// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ares.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listJoinedLobbyMatchPreviewCandidates = `-- name: ListJoinedLobbyMatchPreviewCandidates :many
SELECT
  apollo.users.id AS user_id,
  apollo.users.preferences,
  apollo.users.updated_at AS user_updated_at,
  apollo.lobby_memberships.joined_at,
  apollo.lobby_memberships.updated_at AS membership_updated_at
FROM apollo.lobby_memberships
JOIN apollo.users
  ON apollo.users.id = apollo.lobby_memberships.user_id
WHERE apollo.lobby_memberships.status = 'joined'
ORDER BY user_id ASC
`

type ListJoinedLobbyMatchPreviewCandidatesRow struct {
	UserID              uuid.UUID
	Preferences         []byte
	UserUpdatedAt       pgtype.Timestamptz
	JoinedAt            pgtype.Timestamptz
	MembershipUpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListJoinedLobbyMatchPreviewCandidates(ctx context.Context) ([]ListJoinedLobbyMatchPreviewCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listJoinedLobbyMatchPreviewCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinedLobbyMatchPreviewCandidatesRow
	for rows.Next() {
		var i ListJoinedLobbyMatchPreviewCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Preferences,
			&i.UserUpdatedAt,
			&i.JoinedAt,
			&i.MembershipUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
