// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO apollo.email_verification_tokens (
  user_id,
  email,
  token_hash,
  expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, email, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (ApolloEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken,
		arg.UserID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ApolloEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO apollo.sessions (
  user_id,
  expires_at
)
VALUES ($1, $2)
RETURNING id, user_id, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ApolloSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.ExpiresAt)
	var i ApolloSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO apollo.users (
  student_id,
  display_name,
  email
)
VALUES ($1, $2, $3)
RETURNING id, student_id, display_name, email, role, preferences, created_at, updated_at, email_verified_at
`

type CreateUserParams struct {
	StudentID   string
	DisplayName string
	Email       string
}

type CreateUserRow struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Role            string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.StudentID, arg.DisplayName, arg.Email)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const deletePendingEmailVerificationTokensByUserID = `-- name: DeletePendingEmailVerificationTokensByUserID :exec
DELETE FROM apollo.email_verification_tokens
WHERE user_id = $1
  AND used_at IS NULL
`

func (q *Queries) DeletePendingEmailVerificationTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingEmailVerificationTokensByUserID, userID)
	return err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, user_id, email, token_hash, expires_at, used_at, created_at
FROM apollo.email_verification_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (ApolloEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i ApolloEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, expires_at, revoked_at, created_at
FROM apollo.sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (ApolloSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i ApolloSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionPrincipalByID = `-- name: GetSessionPrincipalByID :one
SELECT s.id,
       s.user_id,
       u.role,
       s.expires_at,
       s.revoked_at,
       s.created_at
FROM apollo.sessions AS s
INNER JOIN apollo.users AS u
  ON u.id = s.user_id
WHERE s.id = $1
LIMIT 1
`

type GetSessionPrincipalByIDRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Role      string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetSessionPrincipalByID(ctx context.Context, id uuid.UUID) (GetSessionPrincipalByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionPrincipalByID, id)
	var i GetSessionPrincipalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, student_id, display_name, email, role, preferences, created_at, updated_at, email_verified_at
FROM apollo.users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Role            string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, student_id, display_name, email, role, preferences, created_at, updated_at, email_verified_at
FROM apollo.users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Role            string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByStudentID = `-- name: GetUserByStudentID :one
SELECT id, student_id, display_name, email, role, preferences, created_at, updated_at, email_verified_at
FROM apollo.users
WHERE student_id = $1
LIMIT 1
`

type GetUserByStudentIDRow struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Role            string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByStudentID(ctx context.Context, studentID string) (GetUserByStudentIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByStudentID, studentID)
	var i GetUserByStudentIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :one
UPDATE apollo.email_verification_tokens
SET used_at = $2
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > $2
RETURNING id, user_id, email, token_hash, expires_at, used_at, created_at
`

type MarkEmailVerificationTokenUsedParams struct {
	TokenHash string
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, arg MarkEmailVerificationTokenUsedParams) (ApolloEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, markEmailVerificationTokenUsed, arg.TokenHash, arg.UsedAt)
	var i ApolloEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE apollo.users
SET email_verified_at = COALESCE(email_verified_at, $2),
    updated_at = $2
WHERE id = $1
RETURNING id, student_id, display_name, email, role, preferences, created_at, updated_at, email_verified_at
`

type MarkUserEmailVerifiedParams struct {
	ID        uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

type MarkUserEmailVerifiedRow struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Role            string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) (MarkUserEmailVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, arg.ID, arg.UpdatedAt)
	var i MarkUserEmailVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE apollo.sessions
SET revoked_at = $2
WHERE id = $1
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE apollo.users
SET role = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, student_id, display_name, email, role, preferences, created_at, updated_at, email_verified_at
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

type SetUserRoleRow struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Role            string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (SetUserRoleRow, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i SetUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE apollo.users
SET preferences = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, student_id, display_name, email, role, preferences, created_at, updated_at, email_verified_at
`

type UpdateUserPreferencesParams struct {
	ID          uuid.UUID
	Preferences []byte
}

type UpdateUserPreferencesRow struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Role            string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UpdateUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences, arg.ID, arg.Preferences)
	var i UpdateUserPreferencesRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}
