// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coaching.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getEffortFeedbackByWorkoutID = `-- name: GetEffortFeedbackByWorkoutID :one
SELECT workout_id, user_id, effort_level, created_at, updated_at
FROM apollo.workout_effort_feedback
WHERE workout_id = $1
LIMIT 1
`

func (q *Queries) GetEffortFeedbackByWorkoutID(ctx context.Context, workoutID uuid.UUID) (ApolloWorkoutEffortFeedback, error) {
	row := q.db.QueryRow(ctx, getEffortFeedbackByWorkoutID, workoutID)
	var i ApolloWorkoutEffortFeedback
	err := row.Scan(
		&i.WorkoutID,
		&i.UserID,
		&i.EffortLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecoveryFeedbackByWorkoutID = `-- name: GetRecoveryFeedbackByWorkoutID :one
SELECT workout_id, user_id, recovery_level, created_at, updated_at
FROM apollo.workout_recovery_feedback
WHERE workout_id = $1
LIMIT 1
`

func (q *Queries) GetRecoveryFeedbackByWorkoutID(ctx context.Context, workoutID uuid.UUID) (ApolloWorkoutRecoveryFeedback, error) {
	row := q.db.QueryRow(ctx, getRecoveryFeedbackByWorkoutID, workoutID)
	var i ApolloWorkoutRecoveryFeedback
	err := row.Scan(
		&i.WorkoutID,
		&i.UserID,
		&i.RecoveryLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEffortFeedbackForFinishedWorkout = `-- name: UpsertEffortFeedbackForFinishedWorkout :one
WITH owned_finished_workout AS (
  SELECT w.id, w.user_id
  FROM apollo.workouts AS w
  WHERE w.id = $1
    AND w.user_id = $2
    AND w.status = 'finished'
)
INSERT INTO apollo.workout_effort_feedback (
  workout_id,
  user_id,
  effort_level
)
SELECT id, user_id, $3
FROM owned_finished_workout
ON CONFLICT (workout_id)
DO UPDATE
SET effort_level = EXCLUDED.effort_level,
    user_id = EXCLUDED.user_id,
    updated_at = NOW()
RETURNING workout_id, user_id, effort_level, created_at, updated_at
`

type UpsertEffortFeedbackForFinishedWorkoutParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	EffortLevel string
}

func (q *Queries) UpsertEffortFeedbackForFinishedWorkout(ctx context.Context, arg UpsertEffortFeedbackForFinishedWorkoutParams) (ApolloWorkoutEffortFeedback, error) {
	row := q.db.QueryRow(ctx, upsertEffortFeedbackForFinishedWorkout, arg.ID, arg.UserID, arg.EffortLevel)
	var i ApolloWorkoutEffortFeedback
	err := row.Scan(
		&i.WorkoutID,
		&i.UserID,
		&i.EffortLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRecoveryFeedbackForFinishedWorkout = `-- name: UpsertRecoveryFeedbackForFinishedWorkout :one
WITH owned_finished_workout AS (
  SELECT w.id, w.user_id
  FROM apollo.workouts AS w
  WHERE w.id = $1
    AND w.user_id = $2
    AND w.status = 'finished'
)
INSERT INTO apollo.workout_recovery_feedback (
  workout_id,
  user_id,
  recovery_level
)
SELECT id, user_id, $3
FROM owned_finished_workout
ON CONFLICT (workout_id)
DO UPDATE
SET recovery_level = EXCLUDED.recovery_level,
    user_id = EXCLUDED.user_id,
    updated_at = NOW()
RETURNING workout_id, user_id, recovery_level, created_at, updated_at
`

type UpsertRecoveryFeedbackForFinishedWorkoutParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	RecoveryLevel string
}

func (q *Queries) UpsertRecoveryFeedbackForFinishedWorkout(ctx context.Context, arg UpsertRecoveryFeedbackForFinishedWorkoutParams) (ApolloWorkoutRecoveryFeedback, error) {
	row := q.db.QueryRow(ctx, upsertRecoveryFeedbackForFinishedWorkout, arg.ID, arg.UserID, arg.RecoveryLevel)
	var i ApolloWorkoutRecoveryFeedback
	err := row.Scan(
		&i.WorkoutID,
		&i.UserID,
		&i.RecoveryLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
