// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition_history.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCompetitionMatch = `-- name: CompleteCompetitionMatch :one
UPDATE apollo.competition_matches
SET status = 'completed',
    updated_at = $2
WHERE id = $1
  AND status = 'in_progress'
RETURNING id,
          competition_session_id,
          match_index,
          status,
          created_at,
          updated_at,
          archived_at
`

type CompleteCompetitionMatchParams struct {
	ID        uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CompleteCompetitionMatch(ctx context.Context, arg CompleteCompetitionMatchParams) (ApolloCompetitionMatch, error) {
	row := q.db.QueryRow(ctx, completeCompetitionMatch, arg.ID, arg.UpdatedAt)
	var i ApolloCompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const completeCompetitionSession = `-- name: CompleteCompetitionSession :one
UPDATE apollo.competition_sessions
SET status = 'completed',
    updated_at = $3
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'in_progress'
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          queue_version,
          status,
          created_at,
          updated_at,
          archived_at
`

type CompleteCompetitionSessionParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	UpdatedAt   pgtype.Timestamptz
}

type CompleteCompetitionSessionRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) CompleteCompetitionSession(ctx context.Context, arg CompleteCompetitionSessionParams) (CompleteCompetitionSessionRow, error) {
	row := q.db.QueryRow(ctx, completeCompetitionSession, arg.ID, arg.OwnerUserID, arg.UpdatedAt)
	var i CompleteCompetitionSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countCompetitionIncompleteActiveMatchesBySessionID = `-- name: CountCompetitionIncompleteActiveMatchesBySessionID :one
SELECT count(*)
FROM apollo.competition_matches
WHERE competition_session_id = $1
  AND status NOT IN ('completed', 'archived')
`

func (q *Queries) CountCompetitionIncompleteActiveMatchesBySessionID(ctx context.Context, competitionSessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetitionIncompleteActiveMatchesBySessionID, competitionSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompetitionMatchResult = `-- name: CreateCompetitionMatchResult :one
INSERT INTO apollo.competition_match_results (
  competition_match_id,
  recorded_by_user_id,
  recorded_at
)
VALUES ($1, $2, $3)
RETURNING competition_match_id,
          recorded_by_user_id,
          recorded_at
`

type CreateCompetitionMatchResultParams struct {
	CompetitionMatchID uuid.UUID
	RecordedByUserID   uuid.UUID
	RecordedAt         pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionMatchResult(ctx context.Context, arg CreateCompetitionMatchResultParams) (ApolloCompetitionMatchResult, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatchResult, arg.CompetitionMatchID, arg.RecordedByUserID, arg.RecordedAt)
	var i ApolloCompetitionMatchResult
	err := row.Scan(&i.CompetitionMatchID, &i.RecordedByUserID, &i.RecordedAt)
	return i, err
}

const createCompetitionMatchResultSide = `-- name: CreateCompetitionMatchResultSide :one
INSERT INTO apollo.competition_match_result_sides (
  competition_match_id,
  side_index,
  competition_session_team_id,
  outcome
)
VALUES ($1, $2, $3, $4)
RETURNING competition_match_id,
          side_index,
          competition_session_team_id,
          outcome
`

type CreateCompetitionMatchResultSideParams struct {
	CompetitionMatchID       uuid.UUID
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
}

func (q *Queries) CreateCompetitionMatchResultSide(ctx context.Context, arg CreateCompetitionMatchResultSideParams) (ApolloCompetitionMatchResultSide, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatchResultSide,
		arg.CompetitionMatchID,
		arg.SideIndex,
		arg.CompetitionSessionTeamID,
		arg.Outcome,
	)
	var i ApolloCompetitionMatchResultSide
	err := row.Scan(
		&i.CompetitionMatchID,
		&i.SideIndex,
		&i.CompetitionSessionTeamID,
		&i.Outcome,
	)
	return i, err
}

const deleteCompetitionMemberRatingsBySportKey = `-- name: DeleteCompetitionMemberRatingsBySportKey :execrows
DELETE FROM apollo.competition_member_ratings
WHERE sport_key = $1
`

func (q *Queries) DeleteCompetitionMemberRatingsBySportKey(ctx context.Context, sportKey string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionMemberRatingsBySportKey, sportKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompetitionMatchResultByMatchID = `-- name: GetCompetitionMatchResultByMatchID :one
SELECT competition_match_id,
       recorded_by_user_id,
       recorded_at
FROM apollo.competition_match_results
WHERE competition_match_id = $1
LIMIT 1
`

func (q *Queries) GetCompetitionMatchResultByMatchID(ctx context.Context, competitionMatchID uuid.UUID) (ApolloCompetitionMatchResult, error) {
	row := q.db.QueryRow(ctx, getCompetitionMatchResultByMatchID, competitionMatchID)
	var i ApolloCompetitionMatchResult
	err := row.Scan(&i.CompetitionMatchID, &i.RecordedByUserID, &i.RecordedAt)
	return i, err
}

const listCompetitionMatchResultRowsBySessionID = `-- name: ListCompetitionMatchResultRowsBySessionID :many
SELECT m.id AS competition_match_id,
       r.recorded_by_user_id,
       r.recorded_at,
       rs.side_index,
       rs.competition_session_team_id,
       rs.outcome
FROM apollo.competition_matches AS m
INNER JOIN apollo.competition_match_results AS r
  ON r.competition_match_id = m.id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_id = m.id
WHERE m.competition_session_id = $1
ORDER BY m.match_index ASC, rs.side_index ASC
`

type ListCompetitionMatchResultRowsBySessionIDRow struct {
	CompetitionMatchID       uuid.UUID
	RecordedByUserID         uuid.UUID
	RecordedAt               pgtype.Timestamptz
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
}

func (q *Queries) ListCompetitionMatchResultRowsBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ListCompetitionMatchResultRowsBySessionIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchResultRowsBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMatchResultRowsBySessionIDRow
	for rows.Next() {
		var i ListCompetitionMatchResultRowsBySessionIDRow
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.RecordedByUserID,
			&i.RecordedAt,
			&i.SideIndex,
			&i.CompetitionSessionTeamID,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMemberHistoryByUserID = `-- name: ListCompetitionMemberHistoryByUserID :many
SELECT m.id AS competition_match_id,
       s.display_name,
       s.sport_key,
       s.facility_key,
       sp.competition_mode,
       sp.sides_per_match,
       s.participants_per_side,
       r.recorded_at,
       rs.outcome
FROM apollo.competition_sessions AS s
INNER JOIN apollo.sports AS sp
  ON sp.sport_key = s.sport_key
INNER JOIN apollo.competition_matches AS m
  ON m.competition_session_id = s.id
INNER JOIN apollo.competition_match_results AS r
  ON r.competition_match_id = m.id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_id = m.id
INNER JOIN apollo.competition_team_roster_members AS rm
  ON rm.competition_session_id = s.id
 AND rm.competition_session_team_id = rs.competition_session_team_id
WHERE rm.user_id = $1
  AND m.status = 'completed'
ORDER BY r.recorded_at DESC, m.id DESC
`

type ListCompetitionMemberHistoryByUserIDRow struct {
	CompetitionMatchID  uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	CompetitionMode     string
	SidesPerMatch       int32
	ParticipantsPerSide int32
	RecordedAt          pgtype.Timestamptz
	Outcome             string
}

func (q *Queries) ListCompetitionMemberHistoryByUserID(ctx context.Context, userID uuid.UUID) ([]ListCompetitionMemberHistoryByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMemberHistoryByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMemberHistoryByUserIDRow
	for rows.Next() {
		var i ListCompetitionMemberHistoryByUserIDRow
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.DisplayName,
			&i.SportKey,
			&i.FacilityKey,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSide,
			&i.RecordedAt,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMemberRatingsByUserID = `-- name: ListCompetitionMemberRatingsByUserID :many
SELECT user_id,
       sport_key,
       mode_key,
       mu,
       sigma,
       matches_played,
       last_played,
       updated_at
FROM apollo.competition_member_ratings
WHERE user_id = $1
ORDER BY sport_key ASC, mode_key ASC
`

func (q *Queries) ListCompetitionMemberRatingsByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloCompetitionMemberRating, error) {
	rows, err := q.db.Query(ctx, listCompetitionMemberRatingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionMemberRating
	for rows.Next() {
		var i ApolloCompetitionMemberRating
		if err := rows.Scan(
			&i.UserID,
			&i.SportKey,
			&i.ModeKey,
			&i.Mu,
			&i.Sigma,
			&i.MatchesPlayed,
			&i.LastPlayed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMemberStatRowsByUserID = `-- name: ListCompetitionMemberStatRowsByUserID :many
SELECT s.sport_key,
       sp.competition_mode,
       sp.sides_per_match,
       s.participants_per_side,
       r.recorded_at,
       rs.outcome
FROM apollo.competition_sessions AS s
INNER JOIN apollo.sports AS sp
  ON sp.sport_key = s.sport_key
INNER JOIN apollo.competition_matches AS m
  ON m.competition_session_id = s.id
INNER JOIN apollo.competition_match_results AS r
  ON r.competition_match_id = m.id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_id = m.id
INNER JOIN apollo.competition_team_roster_members AS rm
  ON rm.competition_session_id = s.id
 AND rm.competition_session_team_id = rs.competition_session_team_id
WHERE rm.user_id = $1
  AND m.status = 'completed'
ORDER BY r.recorded_at ASC, m.id ASC
`

type ListCompetitionMemberStatRowsByUserIDRow struct {
	SportKey            string
	CompetitionMode     string
	SidesPerMatch       int32
	ParticipantsPerSide int32
	RecordedAt          pgtype.Timestamptz
	Outcome             string
}

func (q *Queries) ListCompetitionMemberStatRowsByUserID(ctx context.Context, userID uuid.UUID) ([]ListCompetitionMemberStatRowsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMemberStatRowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMemberStatRowsByUserIDRow
	for rows.Next() {
		var i ListCompetitionMemberStatRowsByUserIDRow
		if err := rows.Scan(
			&i.SportKey,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSide,
			&i.RecordedAt,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionRatingParticipantsBySport = `-- name: ListCompetitionRatingParticipantsBySport :many
SELECT m.id AS competition_match_id,
       s.sport_key,
       sp.competition_mode,
       sp.sides_per_match,
       s.participants_per_side,
       r.recorded_at,
       rs.competition_session_team_id,
       rs.side_index,
       rs.outcome,
       rm.user_id
FROM apollo.competition_sessions AS s
INNER JOIN apollo.sports AS sp
  ON sp.sport_key = s.sport_key
INNER JOIN apollo.competition_matches AS m
  ON m.competition_session_id = s.id
INNER JOIN apollo.competition_match_results AS r
  ON r.competition_match_id = m.id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_id = m.id
INNER JOIN apollo.competition_team_roster_members AS rm
  ON rm.competition_session_id = s.id
 AND rm.competition_session_team_id = rs.competition_session_team_id
WHERE s.sport_key = $1
  AND m.status = 'completed'
ORDER BY r.recorded_at ASC, m.id ASC, rs.side_index ASC, rm.user_id ASC
`

type ListCompetitionRatingParticipantsBySportRow struct {
	CompetitionMatchID       uuid.UUID
	SportKey                 string
	CompetitionMode          string
	SidesPerMatch            int32
	ParticipantsPerSide      int32
	RecordedAt               pgtype.Timestamptz
	CompetitionSessionTeamID uuid.UUID
	SideIndex                int32
	Outcome                  string
	UserID                   uuid.UUID
}

func (q *Queries) ListCompetitionRatingParticipantsBySport(ctx context.Context, sportKey string) ([]ListCompetitionRatingParticipantsBySportRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionRatingParticipantsBySport, sportKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionRatingParticipantsBySportRow
	for rows.Next() {
		var i ListCompetitionRatingParticipantsBySportRow
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.SportKey,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSide,
			&i.RecordedAt,
			&i.CompetitionSessionTeamID,
			&i.SideIndex,
			&i.Outcome,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompetitionMemberRating = `-- name: UpsertCompetitionMemberRating :one
INSERT INTO apollo.competition_member_ratings (
  user_id,
  sport_key,
  mode_key,
  mu,
  sigma,
  matches_played,
  last_played,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, sport_key, mode_key)
DO UPDATE SET
  mu = EXCLUDED.mu,
  sigma = EXCLUDED.sigma,
  matches_played = EXCLUDED.matches_played,
  last_played = EXCLUDED.last_played,
  updated_at = EXCLUDED.updated_at
RETURNING user_id,
          sport_key,
          mode_key,
          mu,
          sigma,
          matches_played,
          last_played,
          updated_at
`

type UpsertCompetitionMemberRatingParams struct {
	UserID        uuid.UUID
	SportKey      string
	ModeKey       string
	Mu            pgtype.Numeric
	Sigma         pgtype.Numeric
	MatchesPlayed int32
	LastPlayed    pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionMemberRating(ctx context.Context, arg UpsertCompetitionMemberRatingParams) (ApolloCompetitionMemberRating, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionMemberRating,
		arg.UserID,
		arg.SportKey,
		arg.ModeKey,
		arg.Mu,
		arg.Sigma,
		arg.MatchesPlayed,
		arg.LastPlayed,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionMemberRating
	err := row.Scan(
		&i.UserID,
		&i.SportKey,
		&i.ModeKey,
		&i.Mu,
		&i.Sigma,
		&i.MatchesPlayed,
		&i.LastPlayed,
		&i.UpdatedAt,
	)
	return i, err
}
