// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCompetitionMatch = `-- name: ArchiveCompetitionMatch :one
UPDATE apollo.competition_matches
SET status = 'archived',
    archived_at = $2,
    updated_at = $2
WHERE id = $1
  AND status = 'draft'
RETURNING id,
          competition_session_id,
          match_index,
          status,
          created_at,
          updated_at,
          archived_at
`

type ArchiveCompetitionMatchParams struct {
	ID         uuid.UUID
	ArchivedAt pgtype.Timestamptz
}

func (q *Queries) ArchiveCompetitionMatch(ctx context.Context, arg ArchiveCompetitionMatchParams) (ApolloCompetitionMatch, error) {
	row := q.db.QueryRow(ctx, archiveCompetitionMatch, arg.ID, arg.ArchivedAt)
	var i ApolloCompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const archiveCompetitionSession = `-- name: ArchiveCompetitionSession :one
UPDATE apollo.competition_sessions
SET status = 'archived',
    archived_at = $3,
    updated_at = $3
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'draft'
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          status,
          created_at,
          updated_at,
          archived_at
`

type ArchiveCompetitionSessionParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	ArchivedAt  pgtype.Timestamptz
}

func (q *Queries) ArchiveCompetitionSession(ctx context.Context, arg ArchiveCompetitionSessionParams) (ApolloCompetitionSession, error) {
	row := q.db.QueryRow(ctx, archiveCompetitionSession, arg.ID, arg.OwnerUserID, arg.ArchivedAt)
	var i ApolloCompetitionSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const competitionSessionHasRosterMemberUser = `-- name: CompetitionSessionHasRosterMemberUser :one
SELECT EXISTS (
    SELECT 1
    FROM apollo.competition_team_roster_members
    WHERE competition_session_id = $1
      AND user_id = $2
)
`

type CompetitionSessionHasRosterMemberUserParams struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
}

func (q *Queries) CompetitionSessionHasRosterMemberUser(ctx context.Context, arg CompetitionSessionHasRosterMemberUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, competitionSessionHasRosterMemberUser, arg.CompetitionSessionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const competitionTeamHasMatchReference = `-- name: CompetitionTeamHasMatchReference :one
SELECT EXISTS (
    SELECT 1
    FROM apollo.competition_match_side_slots AS s
    WHERE s.competition_session_team_id = $1
)
`

func (q *Queries) CompetitionTeamHasMatchReference(ctx context.Context, competitionSessionTeamID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, competitionTeamHasMatchReference, competitionSessionTeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCompetitionRosterMembersByTeamID = `-- name: CountCompetitionRosterMembersByTeamID :one
SELECT count(*)
FROM apollo.competition_team_roster_members
WHERE competition_session_team_id = $1
`

func (q *Queries) CountCompetitionRosterMembersByTeamID(ctx context.Context, competitionSessionTeamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetitionRosterMembersByTeamID, competitionSessionTeamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDraftCompetitionMatchesBySessionID = `-- name: CountDraftCompetitionMatchesBySessionID :one
SELECT count(*)
FROM apollo.competition_matches
WHERE competition_session_id = $1
  AND status = 'draft'
`

func (q *Queries) CountDraftCompetitionMatchesBySessionID(ctx context.Context, competitionSessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDraftCompetitionMatchesBySessionID, competitionSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompetitionMatch = `-- name: CreateCompetitionMatch :one
INSERT INTO apollo.competition_matches (
  competition_session_id,
  match_index,
  status,
  updated_at
)
VALUES ($1, $2, 'draft', NOW())
RETURNING id,
          competition_session_id,
          match_index,
          status,
          created_at,
          updated_at,
          archived_at
`

type CreateCompetitionMatchParams struct {
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
}

func (q *Queries) CreateCompetitionMatch(ctx context.Context, arg CreateCompetitionMatchParams) (ApolloCompetitionMatch, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatch, arg.CompetitionSessionID, arg.MatchIndex)
	var i ApolloCompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createCompetitionMatchSideSlot = `-- name: CreateCompetitionMatchSideSlot :one
INSERT INTO apollo.competition_match_side_slots (
  competition_match_id,
  competition_session_team_id,
  side_index
)
VALUES ($1, $2, $3)
RETURNING competition_match_id,
          competition_session_team_id,
          side_index,
          created_at
`

type CreateCompetitionMatchSideSlotParams struct {
	CompetitionMatchID       uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	SideIndex                int32
}

func (q *Queries) CreateCompetitionMatchSideSlot(ctx context.Context, arg CreateCompetitionMatchSideSlotParams) (ApolloCompetitionMatchSideSlot, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatchSideSlot, arg.CompetitionMatchID, arg.CompetitionSessionTeamID, arg.SideIndex)
	var i ApolloCompetitionMatchSideSlot
	err := row.Scan(
		&i.CompetitionMatchID,
		&i.CompetitionSessionTeamID,
		&i.SideIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionSession = `-- name: CreateCompetitionSession :one
INSERT INTO apollo.competition_sessions (
  owner_user_id,
  display_name,
  sport_key,
  facility_key,
  zone_key,
  participants_per_side,
  status,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, 'draft', NOW())
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          status,
          created_at,
          updated_at,
          archived_at
`

type CreateCompetitionSessionParams struct {
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
}

func (q *Queries) CreateCompetitionSession(ctx context.Context, arg CreateCompetitionSessionParams) (ApolloCompetitionSession, error) {
	row := q.db.QueryRow(ctx, createCompetitionSession,
		arg.OwnerUserID,
		arg.DisplayName,
		arg.SportKey,
		arg.FacilityKey,
		arg.ZoneKey,
		arg.ParticipantsPerSide,
	)
	var i ApolloCompetitionSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createCompetitionSessionTeam = `-- name: CreateCompetitionSessionTeam :one
INSERT INTO apollo.competition_session_teams (
  competition_session_id,
  side_index
)
VALUES ($1, $2)
RETURNING id,
          competition_session_id,
          side_index,
          created_at
`

type CreateCompetitionSessionTeamParams struct {
	CompetitionSessionID uuid.UUID
	SideIndex            int32
}

func (q *Queries) CreateCompetitionSessionTeam(ctx context.Context, arg CreateCompetitionSessionTeamParams) (ApolloCompetitionSessionTeam, error) {
	row := q.db.QueryRow(ctx, createCompetitionSessionTeam, arg.CompetitionSessionID, arg.SideIndex)
	var i ApolloCompetitionSessionTeam
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.SideIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionTeamRosterMember = `-- name: CreateCompetitionTeamRosterMember :one
INSERT INTO apollo.competition_team_roster_members (
  competition_session_id,
  competition_session_team_id,
  user_id,
  slot_index
)
VALUES ($1, $2, $3, $4)
RETURNING competition_session_id,
          competition_session_team_id,
          user_id,
          slot_index,
          created_at
`

type CreateCompetitionTeamRosterMemberParams struct {
	CompetitionSessionID     uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
	SlotIndex                int32
}

func (q *Queries) CreateCompetitionTeamRosterMember(ctx context.Context, arg CreateCompetitionTeamRosterMemberParams) (ApolloCompetitionTeamRosterMember, error) {
	row := q.db.QueryRow(ctx, createCompetitionTeamRosterMember,
		arg.CompetitionSessionID,
		arg.CompetitionSessionTeamID,
		arg.UserID,
		arg.SlotIndex,
	)
	var i ApolloCompetitionTeamRosterMember
	err := row.Scan(
		&i.CompetitionSessionID,
		&i.CompetitionSessionTeamID,
		&i.UserID,
		&i.SlotIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompetitionSessionTeam = `-- name: DeleteCompetitionSessionTeam :execrows
DELETE FROM apollo.competition_session_teams
WHERE id = $1
`

func (q *Queries) DeleteCompetitionSessionTeam(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionSessionTeam, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionTeamRosterMember = `-- name: DeleteCompetitionTeamRosterMember :execrows
DELETE FROM apollo.competition_team_roster_members
WHERE competition_session_team_id = $1
  AND user_id = $2
`

type DeleteCompetitionTeamRosterMemberParams struct {
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
}

func (q *Queries) DeleteCompetitionTeamRosterMember(ctx context.Context, arg DeleteCompetitionTeamRosterMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionTeamRosterMember, arg.CompetitionSessionTeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompetitionMatchByID = `-- name: GetCompetitionMatchByID :one
SELECT id,
       competition_session_id,
       match_index,
       status,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_matches
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompetitionMatchByID(ctx context.Context, id uuid.UUID) (ApolloCompetitionMatch, error) {
	row := q.db.QueryRow(ctx, getCompetitionMatchByID, id)
	var i ApolloCompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCompetitionSessionByIDForOwner = `-- name: GetCompetitionSessionByIDForOwner :one
SELECT id,
       owner_user_id,
       display_name,
       sport_key,
       facility_key,
       zone_key,
       participants_per_side,
       status,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_sessions
WHERE id = $1
  AND owner_user_id = $2
LIMIT 1
`

type GetCompetitionSessionByIDForOwnerParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
}

func (q *Queries) GetCompetitionSessionByIDForOwner(ctx context.Context, arg GetCompetitionSessionByIDForOwnerParams) (ApolloCompetitionSession, error) {
	row := q.db.QueryRow(ctx, getCompetitionSessionByIDForOwner, arg.ID, arg.OwnerUserID)
	var i ApolloCompetitionSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCompetitionSessionTeamByID = `-- name: GetCompetitionSessionTeamByID :one
SELECT id,
       competition_session_id,
       side_index,
       created_at
FROM apollo.competition_session_teams
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompetitionSessionTeamByID(ctx context.Context, id uuid.UUID) (ApolloCompetitionSessionTeam, error) {
	row := q.db.QueryRow(ctx, getCompetitionSessionTeamByID, id)
	var i ApolloCompetitionSessionTeam
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.SideIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listCompetitionMatchSideSlotsBySessionID = `-- name: ListCompetitionMatchSideSlotsBySessionID :many
SELECT s.competition_match_id,
       s.competition_session_team_id,
       s.side_index,
       s.created_at
FROM apollo.competition_match_side_slots AS s
INNER JOIN apollo.competition_matches AS m
  ON m.id = s.competition_match_id
WHERE m.competition_session_id = $1
ORDER BY m.match_index ASC, s.side_index ASC, s.competition_session_team_id ASC
`

func (q *Queries) ListCompetitionMatchSideSlotsBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ApolloCompetitionMatchSideSlot, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchSideSlotsBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionMatchSideSlot
	for rows.Next() {
		var i ApolloCompetitionMatchSideSlot
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.CompetitionSessionTeamID,
			&i.SideIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMatchesBySessionID = `-- name: ListCompetitionMatchesBySessionID :many
SELECT id,
       competition_session_id,
       match_index,
       status,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_matches
WHERE competition_session_id = $1
ORDER BY match_index ASC, id ASC
`

func (q *Queries) ListCompetitionMatchesBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ApolloCompetitionMatch, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchesBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionMatch
	for rows.Next() {
		var i ApolloCompetitionMatch
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionSessionID,
			&i.MatchIndex,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSessionTeamsBySessionID = `-- name: ListCompetitionSessionTeamsBySessionID :many
SELECT id,
       competition_session_id,
       side_index,
       created_at
FROM apollo.competition_session_teams
WHERE competition_session_id = $1
ORDER BY side_index ASC, id ASC
`

func (q *Queries) ListCompetitionSessionTeamsBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ApolloCompetitionSessionTeam, error) {
	rows, err := q.db.Query(ctx, listCompetitionSessionTeamsBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionSessionTeam
	for rows.Next() {
		var i ApolloCompetitionSessionTeam
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionSessionID,
			&i.SideIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSessionsByOwner = `-- name: ListCompetitionSessionsByOwner :many
SELECT id,
       owner_user_id,
       display_name,
       sport_key,
       facility_key,
       zone_key,
       participants_per_side,
       status,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_sessions
WHERE owner_user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCompetitionSessionsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]ApolloCompetitionSession, error) {
	rows, err := q.db.Query(ctx, listCompetitionSessionsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionSession
	for rows.Next() {
		var i ApolloCompetitionSession
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.DisplayName,
			&i.SportKey,
			&i.FacilityKey,
			&i.ZoneKey,
			&i.ParticipantsPerSide,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTeamRosterMembersBySessionID = `-- name: ListCompetitionTeamRosterMembersBySessionID :many
SELECT r.competition_session_team_id,
       r.user_id,
       r.slot_index,
       r.created_at,
       u.display_name
FROM apollo.competition_team_roster_members AS r
INNER JOIN apollo.competition_session_teams AS t
  ON t.id = r.competition_session_team_id
INNER JOIN apollo.users AS u
  ON u.id = r.user_id
WHERE t.competition_session_id = $1
ORDER BY t.side_index ASC, r.slot_index ASC, r.user_id ASC
`

type ListCompetitionTeamRosterMembersBySessionIDRow struct {
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
	SlotIndex                int32
	CreatedAt                pgtype.Timestamptz
	DisplayName              string
}

func (q *Queries) ListCompetitionTeamRosterMembersBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ListCompetitionTeamRosterMembersBySessionIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionTeamRosterMembersBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionTeamRosterMembersBySessionIDRow
	for rows.Next() {
		var i ListCompetitionTeamRosterMembersBySessionIDRow
		if err := rows.Scan(
			&i.CompetitionSessionTeamID,
			&i.UserID,
			&i.SlotIndex,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
