// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCompetitionMatch = `-- name: ArchiveCompetitionMatch :one
UPDATE apollo.competition_matches
SET status = 'archived',
    archived_at = $2,
    updated_at = $2
WHERE id = $1
  AND status IN ('draft', 'assigned', 'in_progress')
RETURNING id,
          competition_session_id,
          match_index,
          status,
          result_version,
          canonical_result_id,
          created_at,
          updated_at,
          archived_at
`

type ArchiveCompetitionMatchParams struct {
	ID         uuid.UUID
	ArchivedAt pgtype.Timestamptz
}

type ArchiveCompetitionMatchRow struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	ResultVersion        int32
	CanonicalResultID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) ArchiveCompetitionMatch(ctx context.Context, arg ArchiveCompetitionMatchParams) (ArchiveCompetitionMatchRow, error) {
	row := q.db.QueryRow(ctx, archiveCompetitionMatch, arg.ID, arg.ArchivedAt)
	var i ArchiveCompetitionMatchRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.ResultVersion,
		&i.CanonicalResultID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const assignCompetitionSessionFromQueue = `-- name: AssignCompetitionSessionFromQueue :one
UPDATE apollo.competition_sessions
SET status = 'assigned',
    queue_version = queue_version + 1,
    updated_at = $4
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'queue_open'
  AND queue_version = $3
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          queue_version,
          status,
          created_at,
          updated_at,
          archived_at
`

type AssignCompetitionSessionFromQueueParams struct {
	ID           uuid.UUID
	OwnerUserID  uuid.UUID
	QueueVersion int32
	UpdatedAt    pgtype.Timestamptz
}

type AssignCompetitionSessionFromQueueRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) AssignCompetitionSessionFromQueue(ctx context.Context, arg AssignCompetitionSessionFromQueueParams) (AssignCompetitionSessionFromQueueRow, error) {
	row := q.db.QueryRow(ctx, assignCompetitionSessionFromQueue,
		arg.ID,
		arg.OwnerUserID,
		arg.QueueVersion,
		arg.UpdatedAt,
	)
	var i AssignCompetitionSessionFromQueueRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const bumpCompetitionSessionQueueVersion = `-- name: BumpCompetitionSessionQueueVersion :one
UPDATE apollo.competition_sessions
SET queue_version = queue_version + 1,
    updated_at = $3
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'queue_open'
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          queue_version,
          status,
          created_at,
          updated_at,
          archived_at
`

type BumpCompetitionSessionQueueVersionParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	UpdatedAt   pgtype.Timestamptz
}

type BumpCompetitionSessionQueueVersionRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) BumpCompetitionSessionQueueVersion(ctx context.Context, arg BumpCompetitionSessionQueueVersionParams) (BumpCompetitionSessionQueueVersionRow, error) {
	row := q.db.QueryRow(ctx, bumpCompetitionSessionQueueVersion, arg.ID, arg.OwnerUserID, arg.UpdatedAt)
	var i BumpCompetitionSessionQueueVersionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const competitionSessionHasRosterMemberUser = `-- name: CompetitionSessionHasRosterMemberUser :one
SELECT EXISTS (
    SELECT 1
    FROM apollo.competition_team_roster_members
    WHERE competition_session_id = $1
      AND user_id = $2
)
`

type CompetitionSessionHasRosterMemberUserParams struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
}

func (q *Queries) CompetitionSessionHasRosterMemberUser(ctx context.Context, arg CompetitionSessionHasRosterMemberUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, competitionSessionHasRosterMemberUser, arg.CompetitionSessionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const competitionTeamHasMatchReference = `-- name: CompetitionTeamHasMatchReference :one
SELECT EXISTS (
    SELECT 1
    FROM apollo.competition_match_side_slots AS s
    WHERE s.competition_session_team_id = $1
)
`

func (q *Queries) CompetitionTeamHasMatchReference(ctx context.Context, competitionSessionTeamID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, competitionTeamHasMatchReference, competitionSessionTeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCompetitionRosterMembersByTeamID = `-- name: CountCompetitionRosterMembersByTeamID :one
SELECT count(*)
FROM apollo.competition_team_roster_members
WHERE competition_session_team_id = $1
`

func (q *Queries) CountCompetitionRosterMembersByTeamID(ctx context.Context, competitionSessionTeamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetitionRosterMembersByTeamID, competitionSessionTeamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompetitionSessionQueueMembersBySessionID = `-- name: CountCompetitionSessionQueueMembersBySessionID :one
SELECT count(*)
FROM apollo.competition_session_queue_members
WHERE competition_session_id = $1
`

func (q *Queries) CountCompetitionSessionQueueMembersBySessionID(ctx context.Context, competitionSessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetitionSessionQueueMembersBySessionID, competitionSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDraftCompetitionMatchesBySessionID = `-- name: CountDraftCompetitionMatchesBySessionID :one
SELECT count(*)
FROM apollo.competition_matches
WHERE competition_session_id = $1
  AND status = 'draft'
`

func (q *Queries) CountDraftCompetitionMatchesBySessionID(ctx context.Context, competitionSessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDraftCompetitionMatchesBySessionID, competitionSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompetitionMatch = `-- name: CreateCompetitionMatch :one
INSERT INTO apollo.competition_matches (
  competition_session_id,
  match_index,
  status,
  updated_at
)
VALUES ($1, $2, $3, NOW())
RETURNING id,
          competition_session_id,
          match_index,
          status,
          result_version,
          canonical_result_id,
          created_at,
          updated_at,
          archived_at
`

type CreateCompetitionMatchParams struct {
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
}

type CreateCompetitionMatchRow struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	ResultVersion        int32
	CanonicalResultID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionMatch(ctx context.Context, arg CreateCompetitionMatchParams) (CreateCompetitionMatchRow, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatch, arg.CompetitionSessionID, arg.MatchIndex, arg.Status)
	var i CreateCompetitionMatchRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.ResultVersion,
		&i.CanonicalResultID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createCompetitionMatchPreviewMember = `-- name: CreateCompetitionMatchPreviewMember :one
INSERT INTO apollo.competition_match_preview_members (
  competition_match_preview_id,
  side_index,
  slot_index,
  competition_queue_intent_id,
  user_id,
  rating_mu,
  rating_sigma,
  rating_matches_played,
  rating_source,
  tier
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING competition_match_preview_id,
          side_index,
          slot_index,
          competition_queue_intent_id,
          user_id,
          rating_mu,
          rating_sigma,
          rating_matches_played,
          rating_source,
          tier
`

type CreateCompetitionMatchPreviewMemberParams struct {
	CompetitionMatchPreviewID uuid.UUID
	SideIndex                 int32
	SlotIndex                 int32
	CompetitionQueueIntentID  uuid.UUID
	UserID                    uuid.UUID
	RatingMu                  pgtype.Numeric
	RatingSigma               pgtype.Numeric
	RatingMatchesPlayed       int32
	RatingSource              string
	Tier                      string
}

func (q *Queries) CreateCompetitionMatchPreviewMember(ctx context.Context, arg CreateCompetitionMatchPreviewMemberParams) (ApolloCompetitionMatchPreviewMember, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatchPreviewMember,
		arg.CompetitionMatchPreviewID,
		arg.SideIndex,
		arg.SlotIndex,
		arg.CompetitionQueueIntentID,
		arg.UserID,
		arg.RatingMu,
		arg.RatingSigma,
		arg.RatingMatchesPlayed,
		arg.RatingSource,
		arg.Tier,
	)
	var i ApolloCompetitionMatchPreviewMember
	err := row.Scan(
		&i.CompetitionMatchPreviewID,
		&i.SideIndex,
		&i.SlotIndex,
		&i.CompetitionQueueIntentID,
		&i.UserID,
		&i.RatingMu,
		&i.RatingSigma,
		&i.RatingMatchesPlayed,
		&i.RatingSource,
		&i.Tier,
	)
	return i, err
}

const createCompetitionMatchSideSlot = `-- name: CreateCompetitionMatchSideSlot :one
INSERT INTO apollo.competition_match_side_slots (
  competition_match_id,
  competition_session_team_id,
  side_index
)
VALUES ($1, $2, $3)
RETURNING competition_match_id,
          competition_session_team_id,
          side_index,
          created_at
`

type CreateCompetitionMatchSideSlotParams struct {
	CompetitionMatchID       uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	SideIndex                int32
}

func (q *Queries) CreateCompetitionMatchSideSlot(ctx context.Context, arg CreateCompetitionMatchSideSlotParams) (ApolloCompetitionMatchSideSlot, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatchSideSlot, arg.CompetitionMatchID, arg.CompetitionSessionTeamID, arg.SideIndex)
	var i ApolloCompetitionMatchSideSlot
	err := row.Scan(
		&i.CompetitionMatchID,
		&i.CompetitionSessionTeamID,
		&i.SideIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionQueueIntentEvent = `-- name: CreateCompetitionQueueIntentEvent :one
INSERT INTO apollo.competition_queue_intent_events (
  competition_queue_intent_id,
  competition_session_id,
  user_id,
  event_type,
  facility_key,
  sport_key,
  mode_key,
  tier,
  status,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  occurred_at
)
VALUES (
  $1,
  $2,
  $3,
  'competition.queue_intent.updated',
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15
)
RETURNING id,
          competition_queue_intent_id,
          competition_session_id,
          user_id,
          event_type,
          facility_key,
          sport_key,
          mode_key,
          tier,
          status,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          occurred_at,
          created_at
`

type CreateCompetitionQueueIntentEventParams struct {
	CompetitionQueueIntentID uuid.UUID
	CompetitionSessionID     uuid.UUID
	UserID                   uuid.UUID
	FacilityKey              string
	SportKey                 string
	ModeKey                  string
	Tier                     string
	Status                   string
	ActorUserID              pgtype.UUID
	ActorRole                *string
	ActorSessionID           pgtype.UUID
	Capability               *string
	TrustedSurfaceKey        *string
	TrustedSurfaceLabel      *string
	OccurredAt               pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionQueueIntentEvent(ctx context.Context, arg CreateCompetitionQueueIntentEventParams) (ApolloCompetitionQueueIntentEvent, error) {
	row := q.db.QueryRow(ctx, createCompetitionQueueIntentEvent,
		arg.CompetitionQueueIntentID,
		arg.CompetitionSessionID,
		arg.UserID,
		arg.FacilityKey,
		arg.SportKey,
		arg.ModeKey,
		arg.Tier,
		arg.Status,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.OccurredAt,
	)
	var i ApolloCompetitionQueueIntentEvent
	err := row.Scan(
		&i.ID,
		&i.CompetitionQueueIntentID,
		&i.CompetitionSessionID,
		&i.UserID,
		&i.EventType,
		&i.FacilityKey,
		&i.SportKey,
		&i.ModeKey,
		&i.Tier,
		&i.Status,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionSession = `-- name: CreateCompetitionSession :one
INSERT INTO apollo.competition_sessions (
  owner_user_id,
  display_name,
  sport_key,
  facility_key,
  zone_key,
  participants_per_side,
  status,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, 'draft', NOW())
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          queue_version,
          status,
          created_at,
          updated_at,
          archived_at
`

type CreateCompetitionSessionParams struct {
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
}

type CreateCompetitionSessionRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionSession(ctx context.Context, arg CreateCompetitionSessionParams) (CreateCompetitionSessionRow, error) {
	row := q.db.QueryRow(ctx, createCompetitionSession,
		arg.OwnerUserID,
		arg.DisplayName,
		arg.SportKey,
		arg.FacilityKey,
		arg.ZoneKey,
		arg.ParticipantsPerSide,
	)
	var i CreateCompetitionSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createCompetitionSessionQueueMember = `-- name: CreateCompetitionSessionQueueMember :one
INSERT INTO apollo.competition_session_queue_members (
  competition_session_id,
  user_id,
  joined_at
)
VALUES ($1, $2, $3)
RETURNING competition_session_id,
          user_id,
          joined_at
`

type CreateCompetitionSessionQueueMemberParams struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
	JoinedAt             pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionSessionQueueMember(ctx context.Context, arg CreateCompetitionSessionQueueMemberParams) (ApolloCompetitionSessionQueueMember, error) {
	row := q.db.QueryRow(ctx, createCompetitionSessionQueueMember, arg.CompetitionSessionID, arg.UserID, arg.JoinedAt)
	var i ApolloCompetitionSessionQueueMember
	err := row.Scan(&i.CompetitionSessionID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createCompetitionSessionTeam = `-- name: CreateCompetitionSessionTeam :one
INSERT INTO apollo.competition_session_teams (
  competition_session_id,
  side_index
)
VALUES ($1, $2)
RETURNING id,
          competition_session_id,
          side_index,
          created_at
`

type CreateCompetitionSessionTeamParams struct {
	CompetitionSessionID uuid.UUID
	SideIndex            int32
}

func (q *Queries) CreateCompetitionSessionTeam(ctx context.Context, arg CreateCompetitionSessionTeamParams) (ApolloCompetitionSessionTeam, error) {
	row := q.db.QueryRow(ctx, createCompetitionSessionTeam, arg.CompetitionSessionID, arg.SideIndex)
	var i ApolloCompetitionSessionTeam
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.SideIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionStaffActionAttribution = `-- name: CreateCompetitionStaffActionAttribution :one
INSERT INTO apollo.competition_staff_action_attributions (
  actor_user_id,
  actor_role,
  session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  action,
  competition_session_id,
  competition_session_team_id,
  competition_match_id,
  subject_user_id,
  occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id,
          actor_user_id,
          actor_role,
          session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          action,
          competition_session_id,
          competition_session_team_id,
          competition_match_id,
          subject_user_id,
          occurred_at
`

type CreateCompetitionStaffActionAttributionParams struct {
	ActorUserID              uuid.UUID
	ActorRole                string
	SessionID                uuid.UUID
	Capability               string
	TrustedSurfaceKey        string
	TrustedSurfaceLabel      *string
	Action                   string
	CompetitionSessionID     pgtype.UUID
	CompetitionSessionTeamID pgtype.UUID
	CompetitionMatchID       pgtype.UUID
	SubjectUserID            pgtype.UUID
	OccurredAt               pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionStaffActionAttribution(ctx context.Context, arg CreateCompetitionStaffActionAttributionParams) (ApolloCompetitionStaffActionAttribution, error) {
	row := q.db.QueryRow(ctx, createCompetitionStaffActionAttribution,
		arg.ActorUserID,
		arg.ActorRole,
		arg.SessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.Action,
		arg.CompetitionSessionID,
		arg.CompetitionSessionTeamID,
		arg.CompetitionMatchID,
		arg.SubjectUserID,
		arg.OccurredAt,
	)
	var i ApolloCompetitionStaffActionAttribution
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorRole,
		&i.SessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.Action,
		&i.CompetitionSessionID,
		&i.CompetitionSessionTeamID,
		&i.CompetitionMatchID,
		&i.SubjectUserID,
		&i.OccurredAt,
	)
	return i, err
}

const createCompetitionTeamRosterMember = `-- name: CreateCompetitionTeamRosterMember :one
INSERT INTO apollo.competition_team_roster_members (
  competition_session_id,
  competition_session_team_id,
  user_id,
  slot_index
)
VALUES ($1, $2, $3, $4)
RETURNING competition_session_id,
          competition_session_team_id,
          user_id,
          slot_index,
          created_at
`

type CreateCompetitionTeamRosterMemberParams struct {
	CompetitionSessionID     uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
	SlotIndex                int32
}

func (q *Queries) CreateCompetitionTeamRosterMember(ctx context.Context, arg CreateCompetitionTeamRosterMemberParams) (ApolloCompetitionTeamRosterMember, error) {
	row := q.db.QueryRow(ctx, createCompetitionTeamRosterMember,
		arg.CompetitionSessionID,
		arg.CompetitionSessionTeamID,
		arg.UserID,
		arg.SlotIndex,
	)
	var i ApolloCompetitionTeamRosterMember
	err := row.Scan(
		&i.CompetitionSessionID,
		&i.CompetitionSessionTeamID,
		&i.UserID,
		&i.SlotIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompetitionMatchPreviewMembersByPreviewID = `-- name: DeleteCompetitionMatchPreviewMembersByPreviewID :execrows
DELETE FROM apollo.competition_match_preview_members
WHERE competition_match_preview_id = $1
`

func (q *Queries) DeleteCompetitionMatchPreviewMembersByPreviewID(ctx context.Context, competitionMatchPreviewID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionMatchPreviewMembersByPreviewID, competitionMatchPreviewID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionSessionQueueMember = `-- name: DeleteCompetitionSessionQueueMember :execrows
DELETE FROM apollo.competition_session_queue_members
WHERE competition_session_id = $1
  AND user_id = $2
`

type DeleteCompetitionSessionQueueMemberParams struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
}

func (q *Queries) DeleteCompetitionSessionQueueMember(ctx context.Context, arg DeleteCompetitionSessionQueueMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionSessionQueueMember, arg.CompetitionSessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionSessionQueueMembersBySessionID = `-- name: DeleteCompetitionSessionQueueMembersBySessionID :execrows
DELETE FROM apollo.competition_session_queue_members
WHERE competition_session_id = $1
`

func (q *Queries) DeleteCompetitionSessionQueueMembersBySessionID(ctx context.Context, competitionSessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionSessionQueueMembersBySessionID, competitionSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionSessionTeam = `-- name: DeleteCompetitionSessionTeam :execrows
DELETE FROM apollo.competition_session_teams
WHERE id = $1
`

func (q *Queries) DeleteCompetitionSessionTeam(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionSessionTeam, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionTeamRosterMember = `-- name: DeleteCompetitionTeamRosterMember :execrows
DELETE FROM apollo.competition_team_roster_members
WHERE competition_session_team_id = $1
  AND user_id = $2
`

type DeleteCompetitionTeamRosterMemberParams struct {
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
}

func (q *Queries) DeleteCompetitionTeamRosterMember(ctx context.Context, arg DeleteCompetitionTeamRosterMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionTeamRosterMember, arg.CompetitionSessionTeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompetitionMatchByID = `-- name: GetCompetitionMatchByID :one
SELECT id,
       competition_session_id,
       match_index,
       status,
       result_version,
       canonical_result_id,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_matches
WHERE id = $1
LIMIT 1
`

type GetCompetitionMatchByIDRow struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	ResultVersion        int32
	CanonicalResultID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) GetCompetitionMatchByID(ctx context.Context, id uuid.UUID) (GetCompetitionMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getCompetitionMatchByID, id)
	var i GetCompetitionMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.ResultVersion,
		&i.CanonicalResultID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCompetitionSessionByID = `-- name: GetCompetitionSessionByID :one
SELECT id,
       owner_user_id,
       display_name,
       sport_key,
       facility_key,
       zone_key,
       participants_per_side,
       queue_version,
       status,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_sessions
WHERE id = $1
LIMIT 1
`

type GetCompetitionSessionByIDRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) GetCompetitionSessionByID(ctx context.Context, id uuid.UUID) (GetCompetitionSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getCompetitionSessionByID, id)
	var i GetCompetitionSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCompetitionSessionTeamByID = `-- name: GetCompetitionSessionTeamByID :one
SELECT id,
       competition_session_id,
       side_index,
       created_at
FROM apollo.competition_session_teams
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompetitionSessionTeamByID(ctx context.Context, id uuid.UUID) (ApolloCompetitionSessionTeam, error) {
	row := q.db.QueryRow(ctx, getCompetitionSessionTeamByID, id)
	var i ApolloCompetitionSessionTeam
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.SideIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listCompetitionMatchPreviewCandidatesBySessionID = `-- name: ListCompetitionMatchPreviewCandidatesBySessionID :many
SELECT qi.id AS competition_queue_intent_id,
       q.competition_session_id,
       q.user_id,
       u.display_name,
       u.preferences,
       q.joined_at,
       qi.facility_key,
       qi.sport_key,
       qi.mode_key,
       qi.tier,
       qi.updated_at AS queue_intent_updated_at,
       r.mu,
       r.sigma,
       r.matches_played,
       r.updated_at AS rating_updated_at
FROM apollo.competition_session_queue_members AS q
INNER JOIN apollo.users AS u
  ON u.id = q.user_id
INNER JOIN apollo.competition_queue_intents AS qi
  ON qi.competition_session_id = q.competition_session_id
 AND qi.user_id = q.user_id
 AND qi.status = 'active'
LEFT JOIN apollo.competition_member_ratings AS r
  ON r.user_id = q.user_id
 AND r.sport_key = qi.sport_key
 AND r.mode_key = qi.mode_key
WHERE q.competition_session_id = $1
ORDER BY q.joined_at ASC, q.user_id ASC
`

type ListCompetitionMatchPreviewCandidatesBySessionIDRow struct {
	CompetitionQueueIntentID uuid.UUID
	CompetitionSessionID     uuid.UUID
	UserID                   uuid.UUID
	DisplayName              string
	Preferences              []byte
	JoinedAt                 pgtype.Timestamptz
	FacilityKey              string
	SportKey                 string
	ModeKey                  string
	Tier                     string
	QueueIntentUpdatedAt     pgtype.Timestamptz
	Mu                       pgtype.Numeric
	Sigma                    pgtype.Numeric
	MatchesPlayed            *int32
	RatingUpdatedAt          pgtype.Timestamptz
}

func (q *Queries) ListCompetitionMatchPreviewCandidatesBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ListCompetitionMatchPreviewCandidatesBySessionIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchPreviewCandidatesBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMatchPreviewCandidatesBySessionIDRow
	for rows.Next() {
		var i ListCompetitionMatchPreviewCandidatesBySessionIDRow
		if err := rows.Scan(
			&i.CompetitionQueueIntentID,
			&i.CompetitionSessionID,
			&i.UserID,
			&i.DisplayName,
			&i.Preferences,
			&i.JoinedAt,
			&i.FacilityKey,
			&i.SportKey,
			&i.ModeKey,
			&i.Tier,
			&i.QueueIntentUpdatedAt,
			&i.Mu,
			&i.Sigma,
			&i.MatchesPlayed,
			&i.RatingUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMatchSideSlotsBySessionID = `-- name: ListCompetitionMatchSideSlotsBySessionID :many
SELECT s.competition_match_id,
       s.competition_session_team_id,
       s.side_index,
       s.created_at
FROM apollo.competition_match_side_slots AS s
INNER JOIN apollo.competition_matches AS m
  ON m.id = s.competition_match_id
WHERE m.competition_session_id = $1
ORDER BY m.match_index ASC, s.side_index ASC, s.competition_session_team_id ASC
`

func (q *Queries) ListCompetitionMatchSideSlotsBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ApolloCompetitionMatchSideSlot, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchSideSlotsBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionMatchSideSlot
	for rows.Next() {
		var i ApolloCompetitionMatchSideSlot
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.CompetitionSessionTeamID,
			&i.SideIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMatchesBySessionID = `-- name: ListCompetitionMatchesBySessionID :many
SELECT id,
       competition_session_id,
       match_index,
       status,
       result_version,
       canonical_result_id,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_matches
WHERE competition_session_id = $1
ORDER BY match_index ASC, id ASC
`

type ListCompetitionMatchesBySessionIDRow struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	ResultVersion        int32
	CanonicalResultID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) ListCompetitionMatchesBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ListCompetitionMatchesBySessionIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchesBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMatchesBySessionIDRow
	for rows.Next() {
		var i ListCompetitionMatchesBySessionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionSessionID,
			&i.MatchIndex,
			&i.Status,
			&i.ResultVersion,
			&i.CanonicalResultID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSessionQueueMembersBySessionID = `-- name: ListCompetitionSessionQueueMembersBySessionID :many
SELECT q.competition_session_id,
       q.user_id,
       q.joined_at,
       u.display_name,
       u.preferences,
       COALESCE(lm.status, 'not_joined') AS lobby_membership_status
FROM apollo.competition_session_queue_members AS q
INNER JOIN apollo.users AS u
  ON u.id = q.user_id
LEFT JOIN apollo.lobby_memberships AS lm
  ON lm.user_id = q.user_id
WHERE q.competition_session_id = $1
ORDER BY q.joined_at ASC, q.user_id ASC
`

type ListCompetitionSessionQueueMembersBySessionIDRow struct {
	CompetitionSessionID  uuid.UUID
	UserID                uuid.UUID
	JoinedAt              pgtype.Timestamptz
	DisplayName           string
	Preferences           []byte
	LobbyMembershipStatus string
}

func (q *Queries) ListCompetitionSessionQueueMembersBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ListCompetitionSessionQueueMembersBySessionIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionSessionQueueMembersBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionSessionQueueMembersBySessionIDRow
	for rows.Next() {
		var i ListCompetitionSessionQueueMembersBySessionIDRow
		if err := rows.Scan(
			&i.CompetitionSessionID,
			&i.UserID,
			&i.JoinedAt,
			&i.DisplayName,
			&i.Preferences,
			&i.LobbyMembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSessionTeamsBySessionID = `-- name: ListCompetitionSessionTeamsBySessionID :many
SELECT id,
       competition_session_id,
       side_index,
       created_at
FROM apollo.competition_session_teams
WHERE competition_session_id = $1
ORDER BY side_index ASC, id ASC
`

func (q *Queries) ListCompetitionSessionTeamsBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ApolloCompetitionSessionTeam, error) {
	rows, err := q.db.Query(ctx, listCompetitionSessionTeamsBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionSessionTeam
	for rows.Next() {
		var i ApolloCompetitionSessionTeam
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionSessionID,
			&i.SideIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSessions = `-- name: ListCompetitionSessions :many
SELECT id,
       owner_user_id,
       display_name,
       sport_key,
       facility_key,
       zone_key,
       participants_per_side,
       queue_version,
       status,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_sessions
ORDER BY created_at DESC, id DESC
`

type ListCompetitionSessionsRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) ListCompetitionSessions(ctx context.Context) ([]ListCompetitionSessionsRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionSessionsRow
	for rows.Next() {
		var i ListCompetitionSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.DisplayName,
			&i.SportKey,
			&i.FacilityKey,
			&i.ZoneKey,
			&i.ParticipantsPerSide,
			&i.QueueVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTeamRosterMembersBySessionID = `-- name: ListCompetitionTeamRosterMembersBySessionID :many
SELECT r.competition_session_team_id,
       r.user_id,
       r.slot_index,
       r.created_at,
       u.display_name
FROM apollo.competition_team_roster_members AS r
INNER JOIN apollo.competition_session_teams AS t
  ON t.id = r.competition_session_team_id
INNER JOIN apollo.users AS u
  ON u.id = r.user_id
WHERE t.competition_session_id = $1
ORDER BY t.side_index ASC, r.slot_index ASC, r.user_id ASC
`

type ListCompetitionTeamRosterMembersBySessionIDRow struct {
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
	SlotIndex                int32
	CreatedAt                pgtype.Timestamptz
	DisplayName              string
}

func (q *Queries) ListCompetitionTeamRosterMembersBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ListCompetitionTeamRosterMembersBySessionIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionTeamRosterMembersBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionTeamRosterMembersBySessionIDRow
	for rows.Next() {
		var i ListCompetitionTeamRosterMembersBySessionIDRow
		if err := rows.Scan(
			&i.CompetitionSessionTeamID,
			&i.UserID,
			&i.SlotIndex,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openCompetitionSessionQueue = `-- name: OpenCompetitionSessionQueue :one
UPDATE apollo.competition_sessions
SET status = 'queue_open',
    queue_version = 1,
    updated_at = $3
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'draft'
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          queue_version,
          status,
          created_at,
          updated_at,
          archived_at
`

type OpenCompetitionSessionQueueParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	UpdatedAt   pgtype.Timestamptz
}

type OpenCompetitionSessionQueueRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) OpenCompetitionSessionQueue(ctx context.Context, arg OpenCompetitionSessionQueueParams) (OpenCompetitionSessionQueueRow, error) {
	row := q.db.QueryRow(ctx, openCompetitionSessionQueue, arg.ID, arg.OwnerUserID, arg.UpdatedAt)
	var i OpenCompetitionSessionQueueRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateCompetitionMatchStatusBySessionID = `-- name: UpdateCompetitionMatchStatusBySessionID :execrows
UPDATE apollo.competition_matches
SET status = $2,
    updated_at = $4,
    archived_at = CASE
        WHEN $2 = 'archived' THEN $4
        ELSE archived_at
    END
WHERE competition_session_id = $1
  AND status = $3
`

type UpdateCompetitionMatchStatusBySessionIDParams struct {
	CompetitionSessionID uuid.UUID
	Status               string
	Status_2             string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionMatchStatusBySessionID(ctx context.Context, arg UpdateCompetitionMatchStatusBySessionIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCompetitionMatchStatusBySessionID,
		arg.CompetitionSessionID,
		arg.Status,
		arg.Status_2,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCompetitionQueueIntentStatus = `-- name: UpdateCompetitionQueueIntentStatus :one
UPDATE apollo.competition_queue_intents
SET status = $3,
    updated_at = $4
WHERE competition_session_id = $1
  AND user_id = $2
RETURNING id,
          competition_session_id,
          user_id,
          facility_key,
          sport_key,
          mode_key,
          tier,
          status,
          created_at,
          updated_at
`

type UpdateCompetitionQueueIntentStatusParams struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
	Status               string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionQueueIntentStatus(ctx context.Context, arg UpdateCompetitionQueueIntentStatusParams) (ApolloCompetitionQueueIntent, error) {
	row := q.db.QueryRow(ctx, updateCompetitionQueueIntentStatus,
		arg.CompetitionSessionID,
		arg.UserID,
		arg.Status,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionQueueIntent
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.UserID,
		&i.FacilityKey,
		&i.SportKey,
		&i.ModeKey,
		&i.Tier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompetitionQueueIntentTier = `-- name: UpdateCompetitionQueueIntentTier :one
UPDATE apollo.competition_queue_intents
SET tier = $3,
    status = 'active',
    updated_at = $4
WHERE competition_session_id = $1
  AND user_id = $2
  AND status = 'active'
RETURNING id,
          competition_session_id,
          user_id,
          facility_key,
          sport_key,
          mode_key,
          tier,
          status,
          created_at,
          updated_at
`

type UpdateCompetitionQueueIntentTierParams struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
	Tier                 string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionQueueIntentTier(ctx context.Context, arg UpdateCompetitionQueueIntentTierParams) (ApolloCompetitionQueueIntent, error) {
	row := q.db.QueryRow(ctx, updateCompetitionQueueIntentTier,
		arg.CompetitionSessionID,
		arg.UserID,
		arg.Tier,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionQueueIntent
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.UserID,
		&i.FacilityKey,
		&i.SportKey,
		&i.ModeKey,
		&i.Tier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompetitionSessionStatus = `-- name: UpdateCompetitionSessionStatus :one
UPDATE apollo.competition_sessions
SET status = $3,
    updated_at = $4,
    archived_at = CASE
        WHEN $3 = 'archived' THEN $4
        ELSE archived_at
    END
WHERE id = $1
  AND owner_user_id = $2
  AND status = $5
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          queue_version,
          status,
          created_at,
          updated_at,
          archived_at
`

type UpdateCompetitionSessionStatusParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Status      string
	UpdatedAt   pgtype.Timestamptz
	Status_2    string
}

type UpdateCompetitionSessionStatusRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionSessionStatus(ctx context.Context, arg UpdateCompetitionSessionStatusParams) (UpdateCompetitionSessionStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCompetitionSessionStatus,
		arg.ID,
		arg.OwnerUserID,
		arg.Status,
		arg.UpdatedAt,
		arg.Status_2,
	)
	var i UpdateCompetitionSessionStatusRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertCompetitionMatchPreview = `-- name: UpsertCompetitionMatchPreview :one
INSERT INTO apollo.competition_match_previews (
  competition_session_id,
  queue_version,
  proposal_index,
  preview_version,
  policy_version,
  rating_engine,
  rating_policy_version,
  facility_key,
  sport_key,
  mode_key,
  tier,
  match_quality,
  predicted_win_probability,
  explanation_code,
  input_watermark,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (
  competition_session_id,
  queue_version,
  proposal_index,
  preview_version,
  policy_version
)
DO UPDATE SET
  rating_engine = EXCLUDED.rating_engine,
  rating_policy_version = EXCLUDED.rating_policy_version,
  facility_key = EXCLUDED.facility_key,
  sport_key = EXCLUDED.sport_key,
  mode_key = EXCLUDED.mode_key,
  tier = EXCLUDED.tier,
  match_quality = EXCLUDED.match_quality,
  predicted_win_probability = EXCLUDED.predicted_win_probability,
  explanation_code = EXCLUDED.explanation_code,
  input_watermark = EXCLUDED.input_watermark,
  updated_at = EXCLUDED.updated_at
RETURNING id,
          competition_session_id,
          queue_version,
          proposal_index,
          preview_version,
          policy_version,
          rating_engine,
          rating_policy_version,
          facility_key,
          sport_key,
          mode_key,
          tier,
          match_quality,
          predicted_win_probability,
          explanation_code,
          input_watermark,
          created_at,
          updated_at
`

type UpsertCompetitionMatchPreviewParams struct {
	CompetitionSessionID    uuid.UUID
	QueueVersion            int32
	ProposalIndex           int32
	PreviewVersion          string
	PolicyVersion           string
	RatingEngine            string
	RatingPolicyVersion     string
	FacilityKey             string
	SportKey                string
	ModeKey                 string
	Tier                    string
	MatchQuality            pgtype.Numeric
	PredictedWinProbability pgtype.Numeric
	ExplanationCode         string
	InputWatermark          pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionMatchPreview(ctx context.Context, arg UpsertCompetitionMatchPreviewParams) (ApolloCompetitionMatchPreview, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionMatchPreview,
		arg.CompetitionSessionID,
		arg.QueueVersion,
		arg.ProposalIndex,
		arg.PreviewVersion,
		arg.PolicyVersion,
		arg.RatingEngine,
		arg.RatingPolicyVersion,
		arg.FacilityKey,
		arg.SportKey,
		arg.ModeKey,
		arg.Tier,
		arg.MatchQuality,
		arg.PredictedWinProbability,
		arg.ExplanationCode,
		arg.InputWatermark,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionMatchPreview
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.QueueVersion,
		&i.ProposalIndex,
		&i.PreviewVersion,
		&i.PolicyVersion,
		&i.RatingEngine,
		&i.RatingPolicyVersion,
		&i.FacilityKey,
		&i.SportKey,
		&i.ModeKey,
		&i.Tier,
		&i.MatchQuality,
		&i.PredictedWinProbability,
		&i.ExplanationCode,
		&i.InputWatermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompetitionMatchPreviewGeneratedEvent = `-- name: UpsertCompetitionMatchPreviewGeneratedEvent :one
INSERT INTO apollo.competition_match_preview_events (
  competition_match_preview_id,
  competition_session_id,
  event_type,
  queue_version,
  preview_version,
  policy_version,
  rating_engine,
  rating_policy_version,
  facility_key,
  sport_key,
  mode_key,
  tier,
  match_quality,
  predicted_win_probability,
  explanation_code,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  occurred_at
)
VALUES (
  $1,
  $2,
  'competition.match_preview.generated',
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21
)
ON CONFLICT (competition_match_preview_id, event_type)
DO UPDATE SET
  queue_version = EXCLUDED.queue_version,
  preview_version = EXCLUDED.preview_version,
  policy_version = EXCLUDED.policy_version,
  rating_engine = EXCLUDED.rating_engine,
  rating_policy_version = EXCLUDED.rating_policy_version,
  facility_key = EXCLUDED.facility_key,
  sport_key = EXCLUDED.sport_key,
  mode_key = EXCLUDED.mode_key,
  tier = EXCLUDED.tier,
  match_quality = EXCLUDED.match_quality,
  predicted_win_probability = EXCLUDED.predicted_win_probability,
  explanation_code = EXCLUDED.explanation_code,
  actor_user_id = EXCLUDED.actor_user_id,
  actor_role = EXCLUDED.actor_role,
  actor_session_id = EXCLUDED.actor_session_id,
  capability = EXCLUDED.capability,
  trusted_surface_key = EXCLUDED.trusted_surface_key,
  trusted_surface_label = EXCLUDED.trusted_surface_label,
  occurred_at = EXCLUDED.occurred_at
RETURNING id,
          competition_match_preview_id,
          competition_session_id,
          event_type,
          queue_version,
          preview_version,
          policy_version,
          rating_engine,
          rating_policy_version,
          facility_key,
          sport_key,
          mode_key,
          tier,
          match_quality,
          predicted_win_probability,
          explanation_code,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          occurred_at,
          created_at
`

type UpsertCompetitionMatchPreviewGeneratedEventParams struct {
	CompetitionMatchPreviewID uuid.UUID
	CompetitionSessionID      uuid.UUID
	QueueVersion              int32
	PreviewVersion            string
	PolicyVersion             string
	RatingEngine              string
	RatingPolicyVersion       string
	FacilityKey               string
	SportKey                  string
	ModeKey                   string
	Tier                      string
	MatchQuality              pgtype.Numeric
	PredictedWinProbability   pgtype.Numeric
	ExplanationCode           string
	ActorUserID               pgtype.UUID
	ActorRole                 *string
	ActorSessionID            pgtype.UUID
	Capability                *string
	TrustedSurfaceKey         *string
	TrustedSurfaceLabel       *string
	OccurredAt                pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionMatchPreviewGeneratedEvent(ctx context.Context, arg UpsertCompetitionMatchPreviewGeneratedEventParams) (ApolloCompetitionMatchPreviewEvent, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionMatchPreviewGeneratedEvent,
		arg.CompetitionMatchPreviewID,
		arg.CompetitionSessionID,
		arg.QueueVersion,
		arg.PreviewVersion,
		arg.PolicyVersion,
		arg.RatingEngine,
		arg.RatingPolicyVersion,
		arg.FacilityKey,
		arg.SportKey,
		arg.ModeKey,
		arg.Tier,
		arg.MatchQuality,
		arg.PredictedWinProbability,
		arg.ExplanationCode,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.OccurredAt,
	)
	var i ApolloCompetitionMatchPreviewEvent
	err := row.Scan(
		&i.ID,
		&i.CompetitionMatchPreviewID,
		&i.CompetitionSessionID,
		&i.EventType,
		&i.QueueVersion,
		&i.PreviewVersion,
		&i.PolicyVersion,
		&i.RatingEngine,
		&i.RatingPolicyVersion,
		&i.FacilityKey,
		&i.SportKey,
		&i.ModeKey,
		&i.Tier,
		&i.MatchQuality,
		&i.PredictedWinProbability,
		&i.ExplanationCode,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCompetitionQueueIntent = `-- name: UpsertCompetitionQueueIntent :one
INSERT INTO apollo.competition_queue_intents (
  competition_session_id,
  user_id,
  facility_key,
  sport_key,
  mode_key,
  tier,
  status,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (competition_session_id, user_id)
DO UPDATE SET
  facility_key = EXCLUDED.facility_key,
  sport_key = EXCLUDED.sport_key,
  mode_key = EXCLUDED.mode_key,
  tier = EXCLUDED.tier,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at
RETURNING id,
          competition_session_id,
          user_id,
          facility_key,
          sport_key,
          mode_key,
          tier,
          status,
          created_at,
          updated_at
`

type UpsertCompetitionQueueIntentParams struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
	FacilityKey          string
	SportKey             string
	ModeKey              string
	Tier                 string
	Status               string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionQueueIntent(ctx context.Context, arg UpsertCompetitionQueueIntentParams) (ApolloCompetitionQueueIntent, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionQueueIntent,
		arg.CompetitionSessionID,
		arg.UserID,
		arg.FacilityKey,
		arg.SportKey,
		arg.ModeKey,
		arg.Tier,
		arg.Status,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionQueueIntent
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.UserID,
		&i.FacilityKey,
		&i.SportKey,
		&i.ModeKey,
		&i.Tier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
