// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition_history.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCompetitionMatchWithResult = `-- name: CompleteCompetitionMatchWithResult :one
UPDATE apollo.competition_matches
SET status = 'completed',
    canonical_result_id = $2,
    result_version = result_version + 1,
    updated_at = $4
WHERE id = $1
  AND status = 'in_progress'
  AND result_version = $3
RETURNING id,
          competition_session_id,
          match_index,
          status,
          result_version,
          canonical_result_id,
          created_at,
          updated_at,
          archived_at
`

type CompleteCompetitionMatchWithResultParams struct {
	ID                uuid.UUID
	CanonicalResultID pgtype.UUID
	ResultVersion     int32
	UpdatedAt         pgtype.Timestamptz
}

type CompleteCompetitionMatchWithResultRow struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	ResultVersion        int32
	CanonicalResultID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) CompleteCompetitionMatchWithResult(ctx context.Context, arg CompleteCompetitionMatchWithResultParams) (CompleteCompetitionMatchWithResultRow, error) {
	row := q.db.QueryRow(ctx, completeCompetitionMatchWithResult,
		arg.ID,
		arg.CanonicalResultID,
		arg.ResultVersion,
		arg.UpdatedAt,
	)
	var i CompleteCompetitionMatchWithResultRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.ResultVersion,
		&i.CanonicalResultID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const completeCompetitionSession = `-- name: CompleteCompetitionSession :one
UPDATE apollo.competition_sessions
SET status = 'completed',
    updated_at = $3
WHERE id = $1
  AND owner_user_id = $2
  AND status = 'in_progress'
RETURNING id,
          owner_user_id,
          display_name,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          queue_version,
          status,
          created_at,
          updated_at,
          archived_at
`

type CompleteCompetitionSessionParams struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	UpdatedAt   pgtype.Timestamptz
}

type CompleteCompetitionSessionRow struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	QueueVersion        int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

func (q *Queries) CompleteCompetitionSession(ctx context.Context, arg CompleteCompetitionSessionParams) (CompleteCompetitionSessionRow, error) {
	row := q.db.QueryRow(ctx, completeCompetitionSession, arg.ID, arg.OwnerUserID, arg.UpdatedAt)
	var i CompleteCompetitionSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.QueueVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countCompetitionIncompleteActiveMatchesBySessionID = `-- name: CountCompetitionIncompleteActiveMatchesBySessionID :one
SELECT count(*)
FROM apollo.competition_matches
WHERE competition_session_id = $1
  AND status NOT IN ('completed', 'archived')
`

func (q *Queries) CountCompetitionIncompleteActiveMatchesBySessionID(ctx context.Context, competitionSessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetitionIncompleteActiveMatchesBySessionID, competitionSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompetitionAnalyticsProjectionRebuiltEvent = `-- name: CreateCompetitionAnalyticsProjectionRebuiltEvent :one
INSERT INTO apollo.competition_analytics_events (
  event_type,
  projection_version,
  projection_watermark,
  sport_key,
  stat_type,
  stat_value,
  source_match_id,
  source_result_id,
  sample_size,
  confidence,
  computed_at
)
VALUES (
  'competition.analytics.projection_rebuilt',
  $1,
  $2,
  $3,
  'projection_rebuilt',
  0,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id,
          event_type,
          projection_version,
          projection_watermark,
          user_id,
          sport_key,
          facility_key,
          mode_key,
          team_scope,
          stat_type,
          stat_value,
          source_match_id,
          source_result_id,
          sample_size,
          confidence,
          computed_at,
          created_at
`

type CreateCompetitionAnalyticsProjectionRebuiltEventParams struct {
	ProjectionVersion   string
	ProjectionWatermark string
	SportKey            string
	SourceMatchID       pgtype.UUID
	SourceResultID      pgtype.UUID
	SampleSize          int32
	Confidence          pgtype.Numeric
	ComputedAt          pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionAnalyticsProjectionRebuiltEvent(ctx context.Context, arg CreateCompetitionAnalyticsProjectionRebuiltEventParams) (ApolloCompetitionAnalyticsEvent, error) {
	row := q.db.QueryRow(ctx, createCompetitionAnalyticsProjectionRebuiltEvent,
		arg.ProjectionVersion,
		arg.ProjectionWatermark,
		arg.SportKey,
		arg.SourceMatchID,
		arg.SourceResultID,
		arg.SampleSize,
		arg.Confidence,
		arg.ComputedAt,
	)
	var i ApolloCompetitionAnalyticsEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ProjectionVersion,
		&i.ProjectionWatermark,
		&i.UserID,
		&i.SportKey,
		&i.FacilityKey,
		&i.ModeKey,
		&i.TeamScope,
		&i.StatType,
		&i.StatValue,
		&i.SourceMatchID,
		&i.SourceResultID,
		&i.SampleSize,
		&i.Confidence,
		&i.ComputedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionAnalyticsStatEvent = `-- name: CreateCompetitionAnalyticsStatEvent :one
INSERT INTO apollo.competition_analytics_events (
  event_type,
  projection_version,
  projection_watermark,
  user_id,
  sport_key,
  facility_key,
  mode_key,
  team_scope,
  stat_type,
  stat_value,
  source_match_id,
  source_result_id,
  sample_size,
  confidence,
  computed_at
)
VALUES (
  'competition.analytics.stat_computed',
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14
)
RETURNING id,
          event_type,
          projection_version,
          projection_watermark,
          user_id,
          sport_key,
          facility_key,
          mode_key,
          team_scope,
          stat_type,
          stat_value,
          source_match_id,
          source_result_id,
          sample_size,
          confidence,
          computed_at,
          created_at
`

type CreateCompetitionAnalyticsStatEventParams struct {
	ProjectionVersion   string
	ProjectionWatermark string
	UserID              pgtype.UUID
	SportKey            string
	FacilityKey         string
	ModeKey             string
	TeamScope           string
	StatType            string
	StatValue           pgtype.Numeric
	SourceMatchID       pgtype.UUID
	SourceResultID      pgtype.UUID
	SampleSize          int32
	Confidence          pgtype.Numeric
	ComputedAt          pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionAnalyticsStatEvent(ctx context.Context, arg CreateCompetitionAnalyticsStatEventParams) (ApolloCompetitionAnalyticsEvent, error) {
	row := q.db.QueryRow(ctx, createCompetitionAnalyticsStatEvent,
		arg.ProjectionVersion,
		arg.ProjectionWatermark,
		arg.UserID,
		arg.SportKey,
		arg.FacilityKey,
		arg.ModeKey,
		arg.TeamScope,
		arg.StatType,
		arg.StatValue,
		arg.SourceMatchID,
		arg.SourceResultID,
		arg.SampleSize,
		arg.Confidence,
		arg.ComputedAt,
	)
	var i ApolloCompetitionAnalyticsEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ProjectionVersion,
		&i.ProjectionWatermark,
		&i.UserID,
		&i.SportKey,
		&i.FacilityKey,
		&i.ModeKey,
		&i.TeamScope,
		&i.StatType,
		&i.StatValue,
		&i.SourceMatchID,
		&i.SourceResultID,
		&i.SampleSize,
		&i.Confidence,
		&i.ComputedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionLifecycleEvent = `-- name: CreateCompetitionLifecycleEvent :one
INSERT INTO apollo.competition_lifecycle_events (
  competition_session_id,
  competition_match_id,
  competition_match_result_id,
  event_type,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  previous_result_status,
  result_status,
  dispute_status,
  correction_id,
  supersedes_result_id,
  occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id,
          competition_session_id,
          competition_match_id,
          competition_match_result_id,
          event_type,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          previous_result_status,
          result_status,
          dispute_status,
          correction_id,
          supersedes_result_id,
          occurred_at
`

type CreateCompetitionLifecycleEventParams struct {
	CompetitionSessionID     uuid.UUID
	CompetitionMatchID       pgtype.UUID
	CompetitionMatchResultID pgtype.UUID
	EventType                string
	ActorUserID              pgtype.UUID
	ActorRole                *string
	ActorSessionID           pgtype.UUID
	Capability               *string
	TrustedSurfaceKey        *string
	TrustedSurfaceLabel      *string
	PreviousResultStatus     *string
	ResultStatus             *string
	DisputeStatus            *string
	CorrectionID             pgtype.UUID
	SupersedesResultID       pgtype.UUID
	OccurredAt               pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionLifecycleEvent(ctx context.Context, arg CreateCompetitionLifecycleEventParams) (ApolloCompetitionLifecycleEvent, error) {
	row := q.db.QueryRow(ctx, createCompetitionLifecycleEvent,
		arg.CompetitionSessionID,
		arg.CompetitionMatchID,
		arg.CompetitionMatchResultID,
		arg.EventType,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.PreviousResultStatus,
		arg.ResultStatus,
		arg.DisputeStatus,
		arg.CorrectionID,
		arg.SupersedesResultID,
		arg.OccurredAt,
	)
	var i ApolloCompetitionLifecycleEvent
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.CompetitionMatchID,
		&i.CompetitionMatchResultID,
		&i.EventType,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.PreviousResultStatus,
		&i.ResultStatus,
		&i.DisputeStatus,
		&i.CorrectionID,
		&i.SupersedesResultID,
		&i.OccurredAt,
	)
	return i, err
}

const createCompetitionMatchResult = `-- name: CreateCompetitionMatchResult :one
INSERT INTO apollo.competition_match_results (
  competition_match_id,
  recorded_by_user_id,
  recorded_at,
  result_status,
  dispute_status,
  correction_id,
  supersedes_result_id,
  finalized_at,
  corrected_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id,
          competition_match_id,
          recorded_by_user_id,
          recorded_at,
          result_status,
          dispute_status,
          correction_id,
          supersedes_result_id,
          finalized_at,
          corrected_at
`

type CreateCompetitionMatchResultParams struct {
	CompetitionMatchID uuid.UUID
	RecordedByUserID   uuid.UUID
	RecordedAt         pgtype.Timestamptz
	ResultStatus       string
	DisputeStatus      string
	CorrectionID       pgtype.UUID
	SupersedesResultID pgtype.UUID
	FinalizedAt        pgtype.Timestamptz
	CorrectedAt        pgtype.Timestamptz
}

type CreateCompetitionMatchResultRow struct {
	ID                 uuid.UUID
	CompetitionMatchID uuid.UUID
	RecordedByUserID   uuid.UUID
	RecordedAt         pgtype.Timestamptz
	ResultStatus       string
	DisputeStatus      string
	CorrectionID       pgtype.UUID
	SupersedesResultID pgtype.UUID
	FinalizedAt        pgtype.Timestamptz
	CorrectedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionMatchResult(ctx context.Context, arg CreateCompetitionMatchResultParams) (CreateCompetitionMatchResultRow, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatchResult,
		arg.CompetitionMatchID,
		arg.RecordedByUserID,
		arg.RecordedAt,
		arg.ResultStatus,
		arg.DisputeStatus,
		arg.CorrectionID,
		arg.SupersedesResultID,
		arg.FinalizedAt,
		arg.CorrectedAt,
	)
	var i CreateCompetitionMatchResultRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionMatchID,
		&i.RecordedByUserID,
		&i.RecordedAt,
		&i.ResultStatus,
		&i.DisputeStatus,
		&i.CorrectionID,
		&i.SupersedesResultID,
		&i.FinalizedAt,
		&i.CorrectedAt,
	)
	return i, err
}

const createCompetitionMatchResultSide = `-- name: CreateCompetitionMatchResultSide :one
INSERT INTO apollo.competition_match_result_sides (
  competition_match_result_id,
  competition_match_id,
  side_index,
  competition_session_team_id,
  outcome
)
VALUES ($1, $2, $3, $4, $5)
RETURNING competition_match_result_id,
          competition_match_id,
          side_index,
          competition_session_team_id,
          outcome
`

type CreateCompetitionMatchResultSideParams struct {
	CompetitionMatchResultID uuid.UUID
	CompetitionMatchID       uuid.UUID
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
}

type CreateCompetitionMatchResultSideRow struct {
	CompetitionMatchResultID uuid.UUID
	CompetitionMatchID       uuid.UUID
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
}

func (q *Queries) CreateCompetitionMatchResultSide(ctx context.Context, arg CreateCompetitionMatchResultSideParams) (CreateCompetitionMatchResultSideRow, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatchResultSide,
		arg.CompetitionMatchResultID,
		arg.CompetitionMatchID,
		arg.SideIndex,
		arg.CompetitionSessionTeamID,
		arg.Outcome,
	)
	var i CreateCompetitionMatchResultSideRow
	err := row.Scan(
		&i.CompetitionMatchResultID,
		&i.CompetitionMatchID,
		&i.SideIndex,
		&i.CompetitionSessionTeamID,
		&i.Outcome,
	)
	return i, err
}

const createCompetitionRatingEvent = `-- name: CreateCompetitionRatingEvent :one
INSERT INTO apollo.competition_rating_events (
  event_type,
  rating_engine,
  engine_version,
  policy_version,
  sport_key,
  mode_key,
  user_id,
  source_result_id,
  mu,
  sigma,
  delta_mu,
  delta_sigma,
  calibration_status,
  inactivity_decay_applied,
  climbing_cap_applied,
  projection_watermark,
  occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id,
          event_type,
          rating_engine,
          engine_version,
          policy_version,
          sport_key,
          mode_key,
          user_id,
          source_result_id,
          mu,
          sigma,
          delta_mu,
          delta_sigma,
          calibration_status,
          inactivity_decay_applied,
          climbing_cap_applied,
          projection_watermark,
          occurred_at,
          created_at
`

type CreateCompetitionRatingEventParams struct {
	EventType              string
	RatingEngine           string
	EngineVersion          string
	PolicyVersion          string
	SportKey               string
	ModeKey                *string
	UserID                 pgtype.UUID
	SourceResultID         pgtype.UUID
	Mu                     pgtype.Numeric
	Sigma                  pgtype.Numeric
	DeltaMu                pgtype.Numeric
	DeltaSigma             pgtype.Numeric
	CalibrationStatus      *string
	InactivityDecayApplied bool
	ClimbingCapApplied     bool
	ProjectionWatermark    string
	OccurredAt             pgtype.Timestamptz
}

type CreateCompetitionRatingEventRow struct {
	ID                     uuid.UUID
	EventType              string
	RatingEngine           string
	EngineVersion          string
	PolicyVersion          string
	SportKey               string
	ModeKey                *string
	UserID                 pgtype.UUID
	SourceResultID         pgtype.UUID
	Mu                     pgtype.Numeric
	Sigma                  pgtype.Numeric
	DeltaMu                pgtype.Numeric
	DeltaSigma             pgtype.Numeric
	CalibrationStatus      *string
	InactivityDecayApplied bool
	ClimbingCapApplied     bool
	ProjectionWatermark    string
	OccurredAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionRatingEvent(ctx context.Context, arg CreateCompetitionRatingEventParams) (CreateCompetitionRatingEventRow, error) {
	row := q.db.QueryRow(ctx, createCompetitionRatingEvent,
		arg.EventType,
		arg.RatingEngine,
		arg.EngineVersion,
		arg.PolicyVersion,
		arg.SportKey,
		arg.ModeKey,
		arg.UserID,
		arg.SourceResultID,
		arg.Mu,
		arg.Sigma,
		arg.DeltaMu,
		arg.DeltaSigma,
		arg.CalibrationStatus,
		arg.InactivityDecayApplied,
		arg.ClimbingCapApplied,
		arg.ProjectionWatermark,
		arg.OccurredAt,
	)
	var i CreateCompetitionRatingEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RatingEngine,
		&i.EngineVersion,
		&i.PolicyVersion,
		&i.SportKey,
		&i.ModeKey,
		&i.UserID,
		&i.SourceResultID,
		&i.Mu,
		&i.Sigma,
		&i.DeltaMu,
		&i.DeltaSigma,
		&i.CalibrationStatus,
		&i.InactivityDecayApplied,
		&i.ClimbingCapApplied,
		&i.ProjectionWatermark,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompetitionAnalyticsProjectionsBySportVersion = `-- name: DeleteCompetitionAnalyticsProjectionsBySportVersion :execrows
DELETE FROM apollo.competition_analytics_projections
WHERE sport_key = $1
  AND projection_version = $2
`

type DeleteCompetitionAnalyticsProjectionsBySportVersionParams struct {
	SportKey          string
	ProjectionVersion string
}

func (q *Queries) DeleteCompetitionAnalyticsProjectionsBySportVersion(ctx context.Context, arg DeleteCompetitionAnalyticsProjectionsBySportVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionAnalyticsProjectionsBySportVersion, arg.SportKey, arg.ProjectionVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionAnalyticsStatEventsBySportVersion = `-- name: DeleteCompetitionAnalyticsStatEventsBySportVersion :execrows
DELETE FROM apollo.competition_analytics_events
WHERE sport_key = $1
  AND projection_version = $2
  AND event_type = 'competition.analytics.stat_computed'
`

type DeleteCompetitionAnalyticsStatEventsBySportVersionParams struct {
	SportKey          string
	ProjectionVersion string
}

func (q *Queries) DeleteCompetitionAnalyticsStatEventsBySportVersion(ctx context.Context, arg DeleteCompetitionAnalyticsStatEventsBySportVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionAnalyticsStatEventsBySportVersion, arg.SportKey, arg.ProjectionVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionMemberRatingsBySportKey = `-- name: DeleteCompetitionMemberRatingsBySportKey :execrows
DELETE FROM apollo.competition_member_ratings
WHERE sport_key = $1
`

func (q *Queries) DeleteCompetitionMemberRatingsBySportKey(ctx context.Context, sportKey string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionMemberRatingsBySportKey, sportKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompetitionRatingComparisonsBySportKey = `-- name: DeleteCompetitionRatingComparisonsBySportKey :execrows
DELETE FROM apollo.competition_rating_comparisons
WHERE sport_key = $1
`

func (q *Queries) DeleteCompetitionRatingComparisonsBySportKey(ctx context.Context, sportKey string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompetitionRatingComparisonsBySportKey, sportKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompetitionCanonicalMatchResultByMatchID = `-- name: GetCompetitionCanonicalMatchResultByMatchID :one
SELECT r.id,
       r.competition_match_id,
       recorded_by_user_id,
       recorded_at,
       result_status,
       dispute_status,
       correction_id,
       supersedes_result_id,
       finalized_at,
       corrected_at
FROM apollo.competition_matches AS m
INNER JOIN apollo.competition_match_results AS r
  ON r.id = m.canonical_result_id
WHERE m.id = $1
LIMIT 1
`

type GetCompetitionCanonicalMatchResultByMatchIDRow struct {
	ID                 uuid.UUID
	CompetitionMatchID uuid.UUID
	RecordedByUserID   uuid.UUID
	RecordedAt         pgtype.Timestamptz
	ResultStatus       string
	DisputeStatus      string
	CorrectionID       pgtype.UUID
	SupersedesResultID pgtype.UUID
	FinalizedAt        pgtype.Timestamptz
	CorrectedAt        pgtype.Timestamptz
}

func (q *Queries) GetCompetitionCanonicalMatchResultByMatchID(ctx context.Context, id uuid.UUID) (GetCompetitionCanonicalMatchResultByMatchIDRow, error) {
	row := q.db.QueryRow(ctx, getCompetitionCanonicalMatchResultByMatchID, id)
	var i GetCompetitionCanonicalMatchResultByMatchIDRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionMatchID,
		&i.RecordedByUserID,
		&i.RecordedAt,
		&i.ResultStatus,
		&i.DisputeStatus,
		&i.CorrectionID,
		&i.SupersedesResultID,
		&i.FinalizedAt,
		&i.CorrectedAt,
	)
	return i, err
}

const listCompetitionAnalyticsParticipantsBySport = `-- name: ListCompetitionAnalyticsParticipantsBySport :many
SELECT m.id AS source_match_id,
       r.id AS source_result_id,
       s.sport_key,
       s.facility_key,
       sp.competition_mode,
       sp.sides_per_match,
       s.participants_per_side,
       r.recorded_at,
       rs.competition_session_team_id,
       rs.side_index,
       rs.outcome,
       rm.user_id,
       (re.id IS NOT NULL)::bool AS rating_event_found,
       COALESCE(re.delta_mu, 0)::numeric AS rating_delta_mu,
       COALESCE(re.mu, 0)::numeric AS rating_mu
FROM apollo.competition_sessions AS s
INNER JOIN apollo.sports AS sp
  ON sp.sport_key = s.sport_key
INNER JOIN apollo.competition_matches AS m
  ON m.competition_session_id = s.id
INNER JOIN apollo.competition_match_results AS r
  ON r.id = m.canonical_result_id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_result_id = r.id
INNER JOIN apollo.competition_team_roster_members AS rm
  ON rm.competition_session_id = s.id
 AND rm.competition_session_team_id = rs.competition_session_team_id
LEFT JOIN apollo.competition_rating_events AS re
  ON re.event_type = 'competition.rating.legacy_computed'
 AND re.rating_engine = 'legacy_elo_like'
 AND re.engine_version = 'legacy_elo_like.v1'
 AND re.policy_version = 'apollo_rating_policy_wrapper_v1'
 AND re.sport_key = s.sport_key
 AND re.mode_key = sp.competition_mode || ':s' || sp.sides_per_match::TEXT || '-p' || s.participants_per_side::TEXT
 AND re.source_result_id = r.id
 AND re.user_id = rm.user_id
WHERE s.sport_key = $1
  AND m.status = 'completed'
  AND r.result_status IN ('finalized', 'corrected')
ORDER BY r.recorded_at ASC, r.id ASC, m.id ASC, rs.side_index ASC, rm.user_id ASC
`

type ListCompetitionAnalyticsParticipantsBySportRow struct {
	SourceMatchID            uuid.UUID
	SourceResultID           uuid.UUID
	SportKey                 string
	FacilityKey              string
	CompetitionMode          string
	SidesPerMatch            int32
	ParticipantsPerSide      int32
	RecordedAt               pgtype.Timestamptz
	CompetitionSessionTeamID uuid.UUID
	SideIndex                int32
	Outcome                  string
	UserID                   uuid.UUID
	RatingEventFound         bool
	RatingDeltaMu            pgtype.Numeric
	RatingMu                 pgtype.Numeric
}

func (q *Queries) ListCompetitionAnalyticsParticipantsBySport(ctx context.Context, sportKey string) ([]ListCompetitionAnalyticsParticipantsBySportRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionAnalyticsParticipantsBySport, sportKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionAnalyticsParticipantsBySportRow
	for rows.Next() {
		var i ListCompetitionAnalyticsParticipantsBySportRow
		if err := rows.Scan(
			&i.SourceMatchID,
			&i.SourceResultID,
			&i.SportKey,
			&i.FacilityKey,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSide,
			&i.RecordedAt,
			&i.CompetitionSessionTeamID,
			&i.SideIndex,
			&i.Outcome,
			&i.UserID,
			&i.RatingEventFound,
			&i.RatingDeltaMu,
			&i.RatingMu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMatchResultRowsBySessionID = `-- name: ListCompetitionMatchResultRowsBySessionID :many
SELECT m.id AS competition_match_id,
       r.id AS competition_match_result_id,
       r.recorded_by_user_id,
       r.recorded_at,
       r.result_status,
       r.dispute_status,
       r.correction_id,
       r.supersedes_result_id,
       r.finalized_at,
       r.corrected_at,
       rs.side_index,
       rs.competition_session_team_id,
       rs.outcome
FROM apollo.competition_matches AS m
INNER JOIN apollo.competition_match_results AS r
  ON r.id = m.canonical_result_id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_result_id = r.id
WHERE m.competition_session_id = $1
ORDER BY m.match_index ASC, rs.side_index ASC
`

type ListCompetitionMatchResultRowsBySessionIDRow struct {
	CompetitionMatchID       uuid.UUID
	CompetitionMatchResultID uuid.UUID
	RecordedByUserID         uuid.UUID
	RecordedAt               pgtype.Timestamptz
	ResultStatus             string
	DisputeStatus            string
	CorrectionID             pgtype.UUID
	SupersedesResultID       pgtype.UUID
	FinalizedAt              pgtype.Timestamptz
	CorrectedAt              pgtype.Timestamptz
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
}

func (q *Queries) ListCompetitionMatchResultRowsBySessionID(ctx context.Context, competitionSessionID uuid.UUID) ([]ListCompetitionMatchResultRowsBySessionIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchResultRowsBySessionID, competitionSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMatchResultRowsBySessionIDRow
	for rows.Next() {
		var i ListCompetitionMatchResultRowsBySessionIDRow
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.CompetitionMatchResultID,
			&i.RecordedByUserID,
			&i.RecordedAt,
			&i.ResultStatus,
			&i.DisputeStatus,
			&i.CorrectionID,
			&i.SupersedesResultID,
			&i.FinalizedAt,
			&i.CorrectedAt,
			&i.SideIndex,
			&i.CompetitionSessionTeamID,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMemberHistoryByUserID = `-- name: ListCompetitionMemberHistoryByUserID :many
SELECT m.id AS competition_match_id,
       r.id AS competition_match_result_id,
       s.display_name,
       s.sport_key,
       s.facility_key,
       sp.competition_mode,
       sp.sides_per_match,
       s.participants_per_side,
       r.recorded_at,
       rs.outcome
FROM apollo.competition_sessions AS s
INNER JOIN apollo.sports AS sp
  ON sp.sport_key = s.sport_key
INNER JOIN apollo.competition_matches AS m
  ON m.competition_session_id = s.id
INNER JOIN apollo.competition_match_results AS r
  ON r.id = m.canonical_result_id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_result_id = r.id
INNER JOIN apollo.competition_team_roster_members AS rm
  ON rm.competition_session_id = s.id
 AND rm.competition_session_team_id = rs.competition_session_team_id
WHERE rm.user_id = $1
  AND m.status = 'completed'
  AND r.result_status IN ('finalized', 'corrected')
ORDER BY r.recorded_at DESC, m.id DESC
`

type ListCompetitionMemberHistoryByUserIDRow struct {
	CompetitionMatchID       uuid.UUID
	CompetitionMatchResultID uuid.UUID
	DisplayName              string
	SportKey                 string
	FacilityKey              string
	CompetitionMode          string
	SidesPerMatch            int32
	ParticipantsPerSide      int32
	RecordedAt               pgtype.Timestamptz
	Outcome                  string
}

func (q *Queries) ListCompetitionMemberHistoryByUserID(ctx context.Context, userID uuid.UUID) ([]ListCompetitionMemberHistoryByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMemberHistoryByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMemberHistoryByUserIDRow
	for rows.Next() {
		var i ListCompetitionMemberHistoryByUserIDRow
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.CompetitionMatchResultID,
			&i.DisplayName,
			&i.SportKey,
			&i.FacilityKey,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSide,
			&i.RecordedAt,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMemberRatingsByUserID = `-- name: ListCompetitionMemberRatingsByUserID :many
SELECT user_id,
       sport_key,
       mode_key,
       mu,
       sigma,
       matches_played,
       last_played,
       updated_at,
       rating_engine,
       engine_version,
       policy_version,
       calibration_status,
       last_inactivity_decay_at,
       inactivity_decay_count,
       climbing_cap_applied
FROM apollo.competition_member_ratings
WHERE user_id = $1
ORDER BY sport_key ASC, mode_key ASC
`

type ListCompetitionMemberRatingsByUserIDRow struct {
	UserID                uuid.UUID
	SportKey              string
	ModeKey               string
	Mu                    pgtype.Numeric
	Sigma                 pgtype.Numeric
	MatchesPlayed         int32
	LastPlayed            pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RatingEngine          string
	EngineVersion         string
	PolicyVersion         string
	CalibrationStatus     string
	LastInactivityDecayAt pgtype.Timestamptz
	InactivityDecayCount  int32
	ClimbingCapApplied    bool
}

func (q *Queries) ListCompetitionMemberRatingsByUserID(ctx context.Context, userID uuid.UUID) ([]ListCompetitionMemberRatingsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMemberRatingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMemberRatingsByUserIDRow
	for rows.Next() {
		var i ListCompetitionMemberRatingsByUserIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.SportKey,
			&i.ModeKey,
			&i.Mu,
			&i.Sigma,
			&i.MatchesPlayed,
			&i.LastPlayed,
			&i.UpdatedAt,
			&i.RatingEngine,
			&i.EngineVersion,
			&i.PolicyVersion,
			&i.CalibrationStatus,
			&i.LastInactivityDecayAt,
			&i.InactivityDecayCount,
			&i.ClimbingCapApplied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionMemberStatRowsByUserID = `-- name: ListCompetitionMemberStatRowsByUserID :many
SELECT s.sport_key,
       sp.competition_mode,
       sp.sides_per_match,
       s.participants_per_side,
       r.recorded_at,
       rs.outcome
FROM apollo.competition_sessions AS s
INNER JOIN apollo.sports AS sp
  ON sp.sport_key = s.sport_key
INNER JOIN apollo.competition_matches AS m
  ON m.competition_session_id = s.id
INNER JOIN apollo.competition_match_results AS r
  ON r.id = m.canonical_result_id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_result_id = r.id
INNER JOIN apollo.competition_team_roster_members AS rm
  ON rm.competition_session_id = s.id
 AND rm.competition_session_team_id = rs.competition_session_team_id
WHERE rm.user_id = $1
  AND m.status = 'completed'
  AND r.result_status IN ('finalized', 'corrected')
ORDER BY r.recorded_at ASC, m.id ASC
`

type ListCompetitionMemberStatRowsByUserIDRow struct {
	SportKey            string
	CompetitionMode     string
	SidesPerMatch       int32
	ParticipantsPerSide int32
	RecordedAt          pgtype.Timestamptz
	Outcome             string
}

func (q *Queries) ListCompetitionMemberStatRowsByUserID(ctx context.Context, userID uuid.UUID) ([]ListCompetitionMemberStatRowsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMemberStatRowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMemberStatRowsByUserIDRow
	for rows.Next() {
		var i ListCompetitionMemberStatRowsByUserIDRow
		if err := rows.Scan(
			&i.SportKey,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSide,
			&i.RecordedAt,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionRatingParticipantsBySport = `-- name: ListCompetitionRatingParticipantsBySport :many
SELECT m.id AS competition_match_id,
       r.id AS competition_match_result_id,
       s.sport_key,
       sp.competition_mode,
       sp.sides_per_match,
       s.participants_per_side,
       r.recorded_at,
       rs.competition_session_team_id,
       rs.side_index,
       rs.outcome,
       rm.user_id
FROM apollo.competition_sessions AS s
INNER JOIN apollo.sports AS sp
  ON sp.sport_key = s.sport_key
INNER JOIN apollo.competition_matches AS m
  ON m.competition_session_id = s.id
INNER JOIN apollo.competition_match_results AS r
  ON r.id = m.canonical_result_id
INNER JOIN apollo.competition_match_result_sides AS rs
  ON rs.competition_match_result_id = r.id
INNER JOIN apollo.competition_team_roster_members AS rm
  ON rm.competition_session_id = s.id
 AND rm.competition_session_team_id = rs.competition_session_team_id
WHERE s.sport_key = $1
  AND m.status = 'completed'
  AND r.result_status IN ('finalized', 'corrected')
ORDER BY r.recorded_at ASC, m.id ASC, rs.side_index ASC, rm.user_id ASC
`

type ListCompetitionRatingParticipantsBySportRow struct {
	CompetitionMatchID       uuid.UUID
	CompetitionMatchResultID uuid.UUID
	SportKey                 string
	CompetitionMode          string
	SidesPerMatch            int32
	ParticipantsPerSide      int32
	RecordedAt               pgtype.Timestamptz
	CompetitionSessionTeamID uuid.UUID
	SideIndex                int32
	Outcome                  string
	UserID                   uuid.UUID
}

func (q *Queries) ListCompetitionRatingParticipantsBySport(ctx context.Context, sportKey string) ([]ListCompetitionRatingParticipantsBySportRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionRatingParticipantsBySport, sportKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionRatingParticipantsBySportRow
	for rows.Next() {
		var i ListCompetitionRatingParticipantsBySportRow
		if err := rows.Scan(
			&i.CompetitionMatchID,
			&i.CompetitionMatchResultID,
			&i.SportKey,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSide,
			&i.RecordedAt,
			&i.CompetitionSessionTeamID,
			&i.SideIndex,
			&i.Outcome,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetitionMatchCanonicalResult = `-- name: UpdateCompetitionMatchCanonicalResult :one
UPDATE apollo.competition_matches
SET canonical_result_id = $2,
    result_version = result_version + 1,
    updated_at = $4
WHERE id = $1
  AND result_version = $3
RETURNING id,
          competition_session_id,
          match_index,
          status,
          result_version,
          canonical_result_id,
          created_at,
          updated_at,
          archived_at
`

type UpdateCompetitionMatchCanonicalResultParams struct {
	ID                uuid.UUID
	CanonicalResultID pgtype.UUID
	ResultVersion     int32
	UpdatedAt         pgtype.Timestamptz
}

type UpdateCompetitionMatchCanonicalResultRow struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	ResultVersion        int32
	CanonicalResultID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionMatchCanonicalResult(ctx context.Context, arg UpdateCompetitionMatchCanonicalResultParams) (UpdateCompetitionMatchCanonicalResultRow, error) {
	row := q.db.QueryRow(ctx, updateCompetitionMatchCanonicalResult,
		arg.ID,
		arg.CanonicalResultID,
		arg.ResultVersion,
		arg.UpdatedAt,
	)
	var i UpdateCompetitionMatchCanonicalResultRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.MatchIndex,
		&i.Status,
		&i.ResultVersion,
		&i.CanonicalResultID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateCompetitionMatchResultStatus = `-- name: UpdateCompetitionMatchResultStatus :one
UPDATE apollo.competition_match_results
SET result_status = $2,
    dispute_status = $3,
    finalized_at = CASE
        WHEN $2 = 'finalized' THEN $5
        ELSE finalized_at
    END,
    corrected_at = CASE
        WHEN $2 = 'corrected' THEN $5
        ELSE corrected_at
    END
WHERE id = $1
  AND result_status = $4
RETURNING id,
          competition_match_id,
          recorded_by_user_id,
          recorded_at,
          result_status,
          dispute_status,
          correction_id,
          supersedes_result_id,
          finalized_at,
          corrected_at
`

type UpdateCompetitionMatchResultStatusParams struct {
	ID             uuid.UUID
	ResultStatus   string
	DisputeStatus  string
	ResultStatus_2 string
	FinalizedAt    pgtype.Timestamptz
}

type UpdateCompetitionMatchResultStatusRow struct {
	ID                 uuid.UUID
	CompetitionMatchID uuid.UUID
	RecordedByUserID   uuid.UUID
	RecordedAt         pgtype.Timestamptz
	ResultStatus       string
	DisputeStatus      string
	CorrectionID       pgtype.UUID
	SupersedesResultID pgtype.UUID
	FinalizedAt        pgtype.Timestamptz
	CorrectedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionMatchResultStatus(ctx context.Context, arg UpdateCompetitionMatchResultStatusParams) (UpdateCompetitionMatchResultStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCompetitionMatchResultStatus,
		arg.ID,
		arg.ResultStatus,
		arg.DisputeStatus,
		arg.ResultStatus_2,
		arg.FinalizedAt,
	)
	var i UpdateCompetitionMatchResultStatusRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionMatchID,
		&i.RecordedByUserID,
		&i.RecordedAt,
		&i.ResultStatus,
		&i.DisputeStatus,
		&i.CorrectionID,
		&i.SupersedesResultID,
		&i.FinalizedAt,
		&i.CorrectedAt,
	)
	return i, err
}

const upsertCompetitionAnalyticsProjection = `-- name: UpsertCompetitionAnalyticsProjection :one
INSERT INTO apollo.competition_analytics_projections (
  user_id,
  sport_key,
  facility_key,
  mode_key,
  team_scope,
  stat_type,
  stat_value,
  source_match_id,
  source_result_id,
  sample_size,
  confidence,
  computed_at,
  projection_version,
  projection_watermark,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15
)
ON CONFLICT (
  projection_version,
  user_id,
  sport_key,
  facility_key,
  mode_key,
  team_scope,
  stat_type
)
DO UPDATE SET
  stat_value = EXCLUDED.stat_value,
  source_match_id = EXCLUDED.source_match_id,
  source_result_id = EXCLUDED.source_result_id,
  sample_size = EXCLUDED.sample_size,
  confidence = EXCLUDED.confidence,
  computed_at = EXCLUDED.computed_at,
  projection_watermark = EXCLUDED.projection_watermark,
  updated_at = EXCLUDED.updated_at
RETURNING id,
          user_id,
          sport_key,
          facility_key,
          mode_key,
          team_scope,
          stat_type,
          stat_value,
          source_match_id,
          source_result_id,
          sample_size,
          confidence,
          computed_at,
          projection_version,
          projection_watermark,
          created_at,
          updated_at
`

type UpsertCompetitionAnalyticsProjectionParams struct {
	UserID              uuid.UUID
	SportKey            string
	FacilityKey         string
	ModeKey             string
	TeamScope           string
	StatType            string
	StatValue           pgtype.Numeric
	SourceMatchID       pgtype.UUID
	SourceResultID      pgtype.UUID
	SampleSize          int32
	Confidence          pgtype.Numeric
	ComputedAt          pgtype.Timestamptz
	ProjectionVersion   string
	ProjectionWatermark string
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionAnalyticsProjection(ctx context.Context, arg UpsertCompetitionAnalyticsProjectionParams) (ApolloCompetitionAnalyticsProjection, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionAnalyticsProjection,
		arg.UserID,
		arg.SportKey,
		arg.FacilityKey,
		arg.ModeKey,
		arg.TeamScope,
		arg.StatType,
		arg.StatValue,
		arg.SourceMatchID,
		arg.SourceResultID,
		arg.SampleSize,
		arg.Confidence,
		arg.ComputedAt,
		arg.ProjectionVersion,
		arg.ProjectionWatermark,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionAnalyticsProjection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SportKey,
		&i.FacilityKey,
		&i.ModeKey,
		&i.TeamScope,
		&i.StatType,
		&i.StatValue,
		&i.SourceMatchID,
		&i.SourceResultID,
		&i.SampleSize,
		&i.Confidence,
		&i.ComputedAt,
		&i.ProjectionVersion,
		&i.ProjectionWatermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompetitionLegacyRatingEvent = `-- name: UpsertCompetitionLegacyRatingEvent :one
INSERT INTO apollo.competition_rating_events (
  event_type,
  rating_engine,
  engine_version,
  policy_version,
  sport_key,
  mode_key,
  user_id,
  source_result_id,
  mu,
  sigma,
  delta_mu,
  delta_sigma,
  calibration_status,
  inactivity_decay_applied,
  climbing_cap_applied,
  projection_watermark,
  occurred_at
)
VALUES (
  'competition.rating.legacy_computed',
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
)
ON CONFLICT (
  rating_engine,
  engine_version,
  policy_version,
  sport_key,
  mode_key,
  source_result_id,
  user_id
)
WHERE event_type = 'competition.rating.legacy_computed'
DO UPDATE SET
  mu = EXCLUDED.mu,
  sigma = EXCLUDED.sigma,
  delta_mu = EXCLUDED.delta_mu,
  delta_sigma = EXCLUDED.delta_sigma,
  calibration_status = EXCLUDED.calibration_status,
  inactivity_decay_applied = EXCLUDED.inactivity_decay_applied,
  climbing_cap_applied = EXCLUDED.climbing_cap_applied,
  projection_watermark = EXCLUDED.projection_watermark,
  occurred_at = EXCLUDED.occurred_at
RETURNING id,
          event_type,
          rating_engine,
          engine_version,
          policy_version,
          sport_key,
          mode_key,
          user_id,
          source_result_id,
          mu,
          sigma,
          delta_mu,
          delta_sigma,
          calibration_status,
          inactivity_decay_applied,
          climbing_cap_applied,
          projection_watermark,
          occurred_at,
          created_at
`

type UpsertCompetitionLegacyRatingEventParams struct {
	RatingEngine           string
	EngineVersion          string
	PolicyVersion          string
	SportKey               string
	ModeKey                *string
	UserID                 pgtype.UUID
	SourceResultID         pgtype.UUID
	Mu                     pgtype.Numeric
	Sigma                  pgtype.Numeric
	DeltaMu                pgtype.Numeric
	DeltaSigma             pgtype.Numeric
	CalibrationStatus      *string
	InactivityDecayApplied bool
	ClimbingCapApplied     bool
	ProjectionWatermark    string
	OccurredAt             pgtype.Timestamptz
}

type UpsertCompetitionLegacyRatingEventRow struct {
	ID                     uuid.UUID
	EventType              string
	RatingEngine           string
	EngineVersion          string
	PolicyVersion          string
	SportKey               string
	ModeKey                *string
	UserID                 pgtype.UUID
	SourceResultID         pgtype.UUID
	Mu                     pgtype.Numeric
	Sigma                  pgtype.Numeric
	DeltaMu                pgtype.Numeric
	DeltaSigma             pgtype.Numeric
	CalibrationStatus      *string
	InactivityDecayApplied bool
	ClimbingCapApplied     bool
	ProjectionWatermark    string
	OccurredAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionLegacyRatingEvent(ctx context.Context, arg UpsertCompetitionLegacyRatingEventParams) (UpsertCompetitionLegacyRatingEventRow, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionLegacyRatingEvent,
		arg.RatingEngine,
		arg.EngineVersion,
		arg.PolicyVersion,
		arg.SportKey,
		arg.ModeKey,
		arg.UserID,
		arg.SourceResultID,
		arg.Mu,
		arg.Sigma,
		arg.DeltaMu,
		arg.DeltaSigma,
		arg.CalibrationStatus,
		arg.InactivityDecayApplied,
		arg.ClimbingCapApplied,
		arg.ProjectionWatermark,
		arg.OccurredAt,
	)
	var i UpsertCompetitionLegacyRatingEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RatingEngine,
		&i.EngineVersion,
		&i.PolicyVersion,
		&i.SportKey,
		&i.ModeKey,
		&i.UserID,
		&i.SourceResultID,
		&i.Mu,
		&i.Sigma,
		&i.DeltaMu,
		&i.DeltaSigma,
		&i.CalibrationStatus,
		&i.InactivityDecayApplied,
		&i.ClimbingCapApplied,
		&i.ProjectionWatermark,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCompetitionMemberRating = `-- name: UpsertCompetitionMemberRating :one
INSERT INTO apollo.competition_member_ratings (
  user_id,
  sport_key,
  mode_key,
  mu,
  sigma,
  matches_played,
  last_played,
  updated_at,
  rating_engine,
  engine_version,
  policy_version,
  source_result_id,
  rating_event_id,
  projection_watermark,
  calibration_status,
  last_inactivity_decay_at,
  inactivity_decay_count,
  climbing_cap_applied
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (user_id, sport_key, mode_key)
DO UPDATE SET
  mu = EXCLUDED.mu,
  sigma = EXCLUDED.sigma,
  matches_played = EXCLUDED.matches_played,
  last_played = EXCLUDED.last_played,
  updated_at = EXCLUDED.updated_at,
  rating_engine = EXCLUDED.rating_engine,
  engine_version = EXCLUDED.engine_version,
  policy_version = EXCLUDED.policy_version,
  source_result_id = EXCLUDED.source_result_id,
  rating_event_id = EXCLUDED.rating_event_id,
  projection_watermark = EXCLUDED.projection_watermark,
  calibration_status = EXCLUDED.calibration_status,
  last_inactivity_decay_at = EXCLUDED.last_inactivity_decay_at,
  inactivity_decay_count = EXCLUDED.inactivity_decay_count,
  climbing_cap_applied = EXCLUDED.climbing_cap_applied
RETURNING user_id,
          sport_key,
          mode_key,
          mu,
          sigma,
          matches_played,
          last_played,
          updated_at,
          rating_engine,
          engine_version,
          policy_version,
          source_result_id,
          rating_event_id,
          projection_watermark,
          calibration_status,
          last_inactivity_decay_at,
          inactivity_decay_count,
          climbing_cap_applied
`

type UpsertCompetitionMemberRatingParams struct {
	UserID                uuid.UUID
	SportKey              string
	ModeKey               string
	Mu                    pgtype.Numeric
	Sigma                 pgtype.Numeric
	MatchesPlayed         int32
	LastPlayed            pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RatingEngine          string
	EngineVersion         string
	PolicyVersion         string
	SourceResultID        pgtype.UUID
	RatingEventID         pgtype.UUID
	ProjectionWatermark   string
	CalibrationStatus     string
	LastInactivityDecayAt pgtype.Timestamptz
	InactivityDecayCount  int32
	ClimbingCapApplied    bool
}

func (q *Queries) UpsertCompetitionMemberRating(ctx context.Context, arg UpsertCompetitionMemberRatingParams) (ApolloCompetitionMemberRating, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionMemberRating,
		arg.UserID,
		arg.SportKey,
		arg.ModeKey,
		arg.Mu,
		arg.Sigma,
		arg.MatchesPlayed,
		arg.LastPlayed,
		arg.UpdatedAt,
		arg.RatingEngine,
		arg.EngineVersion,
		arg.PolicyVersion,
		arg.SourceResultID,
		arg.RatingEventID,
		arg.ProjectionWatermark,
		arg.CalibrationStatus,
		arg.LastInactivityDecayAt,
		arg.InactivityDecayCount,
		arg.ClimbingCapApplied,
	)
	var i ApolloCompetitionMemberRating
	err := row.Scan(
		&i.UserID,
		&i.SportKey,
		&i.ModeKey,
		&i.Mu,
		&i.Sigma,
		&i.MatchesPlayed,
		&i.LastPlayed,
		&i.UpdatedAt,
		&i.RatingEngine,
		&i.EngineVersion,
		&i.PolicyVersion,
		&i.SourceResultID,
		&i.RatingEventID,
		&i.ProjectionWatermark,
		&i.CalibrationStatus,
		&i.LastInactivityDecayAt,
		&i.InactivityDecayCount,
		&i.ClimbingCapApplied,
	)
	return i, err
}

const upsertCompetitionOpenSkillComputedEvent = `-- name: UpsertCompetitionOpenSkillComputedEvent :one
INSERT INTO apollo.competition_rating_events (
  event_type,
  rating_engine,
  engine_version,
  policy_version,
  sport_key,
  mode_key,
  user_id,
  source_result_id,
  legacy_mu,
  legacy_sigma,
  openskill_mu,
  openskill_sigma,
  delta_from_legacy,
  accepted_delta_budget,
  comparison_scenario,
  projection_watermark,
  occurred_at
)
VALUES (
  'competition.rating.openskill_computed',
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
)
ON CONFLICT (
  rating_engine,
  engine_version,
  policy_version,
  sport_key,
  mode_key,
  source_result_id,
  user_id,
  comparison_scenario
)
WHERE event_type = 'competition.rating.openskill_computed'
DO UPDATE SET
  legacy_mu = EXCLUDED.legacy_mu,
  legacy_sigma = EXCLUDED.legacy_sigma,
  openskill_mu = EXCLUDED.openskill_mu,
  openskill_sigma = EXCLUDED.openskill_sigma,
  delta_from_legacy = EXCLUDED.delta_from_legacy,
  accepted_delta_budget = EXCLUDED.accepted_delta_budget,
  projection_watermark = EXCLUDED.projection_watermark,
  occurred_at = EXCLUDED.occurred_at
RETURNING id,
          event_type,
          rating_engine,
          engine_version,
          policy_version,
          sport_key,
          mode_key,
          user_id,
          source_result_id,
          mu,
          sigma,
          delta_mu,
          delta_sigma,
          legacy_mu,
          legacy_sigma,
          openskill_mu,
          openskill_sigma,
          delta_from_legacy,
          accepted_delta_budget,
          comparison_scenario,
          projection_watermark,
          occurred_at,
          created_at
`

type UpsertCompetitionOpenSkillComputedEventParams struct {
	RatingEngine        string
	EngineVersion       string
	PolicyVersion       string
	SportKey            string
	ModeKey             *string
	UserID              pgtype.UUID
	SourceResultID      pgtype.UUID
	LegacyMu            pgtype.Numeric
	LegacySigma         pgtype.Numeric
	OpenskillMu         pgtype.Numeric
	OpenskillSigma      pgtype.Numeric
	DeltaFromLegacy     pgtype.Numeric
	AcceptedDeltaBudget pgtype.Numeric
	ComparisonScenario  *string
	ProjectionWatermark string
	OccurredAt          pgtype.Timestamptz
}

type UpsertCompetitionOpenSkillComputedEventRow struct {
	ID                  uuid.UUID
	EventType           string
	RatingEngine        string
	EngineVersion       string
	PolicyVersion       string
	SportKey            string
	ModeKey             *string
	UserID              pgtype.UUID
	SourceResultID      pgtype.UUID
	Mu                  pgtype.Numeric
	Sigma               pgtype.Numeric
	DeltaMu             pgtype.Numeric
	DeltaSigma          pgtype.Numeric
	LegacyMu            pgtype.Numeric
	LegacySigma         pgtype.Numeric
	OpenskillMu         pgtype.Numeric
	OpenskillSigma      pgtype.Numeric
	DeltaFromLegacy     pgtype.Numeric
	AcceptedDeltaBudget pgtype.Numeric
	ComparisonScenario  *string
	ProjectionWatermark string
	OccurredAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionOpenSkillComputedEvent(ctx context.Context, arg UpsertCompetitionOpenSkillComputedEventParams) (UpsertCompetitionOpenSkillComputedEventRow, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionOpenSkillComputedEvent,
		arg.RatingEngine,
		arg.EngineVersion,
		arg.PolicyVersion,
		arg.SportKey,
		arg.ModeKey,
		arg.UserID,
		arg.SourceResultID,
		arg.LegacyMu,
		arg.LegacySigma,
		arg.OpenskillMu,
		arg.OpenskillSigma,
		arg.DeltaFromLegacy,
		arg.AcceptedDeltaBudget,
		arg.ComparisonScenario,
		arg.ProjectionWatermark,
		arg.OccurredAt,
	)
	var i UpsertCompetitionOpenSkillComputedEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RatingEngine,
		&i.EngineVersion,
		&i.PolicyVersion,
		&i.SportKey,
		&i.ModeKey,
		&i.UserID,
		&i.SourceResultID,
		&i.Mu,
		&i.Sigma,
		&i.DeltaMu,
		&i.DeltaSigma,
		&i.LegacyMu,
		&i.LegacySigma,
		&i.OpenskillMu,
		&i.OpenskillSigma,
		&i.DeltaFromLegacy,
		&i.AcceptedDeltaBudget,
		&i.ComparisonScenario,
		&i.ProjectionWatermark,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCompetitionRatingComparison = `-- name: UpsertCompetitionRatingComparison :one
INSERT INTO apollo.competition_rating_comparisons (
  sport_key,
  mode_key,
  user_id,
  source_result_id,
  legacy_rating_engine,
  legacy_engine_version,
  legacy_policy_version,
  openskill_rating_engine,
  openskill_engine_version,
  openskill_policy_version,
  legacy_mu,
  legacy_sigma,
  openskill_mu,
  openskill_sigma,
  delta_from_legacy,
  accepted_delta_budget,
  comparison_scenario,
  delta_flagged,
  projection_watermark,
  occurred_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21
)
ON CONFLICT (
  openskill_rating_engine,
  openskill_engine_version,
  openskill_policy_version,
  sport_key,
  mode_key,
  source_result_id,
  user_id,
  comparison_scenario
)
DO UPDATE SET
  legacy_rating_engine = EXCLUDED.legacy_rating_engine,
  legacy_engine_version = EXCLUDED.legacy_engine_version,
  legacy_policy_version = EXCLUDED.legacy_policy_version,
  legacy_mu = EXCLUDED.legacy_mu,
  legacy_sigma = EXCLUDED.legacy_sigma,
  openskill_mu = EXCLUDED.openskill_mu,
  openskill_sigma = EXCLUDED.openskill_sigma,
  delta_from_legacy = EXCLUDED.delta_from_legacy,
  accepted_delta_budget = EXCLUDED.accepted_delta_budget,
  delta_flagged = EXCLUDED.delta_flagged,
  projection_watermark = EXCLUDED.projection_watermark,
  occurred_at = EXCLUDED.occurred_at,
  updated_at = EXCLUDED.updated_at
RETURNING id,
          sport_key,
          mode_key,
          user_id,
          source_result_id,
          legacy_rating_engine,
          legacy_engine_version,
          legacy_policy_version,
          openskill_rating_engine,
          openskill_engine_version,
          openskill_policy_version,
          legacy_mu,
          legacy_sigma,
          openskill_mu,
          openskill_sigma,
          delta_from_legacy,
          accepted_delta_budget,
          comparison_scenario,
          delta_flagged,
          projection_watermark,
          occurred_at,
          created_at,
          updated_at
`

type UpsertCompetitionRatingComparisonParams struct {
	SportKey               string
	ModeKey                string
	UserID                 uuid.UUID
	SourceResultID         uuid.UUID
	LegacyRatingEngine     string
	LegacyEngineVersion    string
	LegacyPolicyVersion    string
	OpenskillRatingEngine  string
	OpenskillEngineVersion string
	OpenskillPolicyVersion string
	LegacyMu               pgtype.Numeric
	LegacySigma            pgtype.Numeric
	OpenskillMu            pgtype.Numeric
	OpenskillSigma         pgtype.Numeric
	DeltaFromLegacy        pgtype.Numeric
	AcceptedDeltaBudget    pgtype.Numeric
	ComparisonScenario     string
	DeltaFlagged           bool
	ProjectionWatermark    string
	OccurredAt             pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionRatingComparison(ctx context.Context, arg UpsertCompetitionRatingComparisonParams) (ApolloCompetitionRatingComparison, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionRatingComparison,
		arg.SportKey,
		arg.ModeKey,
		arg.UserID,
		arg.SourceResultID,
		arg.LegacyRatingEngine,
		arg.LegacyEngineVersion,
		arg.LegacyPolicyVersion,
		arg.OpenskillRatingEngine,
		arg.OpenskillEngineVersion,
		arg.OpenskillPolicyVersion,
		arg.LegacyMu,
		arg.LegacySigma,
		arg.OpenskillMu,
		arg.OpenskillSigma,
		arg.DeltaFromLegacy,
		arg.AcceptedDeltaBudget,
		arg.ComparisonScenario,
		arg.DeltaFlagged,
		arg.ProjectionWatermark,
		arg.OccurredAt,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionRatingComparison
	err := row.Scan(
		&i.ID,
		&i.SportKey,
		&i.ModeKey,
		&i.UserID,
		&i.SourceResultID,
		&i.LegacyRatingEngine,
		&i.LegacyEngineVersion,
		&i.LegacyPolicyVersion,
		&i.OpenskillRatingEngine,
		&i.OpenskillEngineVersion,
		&i.OpenskillPolicyVersion,
		&i.LegacyMu,
		&i.LegacySigma,
		&i.OpenskillMu,
		&i.OpenskillSigma,
		&i.DeltaFromLegacy,
		&i.AcceptedDeltaBudget,
		&i.ComparisonScenario,
		&i.DeltaFlagged,
		&i.ProjectionWatermark,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompetitionRatingDeltaFlaggedEvent = `-- name: UpsertCompetitionRatingDeltaFlaggedEvent :one
INSERT INTO apollo.competition_rating_events (
  event_type,
  rating_engine,
  engine_version,
  policy_version,
  sport_key,
  mode_key,
  user_id,
  source_result_id,
  legacy_mu,
  legacy_sigma,
  openskill_mu,
  openskill_sigma,
  delta_from_legacy,
  accepted_delta_budget,
  comparison_scenario,
  projection_watermark,
  occurred_at
)
VALUES (
  'competition.rating.delta_flagged',
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
)
ON CONFLICT (
  rating_engine,
  engine_version,
  policy_version,
  sport_key,
  mode_key,
  source_result_id,
  user_id,
  comparison_scenario
)
WHERE event_type = 'competition.rating.delta_flagged'
DO UPDATE SET
  legacy_mu = EXCLUDED.legacy_mu,
  legacy_sigma = EXCLUDED.legacy_sigma,
  openskill_mu = EXCLUDED.openskill_mu,
  openskill_sigma = EXCLUDED.openskill_sigma,
  delta_from_legacy = EXCLUDED.delta_from_legacy,
  accepted_delta_budget = EXCLUDED.accepted_delta_budget,
  projection_watermark = EXCLUDED.projection_watermark,
  occurred_at = EXCLUDED.occurred_at
RETURNING id,
          event_type,
          rating_engine,
          engine_version,
          policy_version,
          sport_key,
          mode_key,
          user_id,
          source_result_id,
          mu,
          sigma,
          delta_mu,
          delta_sigma,
          legacy_mu,
          legacy_sigma,
          openskill_mu,
          openskill_sigma,
          delta_from_legacy,
          accepted_delta_budget,
          comparison_scenario,
          projection_watermark,
          occurred_at,
          created_at
`

type UpsertCompetitionRatingDeltaFlaggedEventParams struct {
	RatingEngine        string
	EngineVersion       string
	PolicyVersion       string
	SportKey            string
	ModeKey             *string
	UserID              pgtype.UUID
	SourceResultID      pgtype.UUID
	LegacyMu            pgtype.Numeric
	LegacySigma         pgtype.Numeric
	OpenskillMu         pgtype.Numeric
	OpenskillSigma      pgtype.Numeric
	DeltaFromLegacy     pgtype.Numeric
	AcceptedDeltaBudget pgtype.Numeric
	ComparisonScenario  *string
	ProjectionWatermark string
	OccurredAt          pgtype.Timestamptz
}

type UpsertCompetitionRatingDeltaFlaggedEventRow struct {
	ID                  uuid.UUID
	EventType           string
	RatingEngine        string
	EngineVersion       string
	PolicyVersion       string
	SportKey            string
	ModeKey             *string
	UserID              pgtype.UUID
	SourceResultID      pgtype.UUID
	Mu                  pgtype.Numeric
	Sigma               pgtype.Numeric
	DeltaMu             pgtype.Numeric
	DeltaSigma          pgtype.Numeric
	LegacyMu            pgtype.Numeric
	LegacySigma         pgtype.Numeric
	OpenskillMu         pgtype.Numeric
	OpenskillSigma      pgtype.Numeric
	DeltaFromLegacy     pgtype.Numeric
	AcceptedDeltaBudget pgtype.Numeric
	ComparisonScenario  *string
	ProjectionWatermark string
	OccurredAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UpsertCompetitionRatingDeltaFlaggedEvent(ctx context.Context, arg UpsertCompetitionRatingDeltaFlaggedEventParams) (UpsertCompetitionRatingDeltaFlaggedEventRow, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionRatingDeltaFlaggedEvent,
		arg.RatingEngine,
		arg.EngineVersion,
		arg.PolicyVersion,
		arg.SportKey,
		arg.ModeKey,
		arg.UserID,
		arg.SourceResultID,
		arg.LegacyMu,
		arg.LegacySigma,
		arg.OpenskillMu,
		arg.OpenskillSigma,
		arg.DeltaFromLegacy,
		arg.AcceptedDeltaBudget,
		arg.ComparisonScenario,
		arg.ProjectionWatermark,
		arg.OccurredAt,
	)
	var i UpsertCompetitionRatingDeltaFlaggedEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RatingEngine,
		&i.EngineVersion,
		&i.PolicyVersion,
		&i.SportKey,
		&i.ModeKey,
		&i.UserID,
		&i.SourceResultID,
		&i.Mu,
		&i.Sigma,
		&i.DeltaMu,
		&i.DeltaSigma,
		&i.LegacyMu,
		&i.LegacySigma,
		&i.OpenskillMu,
		&i.OpenskillSigma,
		&i.DeltaFromLegacy,
		&i.AcceptedDeltaBudget,
		&i.ComparisonScenario,
		&i.ProjectionWatermark,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}
