// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition_safety.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompetitionReliabilityEvent = `-- name: CreateCompetitionReliabilityEvent :one
INSERT INTO apollo.competition_reliability_events (
  competition_session_id,
  competition_match_id,
  subject_user_id,
  reliability_type,
  severity,
  note,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id,
          competition_session_id,
          competition_match_id,
          subject_user_id,
          reliability_type,
          severity,
          privacy_scope,
          note,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          occurred_at,
          created_at
`

type CreateCompetitionReliabilityEventParams struct {
	CompetitionSessionID uuid.UUID
	CompetitionMatchID   pgtype.UUID
	SubjectUserID        pgtype.UUID
	ReliabilityType      string
	Severity             string
	Note                 *string
	ActorUserID          uuid.UUID
	ActorRole            string
	ActorSessionID       uuid.UUID
	Capability           string
	TrustedSurfaceKey    string
	TrustedSurfaceLabel  *string
	OccurredAt           pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionReliabilityEvent(ctx context.Context, arg CreateCompetitionReliabilityEventParams) (ApolloCompetitionReliabilityEvent, error) {
	row := q.db.QueryRow(ctx, createCompetitionReliabilityEvent,
		arg.CompetitionSessionID,
		arg.CompetitionMatchID,
		arg.SubjectUserID,
		arg.ReliabilityType,
		arg.Severity,
		arg.Note,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.OccurredAt,
	)
	var i ApolloCompetitionReliabilityEvent
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.CompetitionMatchID,
		&i.SubjectUserID,
		&i.ReliabilityType,
		&i.Severity,
		&i.PrivacyScope,
		&i.Note,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionSafetyBlock = `-- name: CreateCompetitionSafetyBlock :one
INSERT INTO apollo.competition_safety_blocks (
  competition_session_id,
  competition_match_id,
  blocker_user_id,
  blocked_user_id,
  reason_code,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id,
          competition_session_id,
          competition_match_id,
          blocker_user_id,
          blocked_user_id,
          reason_code,
          status,
          privacy_scope,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          occurred_at,
          created_at
`

type CreateCompetitionSafetyBlockParams struct {
	CompetitionSessionID uuid.UUID
	CompetitionMatchID   pgtype.UUID
	BlockerUserID        uuid.UUID
	BlockedUserID        uuid.UUID
	ReasonCode           string
	ActorUserID          uuid.UUID
	ActorRole            string
	ActorSessionID       uuid.UUID
	Capability           string
	TrustedSurfaceKey    string
	TrustedSurfaceLabel  *string
	OccurredAt           pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionSafetyBlock(ctx context.Context, arg CreateCompetitionSafetyBlockParams) (ApolloCompetitionSafetyBlock, error) {
	row := q.db.QueryRow(ctx, createCompetitionSafetyBlock,
		arg.CompetitionSessionID,
		arg.CompetitionMatchID,
		arg.BlockerUserID,
		arg.BlockedUserID,
		arg.ReasonCode,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.OccurredAt,
	)
	var i ApolloCompetitionSafetyBlock
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.CompetitionMatchID,
		&i.BlockerUserID,
		&i.BlockedUserID,
		&i.ReasonCode,
		&i.Status,
		&i.PrivacyScope,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionSafetyEvent = `-- name: CreateCompetitionSafetyEvent :one
INSERT INTO apollo.competition_safety_events (
  event_type,
  competition_session_id,
  competition_match_id,
  competition_session_team_id,
  competition_tournament_id,
  safety_report_id,
  safety_block_id,
  reliability_event_id,
  reporter_user_id,
  subject_user_id,
  blocker_user_id,
  blocked_user_id,
  target_type,
  target_id,
  reason_code,
  reliability_type,
  severity,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)
RETURNING id,
          event_type,
          competition_session_id,
          competition_match_id,
          competition_session_team_id,
          competition_tournament_id,
          safety_report_id,
          safety_block_id,
          reliability_event_id,
          reporter_user_id,
          subject_user_id,
          blocker_user_id,
          blocked_user_id,
          target_type,
          target_id,
          reason_code,
          reliability_type,
          severity,
          privacy_scope,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          occurred_at,
          created_at
`

type CreateCompetitionSafetyEventParams struct {
	EventType                string
	CompetitionSessionID     pgtype.UUID
	CompetitionMatchID       pgtype.UUID
	CompetitionSessionTeamID pgtype.UUID
	CompetitionTournamentID  pgtype.UUID
	SafetyReportID           pgtype.UUID
	SafetyBlockID            pgtype.UUID
	ReliabilityEventID       pgtype.UUID
	ReporterUserID           pgtype.UUID
	SubjectUserID            pgtype.UUID
	BlockerUserID            pgtype.UUID
	BlockedUserID            pgtype.UUID
	TargetType               *string
	TargetID                 pgtype.UUID
	ReasonCode               *string
	ReliabilityType          *string
	Severity                 *string
	ActorUserID              uuid.UUID
	ActorRole                string
	ActorSessionID           uuid.UUID
	Capability               string
	TrustedSurfaceKey        string
	TrustedSurfaceLabel      *string
	OccurredAt               pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionSafetyEvent(ctx context.Context, arg CreateCompetitionSafetyEventParams) (ApolloCompetitionSafetyEvent, error) {
	row := q.db.QueryRow(ctx, createCompetitionSafetyEvent,
		arg.EventType,
		arg.CompetitionSessionID,
		arg.CompetitionMatchID,
		arg.CompetitionSessionTeamID,
		arg.CompetitionTournamentID,
		arg.SafetyReportID,
		arg.SafetyBlockID,
		arg.ReliabilityEventID,
		arg.ReporterUserID,
		arg.SubjectUserID,
		arg.BlockerUserID,
		arg.BlockedUserID,
		arg.TargetType,
		arg.TargetID,
		arg.ReasonCode,
		arg.ReliabilityType,
		arg.Severity,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.OccurredAt,
	)
	var i ApolloCompetitionSafetyEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.CompetitionSessionID,
		&i.CompetitionMatchID,
		&i.CompetitionSessionTeamID,
		&i.CompetitionTournamentID,
		&i.SafetyReportID,
		&i.SafetyBlockID,
		&i.ReliabilityEventID,
		&i.ReporterUserID,
		&i.SubjectUserID,
		&i.BlockerUserID,
		&i.BlockedUserID,
		&i.TargetType,
		&i.TargetID,
		&i.ReasonCode,
		&i.ReliabilityType,
		&i.Severity,
		&i.PrivacyScope,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionSafetyReport = `-- name: CreateCompetitionSafetyReport :one
INSERT INTO apollo.competition_safety_reports (
  competition_session_id,
  competition_match_id,
  competition_session_team_id,
  competition_tournament_id,
  reporter_user_id,
  subject_user_id,
  target_type,
  target_id,
  reason_code,
  note,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id,
          competition_session_id,
          competition_match_id,
          competition_session_team_id,
          competition_tournament_id,
          reporter_user_id,
          subject_user_id,
          target_type,
          target_id,
          reason_code,
          status,
          privacy_scope,
          note,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          occurred_at,
          created_at
`

type CreateCompetitionSafetyReportParams struct {
	CompetitionSessionID     pgtype.UUID
	CompetitionMatchID       pgtype.UUID
	CompetitionSessionTeamID pgtype.UUID
	CompetitionTournamentID  pgtype.UUID
	ReporterUserID           uuid.UUID
	SubjectUserID            pgtype.UUID
	TargetType               string
	TargetID                 uuid.UUID
	ReasonCode               string
	Note                     *string
	ActorUserID              uuid.UUID
	ActorRole                string
	ActorSessionID           uuid.UUID
	Capability               string
	TrustedSurfaceKey        string
	TrustedSurfaceLabel      *string
	OccurredAt               pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionSafetyReport(ctx context.Context, arg CreateCompetitionSafetyReportParams) (ApolloCompetitionSafetyReport, error) {
	row := q.db.QueryRow(ctx, createCompetitionSafetyReport,
		arg.CompetitionSessionID,
		arg.CompetitionMatchID,
		arg.CompetitionSessionTeamID,
		arg.CompetitionTournamentID,
		arg.ReporterUserID,
		arg.SubjectUserID,
		arg.TargetType,
		arg.TargetID,
		arg.ReasonCode,
		arg.Note,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.OccurredAt,
	)
	var i ApolloCompetitionSafetyReport
	err := row.Scan(
		&i.ID,
		&i.CompetitionSessionID,
		&i.CompetitionMatchID,
		&i.CompetitionSessionTeamID,
		&i.CompetitionTournamentID,
		&i.ReporterUserID,
		&i.SubjectUserID,
		&i.TargetType,
		&i.TargetID,
		&i.ReasonCode,
		&i.Status,
		&i.PrivacyScope,
		&i.Note,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCompetitionSafetyReviewSummary = `-- name: GetCompetitionSafetyReviewSummary :one
SELECT
  (SELECT count(*) FROM apollo.competition_safety_reports) AS report_count,
  (SELECT count(*) FROM apollo.competition_safety_blocks WHERE status = 'active') AS block_count,
  (SELECT count(*) FROM apollo.competition_reliability_events) AS reliability_event_count,
  (SELECT count(*) FROM apollo.competition_safety_events) AS audit_event_count
`

type GetCompetitionSafetyReviewSummaryRow struct {
	ReportCount           int64
	BlockCount            int64
	ReliabilityEventCount int64
	AuditEventCount       int64
}

func (q *Queries) GetCompetitionSafetyReviewSummary(ctx context.Context) (GetCompetitionSafetyReviewSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCompetitionSafetyReviewSummary)
	var i GetCompetitionSafetyReviewSummaryRow
	err := row.Scan(
		&i.ReportCount,
		&i.BlockCount,
		&i.ReliabilityEventCount,
		&i.AuditEventCount,
	)
	return i, err
}

const listCompetitionReliabilityEventsForReview = `-- name: ListCompetitionReliabilityEventsForReview :many
SELECT id,
       competition_session_id,
       competition_match_id,
       subject_user_id,
       reliability_type,
       severity,
       privacy_scope,
       note,
       actor_user_id,
       actor_role,
       actor_session_id,
       capability,
       trusted_surface_key,
       trusted_surface_label,
       occurred_at,
       created_at
FROM apollo.competition_reliability_events
ORDER BY occurred_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListCompetitionReliabilityEventsForReview(ctx context.Context, limit int32) ([]ApolloCompetitionReliabilityEvent, error) {
	rows, err := q.db.Query(ctx, listCompetitionReliabilityEventsForReview, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionReliabilityEvent
	for rows.Next() {
		var i ApolloCompetitionReliabilityEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionSessionID,
			&i.CompetitionMatchID,
			&i.SubjectUserID,
			&i.ReliabilityType,
			&i.Severity,
			&i.PrivacyScope,
			&i.Note,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorSessionID,
			&i.Capability,
			&i.TrustedSurfaceKey,
			&i.TrustedSurfaceLabel,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSafetyAuditEventsForReview = `-- name: ListCompetitionSafetyAuditEventsForReview :many
SELECT id,
       event_type,
       competition_session_id,
       competition_match_id,
       competition_session_team_id,
       competition_tournament_id,
       safety_report_id,
       safety_block_id,
       reliability_event_id,
       reporter_user_id,
       subject_user_id,
       blocker_user_id,
       blocked_user_id,
       target_type,
       target_id,
       reason_code,
       reliability_type,
       severity,
       privacy_scope,
       actor_user_id,
       actor_role,
       actor_session_id,
       capability,
       trusted_surface_key,
       trusted_surface_label,
       occurred_at,
       created_at
FROM apollo.competition_safety_events
ORDER BY occurred_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListCompetitionSafetyAuditEventsForReview(ctx context.Context, limit int32) ([]ApolloCompetitionSafetyEvent, error) {
	rows, err := q.db.Query(ctx, listCompetitionSafetyAuditEventsForReview, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionSafetyEvent
	for rows.Next() {
		var i ApolloCompetitionSafetyEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.CompetitionSessionID,
			&i.CompetitionMatchID,
			&i.CompetitionSessionTeamID,
			&i.CompetitionTournamentID,
			&i.SafetyReportID,
			&i.SafetyBlockID,
			&i.ReliabilityEventID,
			&i.ReporterUserID,
			&i.SubjectUserID,
			&i.BlockerUserID,
			&i.BlockedUserID,
			&i.TargetType,
			&i.TargetID,
			&i.ReasonCode,
			&i.ReliabilityType,
			&i.Severity,
			&i.PrivacyScope,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorSessionID,
			&i.Capability,
			&i.TrustedSurfaceKey,
			&i.TrustedSurfaceLabel,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSafetyBlocksForReview = `-- name: ListCompetitionSafetyBlocksForReview :many
SELECT id,
       competition_session_id,
       competition_match_id,
       blocker_user_id,
       blocked_user_id,
       reason_code,
       status,
       privacy_scope,
       actor_user_id,
       actor_role,
       actor_session_id,
       capability,
       trusted_surface_key,
       trusted_surface_label,
       occurred_at,
       created_at
FROM apollo.competition_safety_blocks
ORDER BY occurred_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListCompetitionSafetyBlocksForReview(ctx context.Context, limit int32) ([]ApolloCompetitionSafetyBlock, error) {
	rows, err := q.db.Query(ctx, listCompetitionSafetyBlocksForReview, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionSafetyBlock
	for rows.Next() {
		var i ApolloCompetitionSafetyBlock
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionSessionID,
			&i.CompetitionMatchID,
			&i.BlockerUserID,
			&i.BlockedUserID,
			&i.ReasonCode,
			&i.Status,
			&i.PrivacyScope,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorSessionID,
			&i.Capability,
			&i.TrustedSurfaceKey,
			&i.TrustedSurfaceLabel,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionSafetyReportsForReview = `-- name: ListCompetitionSafetyReportsForReview :many
SELECT id,
       competition_session_id,
       competition_match_id,
       competition_session_team_id,
       competition_tournament_id,
       reporter_user_id,
       subject_user_id,
       target_type,
       target_id,
       reason_code,
       status,
       privacy_scope,
       note,
       actor_user_id,
       actor_role,
       actor_session_id,
       capability,
       trusted_surface_key,
       trusted_surface_label,
       occurred_at,
       created_at
FROM apollo.competition_safety_reports
ORDER BY occurred_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListCompetitionSafetyReportsForReview(ctx context.Context, limit int32) ([]ApolloCompetitionSafetyReport, error) {
	rows, err := q.db.Query(ctx, listCompetitionSafetyReportsForReview, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionSafetyReport
	for rows.Next() {
		var i ApolloCompetitionSafetyReport
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionSessionID,
			&i.CompetitionMatchID,
			&i.CompetitionSessionTeamID,
			&i.CompetitionTournamentID,
			&i.ReporterUserID,
			&i.SubjectUserID,
			&i.TargetType,
			&i.TargetID,
			&i.ReasonCode,
			&i.Status,
			&i.PrivacyScope,
			&i.Note,
			&i.ActorUserID,
			&i.ActorRole,
			&i.ActorSessionID,
			&i.Capability,
			&i.TrustedSurfaceKey,
			&i.TrustedSurfaceLabel,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
