// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: membership.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLobbyMembershipByUserID = `-- name: GetLobbyMembershipByUserID :one
SELECT user_id, status, joined_at, left_at, created_at, updated_at
FROM apollo.lobby_memberships
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetLobbyMembershipByUserID(ctx context.Context, userID uuid.UUID) (ApolloLobbyMembership, error) {
	row := q.db.QueryRow(ctx, getLobbyMembershipByUserID, userID)
	var i ApolloLobbyMembership
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaveLobbyMembership = `-- name: LeaveLobbyMembership :one
UPDATE apollo.lobby_memberships
SET status = 'not_joined',
    left_at = $2,
    updated_at = $2
WHERE user_id = $1
  AND status = 'joined'
RETURNING user_id, status, joined_at, left_at, created_at, updated_at
`

type LeaveLobbyMembershipParams struct {
	UserID uuid.UUID
	LeftAt pgtype.Timestamptz
}

func (q *Queries) LeaveLobbyMembership(ctx context.Context, arg LeaveLobbyMembershipParams) (ApolloLobbyMembership, error) {
	row := q.db.QueryRow(ctx, leaveLobbyMembership, arg.UserID, arg.LeftAt)
	var i ApolloLobbyMembership
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLobbyMembershipJoin = `-- name: UpsertLobbyMembershipJoin :one
INSERT INTO apollo.lobby_memberships (
  user_id,
  status,
  joined_at,
  left_at,
  updated_at
)
VALUES ($1, 'joined', $2, NULL, $2)
ON CONFLICT (user_id) DO UPDATE
SET status = 'joined',
    joined_at = EXCLUDED.joined_at,
    left_at = NULL,
    updated_at = EXCLUDED.updated_at
WHERE apollo.lobby_memberships.status <> 'joined'
RETURNING user_id, status, joined_at, left_at, created_at, updated_at
`

type UpsertLobbyMembershipJoinParams struct {
	UserID   uuid.UUID
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) UpsertLobbyMembershipJoin(ctx context.Context, arg UpsertLobbyMembershipJoinParams) (ApolloLobbyMembership, error) {
	row := q.db.QueryRow(ctx, upsertLobbyMembershipJoin, arg.UserID, arg.JoinedAt)
	var i ApolloLobbyMembership
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
