// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApolloAresMatch struct {
	ID        uuid.UUID
	Activity  string
	MatchType string
	PlayedAt  pgtype.Timestamptz
	Metadata  []byte
}

type ApolloAresMatchPlayer struct {
	MatchID     uuid.UUID
	UserID      uuid.UUID
	Team        *int32
	Outcome     string
	MuBefore    pgtype.Numeric
	MuAfter     pgtype.Numeric
	SigmaBefore pgtype.Numeric
	SigmaAfter  pgtype.Numeric
}

type ApolloAresRating struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Activity    string
	Mu          pgtype.Numeric
	Sigma       pgtype.Numeric
	GamesPlayed int32
	LastPlayed  pgtype.Timestamptz
}

type ApolloClaimedTag struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TagHash   string
	Label     *string
	IsActive  bool
	ClaimedAt pgtype.Timestamptz
}

type ApolloCompetitionMatch struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

type ApolloCompetitionMatchResult struct {
	CompetitionMatchID uuid.UUID
	RecordedByUserID   uuid.UUID
	RecordedAt         pgtype.Timestamptz
}

type ApolloCompetitionMatchResultSide struct {
	CompetitionMatchID       uuid.UUID
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
}

type ApolloCompetitionMatchSideSlot struct {
	CompetitionMatchID       uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	SideIndex                int32
	CreatedAt                pgtype.Timestamptz
}

type ApolloCompetitionMemberRating struct {
	UserID        uuid.UUID
	SportKey      string
	ModeKey       string
	Mu            pgtype.Numeric
	Sigma         pgtype.Numeric
	MatchesPlayed int32
	LastPlayed    pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ApolloCompetitionSession struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
	QueueVersion        int32
}

type ApolloCompetitionSessionQueueMember struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
	JoinedAt             pgtype.Timestamptz
}

type ApolloCompetitionSessionTeam struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	SideIndex            int32
	CreatedAt            pgtype.Timestamptz
}

type ApolloCompetitionTeamRosterMember struct {
	CompetitionSessionID     uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
	SlotIndex                int32
	CreatedAt                pgtype.Timestamptz
}

type ApolloEmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ApolloEquipmentDefinition struct {
	ID           uuid.UUID
	EquipmentKey string
	DisplayName  string
	IsMachine    bool
}

type ApolloExercise struct {
	ID        uuid.UUID
	WorkoutID uuid.UUID
	Name      string
	Sets      int32
	Reps      int32
	WeightKg  pgtype.Numeric
	Rpe       pgtype.Numeric
	Notes     *string
	Position  int32
}

type ApolloExerciseDefinition struct {
	ID          uuid.UUID
	ExerciseKey string
	DisplayName string
}

type ApolloExerciseDefinitionEquipment struct {
	ExerciseDefinitionID  uuid.UUID
	EquipmentDefinitionID uuid.UUID
}

type ApolloFacilityCatalogRef struct {
	FacilityKey string
}

type ApolloFacilityZoneRef struct {
	FacilityKey string
	ZoneKey     string
}

type ApolloLobbyMembership struct {
	UserID    uuid.UUID
	Status    string
	JoinedAt  pgtype.Timestamptz
	LeftAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApolloPlannerSession struct {
	ID                uuid.UUID
	PlannerWeekID     uuid.UUID
	DayIndex          int32
	Position          int32
	WorkoutTemplateID pgtype.UUID
}

type ApolloPlannerSessionItem struct {
	ID                    uuid.UUID
	PlannerSessionID      uuid.UUID
	Position              int32
	ExerciseDefinitionID  uuid.UUID
	EquipmentDefinitionID pgtype.UUID
	Sets                  int32
	Reps                  int32
	WeightKg              pgtype.Numeric
	Rpe                   pgtype.Numeric
	Notes                 *string
}

type ApolloPlannerWeek struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	WeekStart pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApolloRecommendation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Content    []byte
	ModelUsed  string
	LatencyMs  *int32
	Feedback   *string
	CreatedAt  pgtype.Timestamptz
	FeedbackAt pgtype.Timestamptz
}

type ApolloSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ApolloSport struct {
	SportKey                    string
	DisplayName                 string
	Description                 string
	CompetitionMode             string
	SidesPerMatch               int32
	ParticipantsPerSideMin      int32
	ParticipantsPerSideMax      int32
	ScoringModel                string
	DefaultMatchDurationMinutes int32
	RulesSummary                string
}

type ApolloSportFacilityCapability struct {
	SportKey    string
	FacilityKey string
}

type ApolloSportFacilityCapabilityZone struct {
	SportKey    string
	FacilityKey string
	ZoneKey     string
}

type ApolloUser struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ApolloVisit struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	FacilityKey            string
	ZoneKey                *string
	SourceEventID          *string
	ArrivedAt              pgtype.Timestamptz
	DepartedAt             pgtype.Timestamptz
	Metadata               []byte
	DepartureSourceEventID *string
}

type ApolloWorkout struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	StartedAt  pgtype.Timestamptz
	Notes      *string
	Metadata   []byte
	Status     string
	FinishedAt pgtype.Timestamptz
}

type ApolloWorkoutEffortFeedback struct {
	WorkoutID   uuid.UUID
	UserID      uuid.UUID
	EffortLevel string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ApolloWorkoutRecoveryFeedback struct {
	WorkoutID     uuid.UUID
	UserID        uuid.UUID
	RecoveryLevel string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ApolloWorkoutTemplate struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApolloWorkoutTemplateItem struct {
	ID                    uuid.UUID
	WorkoutTemplateID     uuid.UUID
	Position              int32
	ExerciseDefinitionID  uuid.UUID
	EquipmentDefinitionID pgtype.UUID
	Sets                  int32
	Reps                  int32
	WeightKg              pgtype.Numeric
	Rpe                   pgtype.Numeric
	Notes                 *string
}
