// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApolloAresMatch struct {
	ID        uuid.UUID
	Activity  string
	MatchType string
	PlayedAt  pgtype.Timestamptz
	Metadata  []byte
}

type ApolloAresMatchPlayer struct {
	MatchID     uuid.UUID
	UserID      uuid.UUID
	Team        *int32
	Outcome     string
	MuBefore    pgtype.Numeric
	MuAfter     pgtype.Numeric
	SigmaBefore pgtype.Numeric
	SigmaAfter  pgtype.Numeric
}

type ApolloAresRating struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Activity    string
	Mu          pgtype.Numeric
	Sigma       pgtype.Numeric
	GamesPlayed int32
	LastPlayed  pgtype.Timestamptz
}

type ApolloClaimedTag struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TagHash   string
	Label     *string
	IsActive  bool
	ClaimedAt pgtype.Timestamptz
}

type ApolloEmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ApolloExercise struct {
	ID        uuid.UUID
	WorkoutID uuid.UUID
	Name      string
	Sets      int32
	Reps      int32
	WeightKg  pgtype.Numeric
	Rpe       pgtype.Numeric
	Notes     *string
	Position  int32
}

type ApolloLobbyMembership struct {
	UserID    uuid.UUID
	Status    string
	JoinedAt  pgtype.Timestamptz
	LeftAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApolloRecommendation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Content    []byte
	ModelUsed  string
	LatencyMs  *int32
	Feedback   *string
	CreatedAt  pgtype.Timestamptz
	FeedbackAt pgtype.Timestamptz
}

type ApolloSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ApolloUser struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

type ApolloVisit struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	FacilityKey            string
	ZoneKey                *string
	SourceEventID          *string
	ArrivedAt              pgtype.Timestamptz
	DepartedAt             pgtype.Timestamptz
	Metadata               []byte
	DepartureSourceEventID *string
}

type ApolloWorkout struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	StartedAt  pgtype.Timestamptz
	Notes      *string
	Metadata   []byte
	Status     string
	FinishedAt pgtype.Timestamptz
}
