// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApolloAresMatch struct {
	ID        uuid.UUID
	Activity  string
	MatchType string
	PlayedAt  pgtype.Timestamptz
	Metadata  []byte
}

type ApolloAresMatchPlayer struct {
	MatchID     uuid.UUID
	UserID      uuid.UUID
	Team        *int32
	Outcome     string
	MuBefore    pgtype.Numeric
	MuAfter     pgtype.Numeric
	SigmaBefore pgtype.Numeric
	SigmaAfter  pgtype.Numeric
}

type ApolloAresRating struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Activity    string
	Mu          pgtype.Numeric
	Sigma       pgtype.Numeric
	GamesPlayed int32
	LastPlayed  pgtype.Timestamptz
}

type ApolloBookingRequest struct {
	ID                         uuid.UUID
	FacilityKey                string
	ZoneKey                    *string
	ResourceKey                *string
	Scope                      string
	RequestedStartAt           pgtype.Timestamptz
	RequestedEndAt             pgtype.Timestamptz
	ContactName                string
	ContactEmail               *string
	ContactPhone               *string
	Organization               *string
	Purpose                    *string
	AttendeeCount              *int32
	InternalNotes              *string
	Status                     string
	Version                    int32
	ScheduleBlockID            pgtype.UUID
	CreatedByUserID            pgtype.UUID
	CreatedBySessionID         pgtype.UUID
	CreatedByRole              *string
	CreatedByCapability        *string
	CreatedTrustedSurfaceKey   *string
	CreatedTrustedSurfaceLabel *string
	UpdatedByUserID            pgtype.UUID
	UpdatedBySessionID         pgtype.UUID
	UpdatedByRole              *string
	UpdatedByCapability        *string
	UpdatedTrustedSurfaceKey   *string
	UpdatedTrustedSurfaceLabel *string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	RequestSource              string
	IntakeChannel              string
	ReplacesRequestID          pgtype.UUID
}

type ApolloBookingRequestIdempotencyKey struct {
	KeyHash          string
	PayloadHash      string
	BookingRequestID uuid.UUID
	CreatedAt        pgtype.Timestamptz
}

type ApolloClaimedTag struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TagHash   string
	Label     *string
	IsActive  bool
	ClaimedAt pgtype.Timestamptz
}

type ApolloCompetitionAnalyticsEvent struct {
	ID                  uuid.UUID
	EventType           string
	ProjectionVersion   string
	ProjectionWatermark string
	UserID              pgtype.UUID
	SportKey            string
	FacilityKey         string
	ModeKey             string
	TeamScope           string
	StatType            string
	StatValue           pgtype.Numeric
	SourceMatchID       pgtype.UUID
	SourceResultID      pgtype.UUID
	SampleSize          int32
	Confidence          pgtype.Numeric
	ComputedAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type ApolloCompetitionAnalyticsProjection struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	SportKey            string
	FacilityKey         string
	ModeKey             string
	TeamScope           string
	StatType            string
	StatValue           pgtype.Numeric
	SourceMatchID       pgtype.UUID
	SourceResultID      pgtype.UUID
	SampleSize          int32
	Confidence          pgtype.Numeric
	ComputedAt          pgtype.Timestamptz
	ProjectionVersion   string
	ProjectionWatermark string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ApolloCompetitionLifecycleEvent struct {
	ID                       uuid.UUID
	CompetitionSessionID     uuid.UUID
	CompetitionMatchID       pgtype.UUID
	CompetitionMatchResultID pgtype.UUID
	EventType                string
	ActorUserID              pgtype.UUID
	ActorRole                *string
	ActorSessionID           pgtype.UUID
	Capability               *string
	TrustedSurfaceKey        *string
	TrustedSurfaceLabel      *string
	PreviousResultStatus     *string
	ResultStatus             *string
	DisputeStatus            *string
	CorrectionID             pgtype.UUID
	SupersedesResultID       pgtype.UUID
	OccurredAt               pgtype.Timestamptz
}

type ApolloCompetitionMatch struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	MatchIndex           int32
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
	ResultVersion        int32
	CanonicalResultID    pgtype.UUID
}

type ApolloCompetitionMatchPreview struct {
	ID                      uuid.UUID
	CompetitionSessionID    uuid.UUID
	QueueVersion            int32
	ProposalIndex           int32
	PreviewVersion          string
	PolicyVersion           string
	RatingEngine            string
	RatingPolicyVersion     string
	FacilityKey             string
	SportKey                string
	ModeKey                 string
	Tier                    string
	MatchQuality            pgtype.Numeric
	PredictedWinProbability pgtype.Numeric
	ExplanationCode         string
	InputWatermark          pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type ApolloCompetitionMatchPreviewEvent struct {
	ID                        uuid.UUID
	CompetitionMatchPreviewID uuid.UUID
	CompetitionSessionID      uuid.UUID
	EventType                 string
	QueueVersion              int32
	PreviewVersion            string
	PolicyVersion             string
	RatingEngine              string
	RatingPolicyVersion       string
	FacilityKey               string
	SportKey                  string
	ModeKey                   string
	Tier                      string
	MatchQuality              pgtype.Numeric
	PredictedWinProbability   pgtype.Numeric
	ExplanationCode           string
	ActorUserID               pgtype.UUID
	ActorRole                 *string
	ActorSessionID            pgtype.UUID
	Capability                *string
	TrustedSurfaceKey         *string
	TrustedSurfaceLabel       *string
	OccurredAt                pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
}

type ApolloCompetitionMatchPreviewMember struct {
	CompetitionMatchPreviewID uuid.UUID
	SideIndex                 int32
	SlotIndex                 int32
	CompetitionQueueIntentID  uuid.UUID
	UserID                    uuid.UUID
	RatingMu                  pgtype.Numeric
	RatingSigma               pgtype.Numeric
	RatingMatchesPlayed       int32
	RatingSource              string
	Tier                      string
}

type ApolloCompetitionMatchResult struct {
	CompetitionMatchID uuid.UUID
	RecordedByUserID   uuid.UUID
	RecordedAt         pgtype.Timestamptz
	ID                 uuid.UUID
	ResultStatus       string
	DisputeStatus      string
	CorrectionID       pgtype.UUID
	SupersedesResultID pgtype.UUID
	FinalizedAt        pgtype.Timestamptz
	CorrectedAt        pgtype.Timestamptz
}

type ApolloCompetitionMatchResultSide struct {
	CompetitionMatchID       uuid.UUID
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
	CompetitionMatchResultID uuid.UUID
}

type ApolloCompetitionMatchSideSlot struct {
	CompetitionMatchID       uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	SideIndex                int32
	CreatedAt                pgtype.Timestamptz
}

type ApolloCompetitionMemberRating struct {
	UserID              uuid.UUID
	SportKey            string
	ModeKey             string
	Mu                  pgtype.Numeric
	Sigma               pgtype.Numeric
	MatchesPlayed       int32
	LastPlayed          pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RatingEngine        string
	EngineVersion       string
	PolicyVersion       string
	SourceResultID      pgtype.UUID
	RatingEventID       pgtype.UUID
	ProjectionWatermark string
}

type ApolloCompetitionQueueIntent struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
	FacilityKey          string
	SportKey             string
	ModeKey              string
	Tier                 string
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type ApolloCompetitionQueueIntentEvent struct {
	ID                       uuid.UUID
	CompetitionQueueIntentID uuid.UUID
	CompetitionSessionID     uuid.UUID
	UserID                   uuid.UUID
	EventType                string
	FacilityKey              string
	SportKey                 string
	ModeKey                  string
	Tier                     string
	Status                   string
	ActorUserID              pgtype.UUID
	ActorRole                *string
	ActorSessionID           pgtype.UUID
	Capability               *string
	TrustedSurfaceKey        *string
	TrustedSurfaceLabel      *string
	OccurredAt               pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

type ApolloCompetitionRatingComparison struct {
	ID                     uuid.UUID
	SportKey               string
	ModeKey                string
	UserID                 uuid.UUID
	SourceResultID         uuid.UUID
	LegacyRatingEngine     string
	LegacyEngineVersion    string
	LegacyPolicyVersion    string
	OpenskillRatingEngine  string
	OpenskillEngineVersion string
	OpenskillPolicyVersion string
	LegacyMu               pgtype.Numeric
	LegacySigma            pgtype.Numeric
	OpenskillMu            pgtype.Numeric
	OpenskillSigma         pgtype.Numeric
	DeltaFromLegacy        pgtype.Numeric
	AcceptedDeltaBudget    pgtype.Numeric
	ComparisonScenario     string
	DeltaFlagged           bool
	ProjectionWatermark    string
	OccurredAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ApolloCompetitionRatingEvent struct {
	ID                  uuid.UUID
	EventType           string
	RatingEngine        string
	EngineVersion       string
	PolicyVersion       string
	SportKey            string
	ModeKey             *string
	UserID              pgtype.UUID
	SourceResultID      pgtype.UUID
	Mu                  pgtype.Numeric
	Sigma               pgtype.Numeric
	DeltaMu             pgtype.Numeric
	DeltaSigma          pgtype.Numeric
	ProjectionWatermark string
	OccurredAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	LegacyMu            pgtype.Numeric
	LegacySigma         pgtype.Numeric
	OpenskillMu         pgtype.Numeric
	OpenskillSigma      pgtype.Numeric
	DeltaFromLegacy     pgtype.Numeric
	AcceptedDeltaBudget pgtype.Numeric
	ComparisonScenario  *string
}

type ApolloCompetitionSession struct {
	ID                  uuid.UUID
	OwnerUserID         uuid.UUID
	DisplayName         string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
	QueueVersion        int32
}

type ApolloCompetitionSessionQueueMember struct {
	CompetitionSessionID uuid.UUID
	UserID               uuid.UUID
	JoinedAt             pgtype.Timestamptz
}

type ApolloCompetitionSessionTeam struct {
	ID                   uuid.UUID
	CompetitionSessionID uuid.UUID
	SideIndex            int32
	CreatedAt            pgtype.Timestamptz
}

type ApolloCompetitionStaffActionAttribution struct {
	ID                       uuid.UUID
	ActorUserID              uuid.UUID
	ActorRole                string
	SessionID                uuid.UUID
	Capability               string
	TrustedSurfaceKey        string
	TrustedSurfaceLabel      *string
	Action                   string
	CompetitionSessionID     pgtype.UUID
	CompetitionSessionTeamID pgtype.UUID
	CompetitionMatchID       pgtype.UUID
	SubjectUserID            pgtype.UUID
	OccurredAt               pgtype.Timestamptz
}

type ApolloCompetitionTeamRosterMember struct {
	CompetitionSessionID     uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	UserID                   uuid.UUID
	SlotIndex                int32
	CreatedAt                pgtype.Timestamptz
}

type ApolloEmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ApolloEquipmentDefinition struct {
	ID           uuid.UUID
	EquipmentKey string
	DisplayName  string
	IsMachine    bool
}

type ApolloExercise struct {
	ID        uuid.UUID
	WorkoutID uuid.UUID
	Name      string
	Sets      int32
	Reps      int32
	WeightKg  pgtype.Numeric
	Rpe       pgtype.Numeric
	Notes     *string
	Position  int32
}

type ApolloExerciseDefinition struct {
	ID          uuid.UUID
	ExerciseKey string
	DisplayName string
}

type ApolloExerciseDefinitionEquipment struct {
	ExerciseDefinitionID  uuid.UUID
	EquipmentDefinitionID uuid.UUID
}

type ApolloFacilityCatalogRef struct {
	FacilityKey string
}

type ApolloFacilityZoneRef struct {
	FacilityKey string
	ZoneKey     string
}

type ApolloLobbyMembership struct {
	UserID    uuid.UUID
	Status    string
	JoinedAt  pgtype.Timestamptz
	LeftAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApolloMemberPresenceStreak struct {
	UserID            uuid.UUID
	FacilityKey       string
	CurrentCount      int32
	CurrentStartDay   pgtype.Date
	LastCreditedDay   pgtype.Date
	LastLinkedVisitID uuid.UUID
	UpdatedAt         pgtype.Timestamptz
}

type ApolloMemberPresenceStreakEvent struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	FacilityKey string
	EventKind   string
	CountBefore int32
	CountAfter  int32
	StreakDay   pgtype.Date
	VisitID     uuid.UUID
	CreatedAt   pgtype.Timestamptz
}

type ApolloNutritionMealLog struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	SourceTemplateID pgtype.UUID
	Name             string
	MealType         string
	LoggedAt         pgtype.Timestamptz
	Calories         *int32
	ProteinGrams     *int32
	CarbsGrams       *int32
	FatGrams         *int32
	Notes            *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ApolloNutritionMealTemplate struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	MealType     string
	Calories     *int32
	ProteinGrams *int32
	CarbsGrams   *int32
	FatGrams     *int32
	Notes        *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ApolloPlannerSession struct {
	ID                uuid.UUID
	PlannerWeekID     uuid.UUID
	DayIndex          int32
	Position          int32
	WorkoutTemplateID pgtype.UUID
}

type ApolloPlannerSessionItem struct {
	ID                    uuid.UUID
	PlannerSessionID      uuid.UUID
	Position              int32
	ExerciseDefinitionID  uuid.UUID
	EquipmentDefinitionID pgtype.UUID
	Sets                  int32
	Reps                  int32
	WeightKg              pgtype.Numeric
	Rpe                   pgtype.Numeric
	Notes                 *string
}

type ApolloPlannerWeek struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	WeekStart pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApolloPublicBookingReceipt struct {
	ReceiptCode      string
	BookingRequestID uuid.UUID
	PublicMessage    *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ApolloRecommendation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Content    []byte
	ModelUsed  string
	LatencyMs  *int32
	Feedback   *string
	CreatedAt  pgtype.Timestamptz
	FeedbackAt pgtype.Timestamptz
}

type ApolloScheduleBlock struct {
	ID                           uuid.UUID
	FacilityKey                  string
	ZoneKey                      *string
	ResourceKey                  *string
	Scope                        string
	ScheduleType                 string
	Kind                         string
	Effect                       string
	Visibility                   string
	Status                       string
	Version                      int32
	Weekday                      *int16
	StartTime                    pgtype.Time
	EndTime                      pgtype.Time
	Timezone                     *string
	RecurrenceStartDate          pgtype.Date
	RecurrenceEndDate            pgtype.Date
	StartAt                      pgtype.Timestamptz
	EndAt                        pgtype.Timestamptz
	CreatedByUserID              uuid.UUID
	CreatedBySessionID           uuid.UUID
	CreatedByRole                string
	CreatedByCapability          string
	CreatedTrustedSurfaceKey     string
	CreatedTrustedSurfaceLabel   *string
	UpdatedByUserID              uuid.UUID
	UpdatedBySessionID           uuid.UUID
	UpdatedByRole                string
	UpdatedByCapability          string
	UpdatedTrustedSurfaceKey     string
	UpdatedTrustedSurfaceLabel   *string
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	CancelledAt                  pgtype.Timestamptz
	CancelledByUserID            pgtype.UUID
	CancelledBySessionID         pgtype.UUID
	CancelledByRole              *string
	CancelledByCapability        *string
	CancelledTrustedSurfaceKey   *string
	CancelledTrustedSurfaceLabel *string
}

type ApolloScheduleBlockException struct {
	ID                         uuid.UUID
	ScheduleBlockID            uuid.UUID
	ExceptionDate              pgtype.Date
	CreatedByUserID            uuid.UUID
	CreatedBySessionID         uuid.UUID
	CreatedByRole              string
	CreatedByCapability        string
	CreatedTrustedSurfaceKey   string
	CreatedTrustedSurfaceLabel *string
	CreatedAt                  pgtype.Timestamptz
}

type ApolloScheduleResource struct {
	ResourceKey    string
	FacilityKey    string
	ZoneKey        *string
	ResourceType   string
	DisplayName    string
	PublicLabel    *string
	Bookable       bool
	Active         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PublicOptionID uuid.UUID
}

type ApolloScheduleResourceEdge struct {
	ResourceKey        string
	RelatedResourceKey string
	EdgeType           string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ApolloSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ApolloSport struct {
	SportKey                    string
	DisplayName                 string
	Description                 string
	CompetitionMode             string
	SidesPerMatch               int32
	ParticipantsPerSideMin      int32
	ParticipantsPerSideMax      int32
	ScoringModel                string
	DefaultMatchDurationMinutes int32
	RulesSummary                string
}

type ApolloSportFacilityCapability struct {
	SportKey    string
	FacilityKey string
}

type ApolloSportFacilityCapabilityZone struct {
	SportKey    string
	FacilityKey string
	ZoneKey     string
}

type ApolloUser struct {
	ID              uuid.UUID
	StudentID       string
	DisplayName     string
	Email           string
	Preferences     []byte
	CreatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Role            string
}

type ApolloVisit struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	FacilityKey            string
	ZoneKey                *string
	SourceEventID          *string
	ArrivedAt              pgtype.Timestamptz
	DepartedAt             pgtype.Timestamptz
	Metadata               []byte
	DepartureSourceEventID *string
}

type ApolloVisitTapLink struct {
	VisitID      uuid.UUID
	ClaimedTagID uuid.UUID
	LinkedAt     pgtype.Timestamptz
}

type ApolloWorkout struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	StartedAt  pgtype.Timestamptz
	Notes      *string
	Metadata   []byte
	Status     string
	FinishedAt pgtype.Timestamptz
}

type ApolloWorkoutEffortFeedback struct {
	WorkoutID   uuid.UUID
	UserID      uuid.UUID
	EffortLevel string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ApolloWorkoutRecoveryFeedback struct {
	WorkoutID     uuid.UUID
	UserID        uuid.UUID
	RecoveryLevel string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ApolloWorkoutTemplate struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApolloWorkoutTemplateItem struct {
	ID                    uuid.UUID
	WorkoutTemplateID     uuid.UUID
	Position              int32
	ExerciseDefinitionID  uuid.UUID
	EquipmentDefinitionID pgtype.UUID
	Sets                  int32
	Reps                  int32
	WeightKg              pgtype.Numeric
	Rpe                   pgtype.Numeric
	Notes                 *string
}
