// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nutrition.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMealLog = `-- name: CreateMealLog :one
INSERT INTO apollo.nutrition_meal_logs (
  user_id,
  source_template_id,
  name,
  meal_type,
  logged_at,
  calories,
  protein_grams,
  carbs_grams,
  fat_grams,
  notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, source_template_id, name, meal_type, logged_at, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
`

type CreateMealLogParams struct {
	UserID           uuid.UUID
	SourceTemplateID pgtype.UUID
	Name             string
	MealType         string
	LoggedAt         pgtype.Timestamptz
	Calories         *int32
	ProteinGrams     *int32
	CarbsGrams       *int32
	FatGrams         *int32
	Notes            *string
}

func (q *Queries) CreateMealLog(ctx context.Context, arg CreateMealLogParams) (ApolloNutritionMealLog, error) {
	row := q.db.QueryRow(ctx, createMealLog,
		arg.UserID,
		arg.SourceTemplateID,
		arg.Name,
		arg.MealType,
		arg.LoggedAt,
		arg.Calories,
		arg.ProteinGrams,
		arg.CarbsGrams,
		arg.FatGrams,
		arg.Notes,
	)
	var i ApolloNutritionMealLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceTemplateID,
		&i.Name,
		&i.MealType,
		&i.LoggedAt,
		&i.Calories,
		&i.ProteinGrams,
		&i.CarbsGrams,
		&i.FatGrams,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMealTemplate = `-- name: CreateMealTemplate :one
INSERT INTO apollo.nutrition_meal_templates (
  user_id,
  name,
  meal_type,
  calories,
  protein_grams,
  carbs_grams,
  fat_grams,
  notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, meal_type, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
`

type CreateMealTemplateParams struct {
	UserID       uuid.UUID
	Name         string
	MealType     string
	Calories     *int32
	ProteinGrams *int32
	CarbsGrams   *int32
	FatGrams     *int32
	Notes        *string
}

func (q *Queries) CreateMealTemplate(ctx context.Context, arg CreateMealTemplateParams) (ApolloNutritionMealTemplate, error) {
	row := q.db.QueryRow(ctx, createMealTemplate,
		arg.UserID,
		arg.Name,
		arg.MealType,
		arg.Calories,
		arg.ProteinGrams,
		arg.CarbsGrams,
		arg.FatGrams,
		arg.Notes,
	)
	var i ApolloNutritionMealTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MealType,
		&i.Calories,
		&i.ProteinGrams,
		&i.CarbsGrams,
		&i.FatGrams,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealLogByIDForUser = `-- name: GetMealLogByIDForUser :one
SELECT id, user_id, source_template_id, name, meal_type, logged_at, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
FROM apollo.nutrition_meal_logs
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetMealLogByIDForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMealLogByIDForUser(ctx context.Context, arg GetMealLogByIDForUserParams) (ApolloNutritionMealLog, error) {
	row := q.db.QueryRow(ctx, getMealLogByIDForUser, arg.ID, arg.UserID)
	var i ApolloNutritionMealLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceTemplateID,
		&i.Name,
		&i.MealType,
		&i.LoggedAt,
		&i.Calories,
		&i.ProteinGrams,
		&i.CarbsGrams,
		&i.FatGrams,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealTemplateByIDForUser = `-- name: GetMealTemplateByIDForUser :one
SELECT id, user_id, name, meal_type, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
FROM apollo.nutrition_meal_templates
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetMealTemplateByIDForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMealTemplateByIDForUser(ctx context.Context, arg GetMealTemplateByIDForUserParams) (ApolloNutritionMealTemplate, error) {
	row := q.db.QueryRow(ctx, getMealTemplateByIDForUser, arg.ID, arg.UserID)
	var i ApolloNutritionMealTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MealType,
		&i.Calories,
		&i.ProteinGrams,
		&i.CarbsGrams,
		&i.FatGrams,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMealLogsByUserID = `-- name: ListMealLogsByUserID :many
SELECT id, user_id, source_template_id, name, meal_type, logged_at, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
FROM apollo.nutrition_meal_logs
WHERE user_id = $1
ORDER BY logged_at DESC, id DESC
`

func (q *Queries) ListMealLogsByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloNutritionMealLog, error) {
	rows, err := q.db.Query(ctx, listMealLogsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloNutritionMealLog
	for rows.Next() {
		var i ApolloNutritionMealLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceTemplateID,
			&i.Name,
			&i.MealType,
			&i.LoggedAt,
			&i.Calories,
			&i.ProteinGrams,
			&i.CarbsGrams,
			&i.FatGrams,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealLogsByUserIDWithinRange = `-- name: ListMealLogsByUserIDWithinRange :many
SELECT id, user_id, source_template_id, name, meal_type, logged_at, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
FROM apollo.nutrition_meal_logs
WHERE user_id = $1
  AND logged_at >= $2
  AND logged_at < $3
ORDER BY logged_at DESC, id DESC
`

type ListMealLogsByUserIDWithinRangeParams struct {
	UserID     uuid.UUID
	LoggedAt   pgtype.Timestamptz
	LoggedAt_2 pgtype.Timestamptz
}

func (q *Queries) ListMealLogsByUserIDWithinRange(ctx context.Context, arg ListMealLogsByUserIDWithinRangeParams) ([]ApolloNutritionMealLog, error) {
	rows, err := q.db.Query(ctx, listMealLogsByUserIDWithinRange, arg.UserID, arg.LoggedAt, arg.LoggedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloNutritionMealLog
	for rows.Next() {
		var i ApolloNutritionMealLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceTemplateID,
			&i.Name,
			&i.MealType,
			&i.LoggedAt,
			&i.Calories,
			&i.ProteinGrams,
			&i.CarbsGrams,
			&i.FatGrams,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealTemplatesByUserID = `-- name: ListMealTemplatesByUserID :many
SELECT id, user_id, name, meal_type, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
FROM apollo.nutrition_meal_templates
WHERE user_id = $1
ORDER BY lower(name), id
`

func (q *Queries) ListMealTemplatesByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloNutritionMealTemplate, error) {
	rows, err := q.db.Query(ctx, listMealTemplatesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloNutritionMealTemplate
	for rows.Next() {
		var i ApolloNutritionMealTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.MealType,
			&i.Calories,
			&i.ProteinGrams,
			&i.CarbsGrams,
			&i.FatGrams,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMealLogForUser = `-- name: UpdateMealLogForUser :one
UPDATE apollo.nutrition_meal_logs
SET source_template_id = $3,
    name = $4,
    meal_type = $5,
    logged_at = $6,
    calories = $7,
    protein_grams = $8,
    carbs_grams = $9,
    fat_grams = $10,
    notes = $11,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, source_template_id, name, meal_type, logged_at, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
`

type UpdateMealLogForUserParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	SourceTemplateID pgtype.UUID
	Name             string
	MealType         string
	LoggedAt         pgtype.Timestamptz
	Calories         *int32
	ProteinGrams     *int32
	CarbsGrams       *int32
	FatGrams         *int32
	Notes            *string
}

func (q *Queries) UpdateMealLogForUser(ctx context.Context, arg UpdateMealLogForUserParams) (ApolloNutritionMealLog, error) {
	row := q.db.QueryRow(ctx, updateMealLogForUser,
		arg.ID,
		arg.UserID,
		arg.SourceTemplateID,
		arg.Name,
		arg.MealType,
		arg.LoggedAt,
		arg.Calories,
		arg.ProteinGrams,
		arg.CarbsGrams,
		arg.FatGrams,
		arg.Notes,
	)
	var i ApolloNutritionMealLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceTemplateID,
		&i.Name,
		&i.MealType,
		&i.LoggedAt,
		&i.Calories,
		&i.ProteinGrams,
		&i.CarbsGrams,
		&i.FatGrams,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMealTemplateForUser = `-- name: UpdateMealTemplateForUser :one
UPDATE apollo.nutrition_meal_templates
SET name = $3,
    meal_type = $4,
    calories = $5,
    protein_grams = $6,
    carbs_grams = $7,
    fat_grams = $8,
    notes = $9,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, meal_type, calories, protein_grams, carbs_grams, fat_grams, notes, created_at, updated_at
`

type UpdateMealTemplateForUserParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	MealType     string
	Calories     *int32
	ProteinGrams *int32
	CarbsGrams   *int32
	FatGrams     *int32
	Notes        *string
}

func (q *Queries) UpdateMealTemplateForUser(ctx context.Context, arg UpdateMealTemplateForUserParams) (ApolloNutritionMealTemplate, error) {
	row := q.db.QueryRow(ctx, updateMealTemplateForUser,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.MealType,
		arg.Calories,
		arg.ProteinGrams,
		arg.CarbsGrams,
		arg.FatGrams,
		arg.Notes,
	)
	var i ApolloNutritionMealTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MealType,
		&i.Calories,
		&i.ProteinGrams,
		&i.CarbsGrams,
		&i.FatGrams,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
