// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presence.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveClaimedTagByHash = `-- name: GetActiveClaimedTagByHash :one
SELECT ct.id, ct.user_id, ct.tag_hash, ct.label, ct.is_active, ct.claimed_at
FROM apollo.claimed_tags AS ct
WHERE ct.tag_hash = $1
  AND ct.is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveClaimedTagByHash(ctx context.Context, tagHash string) (ApolloClaimedTag, error) {
	row := q.db.QueryRow(ctx, getActiveClaimedTagByHash, tagHash)
	var i ApolloClaimedTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagHash,
		&i.Label,
		&i.IsActive,
		&i.ClaimedAt,
	)
	return i, err
}

const getMemberPresenceStreakByUserIDAndFacilityKey = `-- name: GetMemberPresenceStreakByUserIDAndFacilityKey :one
SELECT user_id, facility_key, current_count, current_start_day, last_credited_day, last_linked_visit_id, updated_at
FROM apollo.member_presence_streaks
WHERE user_id = $1
  AND facility_key = $2
LIMIT 1
`

type GetMemberPresenceStreakByUserIDAndFacilityKeyParams struct {
	UserID      uuid.UUID
	FacilityKey string
}

func (q *Queries) GetMemberPresenceStreakByUserIDAndFacilityKey(ctx context.Context, arg GetMemberPresenceStreakByUserIDAndFacilityKeyParams) (ApolloMemberPresenceStreak, error) {
	row := q.db.QueryRow(ctx, getMemberPresenceStreakByUserIDAndFacilityKey, arg.UserID, arg.FacilityKey)
	var i ApolloMemberPresenceStreak
	err := row.Scan(
		&i.UserID,
		&i.FacilityKey,
		&i.CurrentCount,
		&i.CurrentStartDay,
		&i.LastCreditedDay,
		&i.LastLinkedVisitID,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberPresenceStreakByUserIDAndFacilityKeyForUpdate = `-- name: GetMemberPresenceStreakByUserIDAndFacilityKeyForUpdate :one
SELECT user_id, facility_key, current_count, current_start_day, last_credited_day, last_linked_visit_id, updated_at
FROM apollo.member_presence_streaks
WHERE user_id = $1
  AND facility_key = $2
LIMIT 1
FOR UPDATE
`

type GetMemberPresenceStreakByUserIDAndFacilityKeyForUpdateParams struct {
	UserID      uuid.UUID
	FacilityKey string
}

func (q *Queries) GetMemberPresenceStreakByUserIDAndFacilityKeyForUpdate(ctx context.Context, arg GetMemberPresenceStreakByUserIDAndFacilityKeyForUpdateParams) (ApolloMemberPresenceStreak, error) {
	row := q.db.QueryRow(ctx, getMemberPresenceStreakByUserIDAndFacilityKeyForUpdate, arg.UserID, arg.FacilityKey)
	var i ApolloMemberPresenceStreak
	err := row.Scan(
		&i.UserID,
		&i.FacilityKey,
		&i.CurrentCount,
		&i.CurrentStartDay,
		&i.LastCreditedDay,
		&i.LastLinkedVisitID,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisitTapLinkByVisitID = `-- name: GetVisitTapLinkByVisitID :one
SELECT visit_id, claimed_tag_id, linked_at
FROM apollo.visit_tap_links
WHERE visit_id = $1
LIMIT 1
`

func (q *Queries) GetVisitTapLinkByVisitID(ctx context.Context, visitID uuid.UUID) (ApolloVisitTapLink, error) {
	row := q.db.QueryRow(ctx, getVisitTapLinkByVisitID, visitID)
	var i ApolloVisitTapLink
	err := row.Scan(&i.VisitID, &i.ClaimedTagID, &i.LinkedAt)
	return i, err
}

const insertMemberPresenceStreakEvent = `-- name: InsertMemberPresenceStreakEvent :execrows
INSERT INTO apollo.member_presence_streak_events (
  user_id,
  facility_key,
  event_kind,
  count_before,
  count_after,
  streak_day,
  visit_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, facility_key, streak_day) DO NOTHING
`

type InsertMemberPresenceStreakEventParams struct {
	UserID      uuid.UUID
	FacilityKey string
	EventKind   string
	CountBefore int32
	CountAfter  int32
	StreakDay   pgtype.Date
	VisitID     uuid.UUID
}

func (q *Queries) InsertMemberPresenceStreakEvent(ctx context.Context, arg InsertMemberPresenceStreakEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMemberPresenceStreakEvent,
		arg.UserID,
		arg.FacilityKey,
		arg.EventKind,
		arg.CountBefore,
		arg.CountAfter,
		arg.StreakDay,
		arg.VisitID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertVisitTapLink = `-- name: InsertVisitTapLink :execrows
INSERT INTO apollo.visit_tap_links (
  visit_id,
  claimed_tag_id
)
SELECT $1, ct.id
FROM apollo.claimed_tags AS ct
WHERE ct.id = $2
  AND ct.user_id = $3
  AND ct.is_active = TRUE
ON CONFLICT (visit_id) DO NOTHING
`

type InsertVisitTapLinkParams struct {
	VisitID uuid.UUID
	ID      uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) InsertVisitTapLink(ctx context.Context, arg InsertVisitTapLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVisitTapLink, arg.VisitID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFacilityPresenceStreaksByUserID = `-- name: ListFacilityPresenceStreaksByUserID :many
SELECT user_id, facility_key, current_count, current_start_day, last_credited_day, last_linked_visit_id, updated_at
FROM apollo.member_presence_streaks
WHERE user_id = $1
ORDER BY facility_key ASC
`

func (q *Queries) ListFacilityPresenceStreaksByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloMemberPresenceStreak, error) {
	rows, err := q.db.Query(ctx, listFacilityPresenceStreaksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloMemberPresenceStreak
	for rows.Next() {
		var i ApolloMemberPresenceStreak
		if err := rows.Scan(
			&i.UserID,
			&i.FacilityKey,
			&i.CurrentCount,
			&i.CurrentStartDay,
			&i.LastCreditedDay,
			&i.LastLinkedVisitID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestMemberPresenceStreakEventsByUserID = `-- name: ListLatestMemberPresenceStreakEventsByUserID :many
SELECT DISTINCT ON (facility_key)
  id,
  user_id,
  facility_key,
  event_kind,
  count_before,
  count_after,
  streak_day,
  visit_id,
  created_at
FROM apollo.member_presence_streak_events
WHERE user_id = $1
ORDER BY facility_key ASC, streak_day DESC, created_at DESC, id DESC
`

func (q *Queries) ListLatestMemberPresenceStreakEventsByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloMemberPresenceStreakEvent, error) {
	rows, err := q.db.Query(ctx, listLatestMemberPresenceStreakEventsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloMemberPresenceStreakEvent
	for rows.Next() {
		var i ApolloMemberPresenceStreakEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FacilityKey,
			&i.EventKind,
			&i.CountBefore,
			&i.CountAfter,
			&i.StreakDay,
			&i.VisitID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedVisitsByUserID = `-- name: ListLinkedVisitsByUserID :many
SELECT v.id, v.user_id, v.facility_key, v.zone_key, v.source_event_id, v.arrived_at, v.departed_at, v.metadata, v.departure_source_event_id
FROM apollo.visits AS v
JOIN apollo.visit_tap_links AS vtl ON vtl.visit_id = v.id
WHERE v.user_id = $1
ORDER BY v.facility_key ASC, v.arrived_at DESC, v.id DESC
`

func (q *Queries) ListLinkedVisitsByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloVisit, error) {
	rows, err := q.db.Query(ctx, listLinkedVisitsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloVisit
	for rows.Next() {
		var i ApolloVisit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FacilityKey,
			&i.ZoneKey,
			&i.SourceEventID,
			&i.ArrivedAt,
			&i.DepartedAt,
			&i.Metadata,
			&i.DepartureSourceEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitTapLinksByUserID = `-- name: ListVisitTapLinksByUserID :many
SELECT vtl.visit_id, vtl.claimed_tag_id, vtl.linked_at
FROM apollo.visit_tap_links AS vtl
JOIN apollo.visits AS v ON v.id = vtl.visit_id
WHERE v.user_id = $1
ORDER BY v.facility_key ASC, v.arrived_at DESC, v.id DESC
`

func (q *Queries) ListVisitTapLinksByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloVisitTapLink, error) {
	rows, err := q.db.Query(ctx, listVisitTapLinksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloVisitTapLink
	for rows.Next() {
		var i ApolloVisitTapLink
		if err := rows.Scan(&i.VisitID, &i.ClaimedTagID, &i.LinkedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemberPresenceStreak = `-- name: UpsertMemberPresenceStreak :one
INSERT INTO apollo.member_presence_streaks (
  user_id,
  facility_key,
  current_count,
  current_start_day,
  last_credited_day,
  last_linked_visit_id,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, facility_key) DO UPDATE
SET current_count = EXCLUDED.current_count,
    current_start_day = EXCLUDED.current_start_day,
    last_credited_day = EXCLUDED.last_credited_day,
    last_linked_visit_id = EXCLUDED.last_linked_visit_id,
    updated_at = EXCLUDED.updated_at
RETURNING user_id, facility_key, current_count, current_start_day, last_credited_day, last_linked_visit_id, updated_at
`

type UpsertMemberPresenceStreakParams struct {
	UserID            uuid.UUID
	FacilityKey       string
	CurrentCount      int32
	CurrentStartDay   pgtype.Date
	LastCreditedDay   pgtype.Date
	LastLinkedVisitID uuid.UUID
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpsertMemberPresenceStreak(ctx context.Context, arg UpsertMemberPresenceStreakParams) (ApolloMemberPresenceStreak, error) {
	row := q.db.QueryRow(ctx, upsertMemberPresenceStreak,
		arg.UserID,
		arg.FacilityKey,
		arg.CurrentCount,
		arg.CurrentStartDay,
		arg.LastCreditedDay,
		arg.LastLinkedVisitID,
		arg.UpdatedAt,
	)
	var i ApolloMemberPresenceStreak
	err := row.Scan(
		&i.UserID,
		&i.FacilityKey,
		&i.CurrentCount,
		&i.CurrentStartDay,
		&i.LastCreditedDay,
		&i.LastLinkedVisitID,
		&i.UpdatedAt,
	)
	return i, err
}
