// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getLatestFinishedWorkoutByUserID = `-- name: GetLatestFinishedWorkoutByUserID :one
SELECT w.id, w.user_id, w.started_at, w.notes, w.metadata, w.status, w.finished_at
FROM apollo.workouts AS w
WHERE w.user_id = $1
  AND w.status = 'finished'
ORDER BY w.finished_at DESC,
         w.started_at DESC,
         w.id DESC
LIMIT 1
`

func (q *Queries) GetLatestFinishedWorkoutByUserID(ctx context.Context, userID uuid.UUID) (ApolloWorkout, error) {
	row := q.db.QueryRow(ctx, getLatestFinishedWorkoutByUserID, userID)
	var i ApolloWorkout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.Notes,
		&i.Metadata,
		&i.Status,
		&i.FinishedAt,
	)
	return i, err
}
