// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpScheduleBlockVersion = `-- name: BumpScheduleBlockVersion :one
UPDATE apollo.schedule_blocks
SET version = version + 1,
    updated_by_user_id = $3,
    updated_by_session_id = $4,
    updated_by_role = $5,
    updated_by_capability = $6,
    updated_trusted_surface_key = $7,
    updated_trusted_surface_label = $8,
    updated_at = $9
WHERE id = $1
  AND version = $2
  AND status = 'scheduled'
RETURNING id,
          facility_key,
          zone_key,
          resource_key,
          scope,
          schedule_type,
          kind,
          effect,
          visibility,
          status,
          version,
          weekday,
          start_time,
          end_time,
          timezone,
          recurrence_start_date,
          recurrence_end_date,
          start_at,
          end_at,
          created_by_user_id,
          created_by_session_id,
          created_by_role,
          created_by_capability,
          created_trusted_surface_key,
          created_trusted_surface_label,
          updated_by_user_id,
          updated_by_session_id,
          updated_by_role,
          updated_by_capability,
          updated_trusted_surface_key,
          updated_trusted_surface_label,
          created_at,
          updated_at,
          cancelled_at,
          cancelled_by_user_id,
          cancelled_by_session_id,
          cancelled_by_role,
          cancelled_by_capability,
          cancelled_trusted_surface_key,
          cancelled_trusted_surface_label
`

type BumpScheduleBlockVersionParams struct {
	ID                         uuid.UUID
	Version                    int32
	UpdatedByUserID            uuid.UUID
	UpdatedBySessionID         uuid.UUID
	UpdatedByRole              string
	UpdatedByCapability        string
	UpdatedTrustedSurfaceKey   string
	UpdatedTrustedSurfaceLabel *string
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) BumpScheduleBlockVersion(ctx context.Context, arg BumpScheduleBlockVersionParams) (ApolloScheduleBlock, error) {
	row := q.db.QueryRow(ctx, bumpScheduleBlockVersion,
		arg.ID,
		arg.Version,
		arg.UpdatedByUserID,
		arg.UpdatedBySessionID,
		arg.UpdatedByRole,
		arg.UpdatedByCapability,
		arg.UpdatedTrustedSurfaceKey,
		arg.UpdatedTrustedSurfaceLabel,
		arg.UpdatedAt,
	)
	var i ApolloScheduleBlock
	err := row.Scan(
		&i.ID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ResourceKey,
		&i.Scope,
		&i.ScheduleType,
		&i.Kind,
		&i.Effect,
		&i.Visibility,
		&i.Status,
		&i.Version,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.RecurrenceStartDate,
		&i.RecurrenceEndDate,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedByUserID,
		&i.CreatedBySessionID,
		&i.CreatedByRole,
		&i.CreatedByCapability,
		&i.CreatedTrustedSurfaceKey,
		&i.CreatedTrustedSurfaceLabel,
		&i.UpdatedByUserID,
		&i.UpdatedBySessionID,
		&i.UpdatedByRole,
		&i.UpdatedByCapability,
		&i.UpdatedTrustedSurfaceKey,
		&i.UpdatedTrustedSurfaceLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CancelledBySessionID,
		&i.CancelledByRole,
		&i.CancelledByCapability,
		&i.CancelledTrustedSurfaceKey,
		&i.CancelledTrustedSurfaceLabel,
	)
	return i, err
}

const cancelScheduleBlock = `-- name: CancelScheduleBlock :one
UPDATE apollo.schedule_blocks
SET status = 'cancelled',
    version = version + 1,
    updated_by_user_id = $3,
    updated_by_session_id = $4,
    updated_by_role = $5,
    updated_by_capability = $6,
    updated_trusted_surface_key = $7,
    updated_trusted_surface_label = $8,
    cancelled_at = $9,
    cancelled_by_user_id = $3,
    cancelled_by_session_id = $4,
    cancelled_by_role = $5,
    cancelled_by_capability = $6,
    cancelled_trusted_surface_key = $7,
    cancelled_trusted_surface_label = $8,
    updated_at = $9
WHERE id = $1
  AND version = $2
  AND status = 'scheduled'
RETURNING id,
          facility_key,
          zone_key,
          resource_key,
          scope,
          schedule_type,
          kind,
          effect,
          visibility,
          status,
          version,
          weekday,
          start_time,
          end_time,
          timezone,
          recurrence_start_date,
          recurrence_end_date,
          start_at,
          end_at,
          created_by_user_id,
          created_by_session_id,
          created_by_role,
          created_by_capability,
          created_trusted_surface_key,
          created_trusted_surface_label,
          updated_by_user_id,
          updated_by_session_id,
          updated_by_role,
          updated_by_capability,
          updated_trusted_surface_key,
          updated_trusted_surface_label,
          created_at,
          updated_at,
          cancelled_at,
          cancelled_by_user_id,
          cancelled_by_session_id,
          cancelled_by_role,
          cancelled_by_capability,
          cancelled_trusted_surface_key,
          cancelled_trusted_surface_label
`

type CancelScheduleBlockParams struct {
	ID                         uuid.UUID
	Version                    int32
	UpdatedByUserID            uuid.UUID
	UpdatedBySessionID         uuid.UUID
	UpdatedByRole              string
	UpdatedByCapability        string
	UpdatedTrustedSurfaceKey   string
	UpdatedTrustedSurfaceLabel *string
	CancelledAt                pgtype.Timestamptz
}

func (q *Queries) CancelScheduleBlock(ctx context.Context, arg CancelScheduleBlockParams) (ApolloScheduleBlock, error) {
	row := q.db.QueryRow(ctx, cancelScheduleBlock,
		arg.ID,
		arg.Version,
		arg.UpdatedByUserID,
		arg.UpdatedBySessionID,
		arg.UpdatedByRole,
		arg.UpdatedByCapability,
		arg.UpdatedTrustedSurfaceKey,
		arg.UpdatedTrustedSurfaceLabel,
		arg.CancelledAt,
	)
	var i ApolloScheduleBlock
	err := row.Scan(
		&i.ID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ResourceKey,
		&i.Scope,
		&i.ScheduleType,
		&i.Kind,
		&i.Effect,
		&i.Visibility,
		&i.Status,
		&i.Version,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.RecurrenceStartDate,
		&i.RecurrenceEndDate,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedByUserID,
		&i.CreatedBySessionID,
		&i.CreatedByRole,
		&i.CreatedByCapability,
		&i.CreatedTrustedSurfaceKey,
		&i.CreatedTrustedSurfaceLabel,
		&i.UpdatedByUserID,
		&i.UpdatedBySessionID,
		&i.UpdatedByRole,
		&i.UpdatedByCapability,
		&i.UpdatedTrustedSurfaceKey,
		&i.UpdatedTrustedSurfaceLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CancelledBySessionID,
		&i.CancelledByRole,
		&i.CancelledByCapability,
		&i.CancelledTrustedSurfaceKey,
		&i.CancelledTrustedSurfaceLabel,
	)
	return i, err
}

const createScheduleBlock = `-- name: CreateScheduleBlock :one
INSERT INTO apollo.schedule_blocks (
    facility_key,
    zone_key,
    resource_key,
    scope,
    schedule_type,
    kind,
    effect,
    visibility,
    status,
    version,
    weekday,
    start_time,
    end_time,
    timezone,
    recurrence_start_date,
    recurrence_end_date,
    start_at,
    end_at,
    created_by_user_id,
    created_by_session_id,
    created_by_role,
    created_by_capability,
    created_trusted_surface_key,
    created_trusted_surface_label,
    updated_by_user_id,
    updated_by_session_id,
    updated_by_role,
    updated_by_capability,
    updated_trusted_surface_key,
    updated_trusted_surface_label,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'scheduled', 1, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30)
RETURNING id,
          facility_key,
          zone_key,
          resource_key,
          scope,
          schedule_type,
          kind,
          effect,
          visibility,
          status,
          version,
          weekday,
          start_time,
          end_time,
          timezone,
          recurrence_start_date,
          recurrence_end_date,
          start_at,
          end_at,
          created_by_user_id,
          created_by_session_id,
          created_by_role,
          created_by_capability,
          created_trusted_surface_key,
          created_trusted_surface_label,
          updated_by_user_id,
          updated_by_session_id,
          updated_by_role,
          updated_by_capability,
          updated_trusted_surface_key,
          updated_trusted_surface_label,
          created_at,
          updated_at,
          cancelled_at,
          cancelled_by_user_id,
          cancelled_by_session_id,
          cancelled_by_role,
          cancelled_by_capability,
          cancelled_trusted_surface_key,
          cancelled_trusted_surface_label
`

type CreateScheduleBlockParams struct {
	FacilityKey                string
	ZoneKey                    *string
	ResourceKey                *string
	Scope                      string
	ScheduleType               string
	Kind                       string
	Effect                     string
	Visibility                 string
	Weekday                    *int16
	StartTime                  pgtype.Time
	EndTime                    pgtype.Time
	Timezone                   *string
	RecurrenceStartDate        pgtype.Date
	RecurrenceEndDate          pgtype.Date
	StartAt                    pgtype.Timestamptz
	EndAt                      pgtype.Timestamptz
	CreatedByUserID            uuid.UUID
	CreatedBySessionID         uuid.UUID
	CreatedByRole              string
	CreatedByCapability        string
	CreatedTrustedSurfaceKey   string
	CreatedTrustedSurfaceLabel *string
	UpdatedByUserID            uuid.UUID
	UpdatedBySessionID         uuid.UUID
	UpdatedByRole              string
	UpdatedByCapability        string
	UpdatedTrustedSurfaceKey   string
	UpdatedTrustedSurfaceLabel *string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) CreateScheduleBlock(ctx context.Context, arg CreateScheduleBlockParams) (ApolloScheduleBlock, error) {
	row := q.db.QueryRow(ctx, createScheduleBlock,
		arg.FacilityKey,
		arg.ZoneKey,
		arg.ResourceKey,
		arg.Scope,
		arg.ScheduleType,
		arg.Kind,
		arg.Effect,
		arg.Visibility,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
		arg.RecurrenceStartDate,
		arg.RecurrenceEndDate,
		arg.StartAt,
		arg.EndAt,
		arg.CreatedByUserID,
		arg.CreatedBySessionID,
		arg.CreatedByRole,
		arg.CreatedByCapability,
		arg.CreatedTrustedSurfaceKey,
		arg.CreatedTrustedSurfaceLabel,
		arg.UpdatedByUserID,
		arg.UpdatedBySessionID,
		arg.UpdatedByRole,
		arg.UpdatedByCapability,
		arg.UpdatedTrustedSurfaceKey,
		arg.UpdatedTrustedSurfaceLabel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ApolloScheduleBlock
	err := row.Scan(
		&i.ID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ResourceKey,
		&i.Scope,
		&i.ScheduleType,
		&i.Kind,
		&i.Effect,
		&i.Visibility,
		&i.Status,
		&i.Version,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.RecurrenceStartDate,
		&i.RecurrenceEndDate,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedByUserID,
		&i.CreatedBySessionID,
		&i.CreatedByRole,
		&i.CreatedByCapability,
		&i.CreatedTrustedSurfaceKey,
		&i.CreatedTrustedSurfaceLabel,
		&i.UpdatedByUserID,
		&i.UpdatedBySessionID,
		&i.UpdatedByRole,
		&i.UpdatedByCapability,
		&i.UpdatedTrustedSurfaceKey,
		&i.UpdatedTrustedSurfaceLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CancelledBySessionID,
		&i.CancelledByRole,
		&i.CancelledByCapability,
		&i.CancelledTrustedSurfaceKey,
		&i.CancelledTrustedSurfaceLabel,
	)
	return i, err
}

const facilityZoneRefExists = `-- name: FacilityZoneRefExists :one
SELECT EXISTS (
    SELECT 1
    FROM apollo.facility_zone_refs
    WHERE facility_key = $1
      AND zone_key = $2
)
`

type FacilityZoneRefExistsParams struct {
	FacilityKey string
	ZoneKey     string
}

func (q *Queries) FacilityZoneRefExists(ctx context.Context, arg FacilityZoneRefExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, facilityZoneRefExists, arg.FacilityKey, arg.ZoneKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getScheduleBlockByID = `-- name: GetScheduleBlockByID :one
SELECT id,
       facility_key,
       zone_key,
       resource_key,
       scope,
       schedule_type,
       kind,
       effect,
       visibility,
       status,
       version,
       weekday,
       start_time,
       end_time,
       timezone,
       recurrence_start_date,
       recurrence_end_date,
       start_at,
       end_at,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       updated_by_user_id,
       updated_by_session_id,
       updated_by_role,
       updated_by_capability,
       updated_trusted_surface_key,
       updated_trusted_surface_label,
       created_at,
       updated_at,
       cancelled_at,
       cancelled_by_user_id,
       cancelled_by_session_id,
       cancelled_by_role,
       cancelled_by_capability,
       cancelled_trusted_surface_key,
       cancelled_trusted_surface_label
FROM apollo.schedule_blocks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetScheduleBlockByID(ctx context.Context, id uuid.UUID) (ApolloScheduleBlock, error) {
	row := q.db.QueryRow(ctx, getScheduleBlockByID, id)
	var i ApolloScheduleBlock
	err := row.Scan(
		&i.ID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ResourceKey,
		&i.Scope,
		&i.ScheduleType,
		&i.Kind,
		&i.Effect,
		&i.Visibility,
		&i.Status,
		&i.Version,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.RecurrenceStartDate,
		&i.RecurrenceEndDate,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedByUserID,
		&i.CreatedBySessionID,
		&i.CreatedByRole,
		&i.CreatedByCapability,
		&i.CreatedTrustedSurfaceKey,
		&i.CreatedTrustedSurfaceLabel,
		&i.UpdatedByUserID,
		&i.UpdatedBySessionID,
		&i.UpdatedByRole,
		&i.UpdatedByCapability,
		&i.UpdatedTrustedSurfaceKey,
		&i.UpdatedTrustedSurfaceLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CancelledBySessionID,
		&i.CancelledByRole,
		&i.CancelledByCapability,
		&i.CancelledTrustedSurfaceKey,
		&i.CancelledTrustedSurfaceLabel,
	)
	return i, err
}

const getScheduleBlockByIDForUpdate = `-- name: GetScheduleBlockByIDForUpdate :one
SELECT id,
       facility_key,
       zone_key,
       resource_key,
       scope,
       schedule_type,
       kind,
       effect,
       visibility,
       status,
       version,
       weekday,
       start_time,
       end_time,
       timezone,
       recurrence_start_date,
       recurrence_end_date,
       start_at,
       end_at,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       updated_by_user_id,
       updated_by_session_id,
       updated_by_role,
       updated_by_capability,
       updated_trusted_surface_key,
       updated_trusted_surface_label,
       created_at,
       updated_at,
       cancelled_at,
       cancelled_by_user_id,
       cancelled_by_session_id,
       cancelled_by_role,
       cancelled_by_capability,
       cancelled_trusted_surface_key,
       cancelled_trusted_surface_label
FROM apollo.schedule_blocks
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetScheduleBlockByIDForUpdate(ctx context.Context, id uuid.UUID) (ApolloScheduleBlock, error) {
	row := q.db.QueryRow(ctx, getScheduleBlockByIDForUpdate, id)
	var i ApolloScheduleBlock
	err := row.Scan(
		&i.ID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ResourceKey,
		&i.Scope,
		&i.ScheduleType,
		&i.Kind,
		&i.Effect,
		&i.Visibility,
		&i.Status,
		&i.Version,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.RecurrenceStartDate,
		&i.RecurrenceEndDate,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedByUserID,
		&i.CreatedBySessionID,
		&i.CreatedByRole,
		&i.CreatedByCapability,
		&i.CreatedTrustedSurfaceKey,
		&i.CreatedTrustedSurfaceLabel,
		&i.UpdatedByUserID,
		&i.UpdatedBySessionID,
		&i.UpdatedByRole,
		&i.UpdatedByCapability,
		&i.UpdatedTrustedSurfaceKey,
		&i.UpdatedTrustedSurfaceLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CancelledBySessionID,
		&i.CancelledByRole,
		&i.CancelledByCapability,
		&i.CancelledTrustedSurfaceKey,
		&i.CancelledTrustedSurfaceLabel,
	)
	return i, err
}

const getScheduleResourceByKey = `-- name: GetScheduleResourceByKey :one
SELECT resource_key,
       facility_key,
       zone_key,
       resource_type,
       display_name,
       public_label,
       bookable,
       active,
       created_at,
       updated_at
FROM apollo.schedule_resources
WHERE resource_key = $1
LIMIT 1
`

func (q *Queries) GetScheduleResourceByKey(ctx context.Context, resourceKey string) (ApolloScheduleResource, error) {
	row := q.db.QueryRow(ctx, getScheduleResourceByKey, resourceKey)
	var i ApolloScheduleResource
	err := row.Scan(
		&i.ResourceKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ResourceType,
		&i.DisplayName,
		&i.PublicLabel,
		&i.Bookable,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScheduleBlockException = `-- name: InsertScheduleBlockException :one
INSERT INTO apollo.schedule_block_exceptions (
    schedule_block_id,
    exception_date,
    created_by_user_id,
    created_by_session_id,
    created_by_role,
    created_by_capability,
    created_trusted_surface_key,
    created_trusted_surface_label,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id,
          schedule_block_id,
          exception_date,
          created_by_user_id,
          created_by_session_id,
          created_by_role,
          created_by_capability,
          created_trusted_surface_key,
          created_trusted_surface_label,
          created_at
`

type InsertScheduleBlockExceptionParams struct {
	ScheduleBlockID            uuid.UUID
	ExceptionDate              pgtype.Date
	CreatedByUserID            uuid.UUID
	CreatedBySessionID         uuid.UUID
	CreatedByRole              string
	CreatedByCapability        string
	CreatedTrustedSurfaceKey   string
	CreatedTrustedSurfaceLabel *string
	CreatedAt                  pgtype.Timestamptz
}

func (q *Queries) InsertScheduleBlockException(ctx context.Context, arg InsertScheduleBlockExceptionParams) (ApolloScheduleBlockException, error) {
	row := q.db.QueryRow(ctx, insertScheduleBlockException,
		arg.ScheduleBlockID,
		arg.ExceptionDate,
		arg.CreatedByUserID,
		arg.CreatedBySessionID,
		arg.CreatedByRole,
		arg.CreatedByCapability,
		arg.CreatedTrustedSurfaceKey,
		arg.CreatedTrustedSurfaceLabel,
		arg.CreatedAt,
	)
	var i ApolloScheduleBlockException
	err := row.Scan(
		&i.ID,
		&i.ScheduleBlockID,
		&i.ExceptionDate,
		&i.CreatedByUserID,
		&i.CreatedBySessionID,
		&i.CreatedByRole,
		&i.CreatedByCapability,
		&i.CreatedTrustedSurfaceKey,
		&i.CreatedTrustedSurfaceLabel,
		&i.CreatedAt,
	)
	return i, err
}

const listScheduleBlockExceptionsByBlockIDs = `-- name: ListScheduleBlockExceptionsByBlockIDs :many
SELECT id,
       schedule_block_id,
       exception_date,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       created_at
FROM apollo.schedule_block_exceptions
WHERE schedule_block_id = ANY($1::uuid[])
ORDER BY schedule_block_id, exception_date
`

func (q *Queries) ListScheduleBlockExceptionsByBlockIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ApolloScheduleBlockException, error) {
	rows, err := q.db.Query(ctx, listScheduleBlockExceptionsByBlockIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloScheduleBlockException
	for rows.Next() {
		var i ApolloScheduleBlockException
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleBlockID,
			&i.ExceptionDate,
			&i.CreatedByUserID,
			&i.CreatedBySessionID,
			&i.CreatedByRole,
			&i.CreatedByCapability,
			&i.CreatedTrustedSurfaceKey,
			&i.CreatedTrustedSurfaceLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleBlocksByFacilityKey = `-- name: ListScheduleBlocksByFacilityKey :many
SELECT id,
       facility_key,
       zone_key,
       resource_key,
       scope,
       schedule_type,
       kind,
       effect,
       visibility,
       status,
       version,
       weekday,
       start_time,
       end_time,
       timezone,
       recurrence_start_date,
       recurrence_end_date,
       start_at,
       end_at,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       updated_by_user_id,
       updated_by_session_id,
       updated_by_role,
       updated_by_capability,
       updated_trusted_surface_key,
       updated_trusted_surface_label,
       created_at,
       updated_at,
       cancelled_at,
       cancelled_by_user_id,
       cancelled_by_session_id,
       cancelled_by_role,
       cancelled_by_capability,
       cancelled_trusted_surface_key,
       cancelled_trusted_surface_label
FROM apollo.schedule_blocks
WHERE facility_key = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListScheduleBlocksByFacilityKey(ctx context.Context, facilityKey string) ([]ApolloScheduleBlock, error) {
	rows, err := q.db.Query(ctx, listScheduleBlocksByFacilityKey, facilityKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloScheduleBlock
	for rows.Next() {
		var i ApolloScheduleBlock
		if err := rows.Scan(
			&i.ID,
			&i.FacilityKey,
			&i.ZoneKey,
			&i.ResourceKey,
			&i.Scope,
			&i.ScheduleType,
			&i.Kind,
			&i.Effect,
			&i.Visibility,
			&i.Status,
			&i.Version,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.RecurrenceStartDate,
			&i.RecurrenceEndDate,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedByUserID,
			&i.CreatedBySessionID,
			&i.CreatedByRole,
			&i.CreatedByCapability,
			&i.CreatedTrustedSurfaceKey,
			&i.CreatedTrustedSurfaceLabel,
			&i.UpdatedByUserID,
			&i.UpdatedBySessionID,
			&i.UpdatedByRole,
			&i.UpdatedByCapability,
			&i.UpdatedTrustedSurfaceKey,
			&i.UpdatedTrustedSurfaceLabel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
			&i.CancelledByUserID,
			&i.CancelledBySessionID,
			&i.CancelledByRole,
			&i.CancelledByCapability,
			&i.CancelledTrustedSurfaceKey,
			&i.CancelledTrustedSurfaceLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleResourceEdgesByFacilityKey = `-- name: ListScheduleResourceEdgesByFacilityKey :many
SELECT edge.resource_key,
       edge.related_resource_key,
       edge.edge_type,
       edge.created_at,
       edge.updated_at
FROM apollo.schedule_resource_edges AS edge
JOIN apollo.schedule_resources AS source_resource
  ON source_resource.resource_key = edge.resource_key
JOIN apollo.schedule_resources AS related_resource
  ON related_resource.resource_key = edge.related_resource_key
WHERE source_resource.facility_key = $1
  AND related_resource.facility_key = $1
ORDER BY edge.edge_type, edge.resource_key, edge.related_resource_key
`

func (q *Queries) ListScheduleResourceEdgesByFacilityKey(ctx context.Context, facilityKey string) ([]ApolloScheduleResourceEdge, error) {
	rows, err := q.db.Query(ctx, listScheduleResourceEdgesByFacilityKey, facilityKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloScheduleResourceEdge
	for rows.Next() {
		var i ApolloScheduleResourceEdge
		if err := rows.Scan(
			&i.ResourceKey,
			&i.RelatedResourceKey,
			&i.EdgeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleResourcesByFacilityKey = `-- name: ListScheduleResourcesByFacilityKey :many
SELECT resource_key,
       facility_key,
       zone_key,
       resource_type,
       display_name,
       public_label,
       bookable,
       active,
       created_at,
       updated_at
FROM apollo.schedule_resources
WHERE facility_key = $1
ORDER BY resource_key
`

func (q *Queries) ListScheduleResourcesByFacilityKey(ctx context.Context, facilityKey string) ([]ApolloScheduleResource, error) {
	rows, err := q.db.Query(ctx, listScheduleResourcesByFacilityKey, facilityKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloScheduleResource
	for rows.Next() {
		var i ApolloScheduleResource
		if err := rows.Scan(
			&i.ResourceKey,
			&i.FacilityKey,
			&i.ZoneKey,
			&i.ResourceType,
			&i.DisplayName,
			&i.PublicLabel,
			&i.Bookable,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScheduleResource = `-- name: UpsertScheduleResource :one
INSERT INTO apollo.schedule_resources (
    resource_key,
    facility_key,
    zone_key,
    resource_type,
    display_name,
    public_label,
    bookable,
    active,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (resource_key)
DO UPDATE SET
    facility_key = EXCLUDED.facility_key,
    zone_key = EXCLUDED.zone_key,
    resource_type = EXCLUDED.resource_type,
    display_name = EXCLUDED.display_name,
    public_label = EXCLUDED.public_label,
    bookable = EXCLUDED.bookable,
    active = EXCLUDED.active,
    updated_at = EXCLUDED.updated_at
RETURNING resource_key,
          facility_key,
          zone_key,
          resource_type,
          display_name,
          public_label,
          bookable,
          active,
          created_at,
          updated_at
`

type UpsertScheduleResourceParams struct {
	ResourceKey  string
	FacilityKey  string
	ZoneKey      *string
	ResourceType string
	DisplayName  string
	PublicLabel  *string
	Bookable     bool
	Active       bool
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertScheduleResource(ctx context.Context, arg UpsertScheduleResourceParams) (ApolloScheduleResource, error) {
	row := q.db.QueryRow(ctx, upsertScheduleResource,
		arg.ResourceKey,
		arg.FacilityKey,
		arg.ZoneKey,
		arg.ResourceType,
		arg.DisplayName,
		arg.PublicLabel,
		arg.Bookable,
		arg.Active,
		arg.UpdatedAt,
	)
	var i ApolloScheduleResource
	err := row.Scan(
		&i.ResourceKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ResourceType,
		&i.DisplayName,
		&i.PublicLabel,
		&i.Bookable,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScheduleResourceEdge = `-- name: UpsertScheduleResourceEdge :one
INSERT INTO apollo.schedule_resource_edges (
    resource_key,
    related_resource_key,
    edge_type,
    updated_at
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (resource_key, related_resource_key, edge_type)
DO UPDATE SET updated_at = EXCLUDED.updated_at
RETURNING resource_key,
          related_resource_key,
          edge_type,
          created_at,
          updated_at
`

type UpsertScheduleResourceEdgeParams struct {
	ResourceKey        string
	RelatedResourceKey string
	EdgeType           string
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertScheduleResourceEdge(ctx context.Context, arg UpsertScheduleResourceEdgeParams) (ApolloScheduleResourceEdge, error) {
	row := q.db.QueryRow(ctx, upsertScheduleResourceEdge,
		arg.ResourceKey,
		arg.RelatedResourceKey,
		arg.EdgeType,
		arg.UpdatedAt,
	)
	var i ApolloScheduleResourceEdge
	err := row.Scan(
		&i.ResourceKey,
		&i.RelatedResourceKey,
		&i.EdgeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
