// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sports.sql

package store

import (
	"context"
)

const facilityCatalogRefExists = `-- name: FacilityCatalogRefExists :one
SELECT EXISTS (
    SELECT 1
    FROM apollo.facility_catalog_refs
    WHERE facility_key = $1
)
`

func (q *Queries) FacilityCatalogRefExists(ctx context.Context, facilityKey string) (bool, error) {
	row := q.db.QueryRow(ctx, facilityCatalogRefExists, facilityKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSportByKey = `-- name: GetSportByKey :one
SELECT sport_key,
       display_name,
       description,
       competition_mode,
       sides_per_match,
       participants_per_side_min,
       participants_per_side_max,
       scoring_model,
       default_match_duration_minutes,
       rules_summary
FROM apollo.sports
WHERE sport_key = $1
LIMIT 1
`

func (q *Queries) GetSportByKey(ctx context.Context, sportKey string) (ApolloSport, error) {
	row := q.db.QueryRow(ctx, getSportByKey, sportKey)
	var i ApolloSport
	err := row.Scan(
		&i.SportKey,
		&i.DisplayName,
		&i.Description,
		&i.CompetitionMode,
		&i.SidesPerMatch,
		&i.ParticipantsPerSideMin,
		&i.ParticipantsPerSideMax,
		&i.ScoringModel,
		&i.DefaultMatchDurationMinutes,
		&i.RulesSummary,
	)
	return i, err
}

const listFacilityCatalogRefs = `-- name: ListFacilityCatalogRefs :many
SELECT facility_key
FROM apollo.facility_catalog_refs
ORDER BY facility_key
`

func (q *Queries) ListFacilityCatalogRefs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listFacilityCatalogRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var facility_key string
		if err := rows.Scan(&facility_key); err != nil {
			return nil, err
		}
		items = append(items, facility_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportFacilityCapabilities = `-- name: ListSportFacilityCapabilities :many
SELECT c.sport_key,
       c.facility_key,
       z.zone_key
FROM apollo.sport_facility_capabilities AS c
LEFT JOIN apollo.sport_facility_capability_zones AS z
  ON z.sport_key = c.sport_key
 AND z.facility_key = c.facility_key
ORDER BY c.sport_key, c.facility_key, z.zone_key
`

type ListSportFacilityCapabilitiesRow struct {
	SportKey    string
	FacilityKey string
	ZoneKey     *string
}

func (q *Queries) ListSportFacilityCapabilities(ctx context.Context) ([]ListSportFacilityCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listSportFacilityCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSportFacilityCapabilitiesRow
	for rows.Next() {
		var i ListSportFacilityCapabilitiesRow
		if err := rows.Scan(&i.SportKey, &i.FacilityKey, &i.ZoneKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSports = `-- name: ListSports :many
SELECT sport_key,
       display_name,
       description,
       competition_mode,
       sides_per_match,
       participants_per_side_min,
       participants_per_side_max,
       scoring_model,
       default_match_duration_minutes,
       rules_summary
FROM apollo.sports
ORDER BY sport_key
`

func (q *Queries) ListSports(ctx context.Context) ([]ApolloSport, error) {
	rows, err := q.db.Query(ctx, listSports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloSport
	for rows.Next() {
		var i ApolloSport
		if err := rows.Scan(
			&i.SportKey,
			&i.DisplayName,
			&i.Description,
			&i.CompetitionMode,
			&i.SidesPerMatch,
			&i.ParticipantsPerSideMin,
			&i.ParticipantsPerSideMax,
			&i.ScoringModel,
			&i.DefaultMatchDurationMinutes,
			&i.RulesSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
