// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournament.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompetitionTournamentSeedsByBracketID = `-- name: CountCompetitionTournamentSeedsByBracketID :one
SELECT count(*)
FROM apollo.competition_tournament_seeds
WHERE bracket_id = $1
`

func (q *Queries) CountCompetitionTournamentSeedsByBracketID(ctx context.Context, bracketID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetitionTournamentSeedsByBracketID, bracketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompetitionTournamentTeamSnapshotsByBracketID = `-- name: CountCompetitionTournamentTeamSnapshotsByBracketID :one
SELECT count(*)
FROM apollo.competition_tournament_team_snapshots
WHERE bracket_id = $1
`

func (q *Queries) CountCompetitionTournamentTeamSnapshotsByBracketID(ctx context.Context, bracketID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetitionTournamentTeamSnapshotsByBracketID, bracketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompetitionTournament = `-- name: CreateCompetitionTournament :one
INSERT INTO apollo.competition_tournaments (
  owner_user_id,
  display_name,
  format,
  sport_key,
  facility_key,
  zone_key,
  participants_per_side,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id,
          owner_user_id,
          display_name,
          format,
          visibility,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          status,
          tournament_version,
          created_at,
          updated_at,
          archived_at
`

type CreateCompetitionTournamentParams struct {
	OwnerUserID         uuid.UUID
	DisplayName         string
	Format              string
	SportKey            string
	FacilityKey         string
	ZoneKey             *string
	ParticipantsPerSide int32
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionTournament(ctx context.Context, arg CreateCompetitionTournamentParams) (ApolloCompetitionTournament, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournament,
		arg.OwnerUserID,
		arg.DisplayName,
		arg.Format,
		arg.SportKey,
		arg.FacilityKey,
		arg.ZoneKey,
		arg.ParticipantsPerSide,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionTournament
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Format,
		&i.Visibility,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.Status,
		&i.TournamentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createCompetitionTournamentAdvancement = `-- name: CreateCompetitionTournamentAdvancement :one
INSERT INTO apollo.competition_tournament_advancements (
  tournament_id,
  bracket_id,
  match_binding_id,
  round,
  winning_team_snapshot_id,
  losing_team_snapshot_id,
  competition_match_id,
  canonical_result_id,
  advance_reason,
  advanced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id,
          tournament_id,
          bracket_id,
          match_binding_id,
          round,
          winning_team_snapshot_id,
          losing_team_snapshot_id,
          competition_match_id,
          canonical_result_id,
          advance_reason,
          advanced_at,
          created_at
`

type CreateCompetitionTournamentAdvancementParams struct {
	TournamentID          uuid.UUID
	BracketID             uuid.UUID
	MatchBindingID        uuid.UUID
	Round                 int32
	WinningTeamSnapshotID uuid.UUID
	LosingTeamSnapshotID  uuid.UUID
	CompetitionMatchID    uuid.UUID
	CanonicalResultID     uuid.UUID
	AdvanceReason         string
	AdvancedAt            pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionTournamentAdvancement(ctx context.Context, arg CreateCompetitionTournamentAdvancementParams) (ApolloCompetitionTournamentAdvancement, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournamentAdvancement,
		arg.TournamentID,
		arg.BracketID,
		arg.MatchBindingID,
		arg.Round,
		arg.WinningTeamSnapshotID,
		arg.LosingTeamSnapshotID,
		arg.CompetitionMatchID,
		arg.CanonicalResultID,
		arg.AdvanceReason,
		arg.AdvancedAt,
	)
	var i ApolloCompetitionTournamentAdvancement
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.MatchBindingID,
		&i.Round,
		&i.WinningTeamSnapshotID,
		&i.LosingTeamSnapshotID,
		&i.CompetitionMatchID,
		&i.CanonicalResultID,
		&i.AdvanceReason,
		&i.AdvancedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionTournamentBracket = `-- name: CreateCompetitionTournamentBracket :one
INSERT INTO apollo.competition_tournament_brackets (
  tournament_id,
  bracket_index,
  format,
  status,
  updated_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id,
          tournament_id,
          bracket_index,
          format,
          status,
          created_at,
          updated_at
`

type CreateCompetitionTournamentBracketParams struct {
	TournamentID uuid.UUID
	BracketIndex int32
	Format       string
	Status       string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionTournamentBracket(ctx context.Context, arg CreateCompetitionTournamentBracketParams) (ApolloCompetitionTournamentBracket, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournamentBracket,
		arg.TournamentID,
		arg.BracketIndex,
		arg.Format,
		arg.Status,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionTournamentBracket
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketIndex,
		&i.Format,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompetitionTournamentEvent = `-- name: CreateCompetitionTournamentEvent :one
INSERT INTO apollo.competition_tournament_events (
  tournament_id,
  bracket_id,
  event_type,
  tournament_seed_id,
  team_snapshot_id,
  match_binding_id,
  round,
  seed,
  advance_reason,
  competition_session_team_id,
  competition_match_id,
  canonical_result_id,
  actor_user_id,
  actor_role,
  actor_session_id,
  capability,
  trusted_surface_key,
  trusted_surface_label,
  occurred_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, $19
)
RETURNING id,
          tournament_id,
          bracket_id,
          event_type,
          tournament_seed_id,
          team_snapshot_id,
          match_binding_id,
          round,
          seed,
          advance_reason,
          competition_session_team_id,
          competition_match_id,
          canonical_result_id,
          actor_user_id,
          actor_role,
          actor_session_id,
          capability,
          trusted_surface_key,
          trusted_surface_label,
          occurred_at,
          created_at
`

type CreateCompetitionTournamentEventParams struct {
	TournamentID             uuid.UUID
	BracketID                pgtype.UUID
	EventType                string
	TournamentSeedID         pgtype.UUID
	TeamSnapshotID           pgtype.UUID
	MatchBindingID           pgtype.UUID
	Round                    *int32
	Seed                     *int32
	AdvanceReason            *string
	CompetitionSessionTeamID pgtype.UUID
	CompetitionMatchID       pgtype.UUID
	CanonicalResultID        pgtype.UUID
	ActorUserID              pgtype.UUID
	ActorRole                *string
	ActorSessionID           pgtype.UUID
	Capability               *string
	TrustedSurfaceKey        *string
	TrustedSurfaceLabel      *string
	OccurredAt               pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionTournamentEvent(ctx context.Context, arg CreateCompetitionTournamentEventParams) (ApolloCompetitionTournamentEvent, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournamentEvent,
		arg.TournamentID,
		arg.BracketID,
		arg.EventType,
		arg.TournamentSeedID,
		arg.TeamSnapshotID,
		arg.MatchBindingID,
		arg.Round,
		arg.Seed,
		arg.AdvanceReason,
		arg.CompetitionSessionTeamID,
		arg.CompetitionMatchID,
		arg.CanonicalResultID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorSessionID,
		arg.Capability,
		arg.TrustedSurfaceKey,
		arg.TrustedSurfaceLabel,
		arg.OccurredAt,
	)
	var i ApolloCompetitionTournamentEvent
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.EventType,
		&i.TournamentSeedID,
		&i.TeamSnapshotID,
		&i.MatchBindingID,
		&i.Round,
		&i.Seed,
		&i.AdvanceReason,
		&i.CompetitionSessionTeamID,
		&i.CompetitionMatchID,
		&i.CanonicalResultID,
		&i.ActorUserID,
		&i.ActorRole,
		&i.ActorSessionID,
		&i.Capability,
		&i.TrustedSurfaceKey,
		&i.TrustedSurfaceLabel,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionTournamentMatchBinding = `-- name: CreateCompetitionTournamentMatchBinding :one
INSERT INTO apollo.competition_tournament_match_bindings (
  tournament_id,
  bracket_id,
  round,
  match_number,
  competition_match_id,
  side_one_team_snapshot_id,
  side_two_team_snapshot_id,
  bound_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id,
          tournament_id,
          bracket_id,
          round,
          match_number,
          competition_match_id,
          side_one_team_snapshot_id,
          side_two_team_snapshot_id,
          bound_at,
          created_at
`

type CreateCompetitionTournamentMatchBindingParams struct {
	TournamentID          uuid.UUID
	BracketID             uuid.UUID
	Round                 int32
	MatchNumber           int32
	CompetitionMatchID    uuid.UUID
	SideOneTeamSnapshotID uuid.UUID
	SideTwoTeamSnapshotID uuid.UUID
	BoundAt               pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionTournamentMatchBinding(ctx context.Context, arg CreateCompetitionTournamentMatchBindingParams) (ApolloCompetitionTournamentMatchBinding, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournamentMatchBinding,
		arg.TournamentID,
		arg.BracketID,
		arg.Round,
		arg.MatchNumber,
		arg.CompetitionMatchID,
		arg.SideOneTeamSnapshotID,
		arg.SideTwoTeamSnapshotID,
		arg.BoundAt,
	)
	var i ApolloCompetitionTournamentMatchBinding
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.Round,
		&i.MatchNumber,
		&i.CompetitionMatchID,
		&i.SideOneTeamSnapshotID,
		&i.SideTwoTeamSnapshotID,
		&i.BoundAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionTournamentSeed = `-- name: CreateCompetitionTournamentSeed :one
INSERT INTO apollo.competition_tournament_seeds (
  tournament_id,
  bracket_id,
  seed,
  competition_session_team_id,
  seeded_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id,
          tournament_id,
          bracket_id,
          seed,
          competition_session_team_id,
          seeded_at,
          created_at
`

type CreateCompetitionTournamentSeedParams struct {
	TournamentID             uuid.UUID
	BracketID                uuid.UUID
	Seed                     int32
	CompetitionSessionTeamID uuid.UUID
	SeededAt                 pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionTournamentSeed(ctx context.Context, arg CreateCompetitionTournamentSeedParams) (ApolloCompetitionTournamentSeed, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournamentSeed,
		arg.TournamentID,
		arg.BracketID,
		arg.Seed,
		arg.CompetitionSessionTeamID,
		arg.SeededAt,
	)
	var i ApolloCompetitionTournamentSeed
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.Seed,
		&i.CompetitionSessionTeamID,
		&i.SeededAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionTournamentTeamSnapshot = `-- name: CreateCompetitionTournamentTeamSnapshot :one
INSERT INTO apollo.competition_tournament_team_snapshots (
  tournament_id,
  bracket_id,
  tournament_seed_id,
  seed,
  competition_session_id,
  competition_session_team_id,
  roster_hash,
  locked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id,
          tournament_id,
          bracket_id,
          tournament_seed_id,
          seed,
          competition_session_id,
          competition_session_team_id,
          roster_hash,
          locked_at,
          created_at
`

type CreateCompetitionTournamentTeamSnapshotParams struct {
	TournamentID             uuid.UUID
	BracketID                uuid.UUID
	TournamentSeedID         uuid.UUID
	Seed                     int32
	CompetitionSessionID     uuid.UUID
	CompetitionSessionTeamID uuid.UUID
	RosterHash               string
	LockedAt                 pgtype.Timestamptz
}

func (q *Queries) CreateCompetitionTournamentTeamSnapshot(ctx context.Context, arg CreateCompetitionTournamentTeamSnapshotParams) (ApolloCompetitionTournamentTeamSnapshot, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournamentTeamSnapshot,
		arg.TournamentID,
		arg.BracketID,
		arg.TournamentSeedID,
		arg.Seed,
		arg.CompetitionSessionID,
		arg.CompetitionSessionTeamID,
		arg.RosterHash,
		arg.LockedAt,
	)
	var i ApolloCompetitionTournamentTeamSnapshot
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.TournamentSeedID,
		&i.Seed,
		&i.CompetitionSessionID,
		&i.CompetitionSessionTeamID,
		&i.RosterHash,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionTournamentTeamSnapshotMember = `-- name: CreateCompetitionTournamentTeamSnapshotMember :one
INSERT INTO apollo.competition_tournament_team_snapshot_members (
  team_snapshot_id,
  user_id,
  display_name,
  slot_index
)
VALUES ($1, $2, $3, $4)
RETURNING team_snapshot_id,
          user_id,
          display_name,
          slot_index,
          created_at
`

type CreateCompetitionTournamentTeamSnapshotMemberParams struct {
	TeamSnapshotID uuid.UUID
	UserID         uuid.UUID
	DisplayName    string
	SlotIndex      int32
}

func (q *Queries) CreateCompetitionTournamentTeamSnapshotMember(ctx context.Context, arg CreateCompetitionTournamentTeamSnapshotMemberParams) (ApolloCompetitionTournamentTeamSnapshotMember, error) {
	row := q.db.QueryRow(ctx, createCompetitionTournamentTeamSnapshotMember,
		arg.TeamSnapshotID,
		arg.UserID,
		arg.DisplayName,
		arg.SlotIndex,
	)
	var i ApolloCompetitionTournamentTeamSnapshotMember
	err := row.Scan(
		&i.TeamSnapshotID,
		&i.UserID,
		&i.DisplayName,
		&i.SlotIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getCompetitionTournamentByID = `-- name: GetCompetitionTournamentByID :one
SELECT id,
       owner_user_id,
       display_name,
       format,
       visibility,
       sport_key,
       facility_key,
       zone_key,
       participants_per_side,
       status,
       tournament_version,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_tournaments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompetitionTournamentByID(ctx context.Context, id uuid.UUID) (ApolloCompetitionTournament, error) {
	row := q.db.QueryRow(ctx, getCompetitionTournamentByID, id)
	var i ApolloCompetitionTournament
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Format,
		&i.Visibility,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.Status,
		&i.TournamentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCompetitionTournamentMatchBindingByID = `-- name: GetCompetitionTournamentMatchBindingByID :one
SELECT id,
       tournament_id,
       bracket_id,
       round,
       match_number,
       competition_match_id,
       side_one_team_snapshot_id,
       side_two_team_snapshot_id,
       bound_at,
       created_at
FROM apollo.competition_tournament_match_bindings
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompetitionTournamentMatchBindingByID(ctx context.Context, id uuid.UUID) (ApolloCompetitionTournamentMatchBinding, error) {
	row := q.db.QueryRow(ctx, getCompetitionTournamentMatchBindingByID, id)
	var i ApolloCompetitionTournamentMatchBinding
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.Round,
		&i.MatchNumber,
		&i.CompetitionMatchID,
		&i.SideOneTeamSnapshotID,
		&i.SideTwoTeamSnapshotID,
		&i.BoundAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCompetitionTournamentSeedByBracketSeed = `-- name: GetCompetitionTournamentSeedByBracketSeed :one
SELECT id,
       tournament_id,
       bracket_id,
       seed,
       competition_session_team_id,
       seeded_at,
       created_at
FROM apollo.competition_tournament_seeds
WHERE bracket_id = $1
  AND seed = $2
LIMIT 1
`

type GetCompetitionTournamentSeedByBracketSeedParams struct {
	BracketID uuid.UUID
	Seed      int32
}

func (q *Queries) GetCompetitionTournamentSeedByBracketSeed(ctx context.Context, arg GetCompetitionTournamentSeedByBracketSeedParams) (ApolloCompetitionTournamentSeed, error) {
	row := q.db.QueryRow(ctx, getCompetitionTournamentSeedByBracketSeed, arg.BracketID, arg.Seed)
	var i ApolloCompetitionTournamentSeed
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.Seed,
		&i.CompetitionSessionTeamID,
		&i.SeededAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCompetitionTournamentTeamSnapshotByID = `-- name: GetCompetitionTournamentTeamSnapshotByID :one
SELECT id,
       tournament_id,
       bracket_id,
       tournament_seed_id,
       seed,
       competition_session_id,
       competition_session_team_id,
       roster_hash,
       locked_at,
       created_at
FROM apollo.competition_tournament_team_snapshots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompetitionTournamentTeamSnapshotByID(ctx context.Context, id uuid.UUID) (ApolloCompetitionTournamentTeamSnapshot, error) {
	row := q.db.QueryRow(ctx, getCompetitionTournamentTeamSnapshotByID, id)
	var i ApolloCompetitionTournamentTeamSnapshot
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketID,
		&i.TournamentSeedID,
		&i.Seed,
		&i.CompetitionSessionID,
		&i.CompetitionSessionTeamID,
		&i.RosterHash,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCompetitionMatchResultSidesByResultID = `-- name: ListCompetitionMatchResultSidesByResultID :many
SELECT competition_match_result_id,
       competition_match_id,
       side_index,
       competition_session_team_id,
       outcome
FROM apollo.competition_match_result_sides
WHERE competition_match_result_id = $1
ORDER BY side_index ASC
`

type ListCompetitionMatchResultSidesByResultIDRow struct {
	CompetitionMatchResultID uuid.UUID
	CompetitionMatchID       uuid.UUID
	SideIndex                int32
	CompetitionSessionTeamID uuid.UUID
	Outcome                  string
}

func (q *Queries) ListCompetitionMatchResultSidesByResultID(ctx context.Context, competitionMatchResultID uuid.UUID) ([]ListCompetitionMatchResultSidesByResultIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchResultSidesByResultID, competitionMatchResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionMatchResultSidesByResultIDRow
	for rows.Next() {
		var i ListCompetitionMatchResultSidesByResultIDRow
		if err := rows.Scan(
			&i.CompetitionMatchResultID,
			&i.CompetitionMatchID,
			&i.SideIndex,
			&i.CompetitionSessionTeamID,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTournamentAdvancementsByBracketID = `-- name: ListCompetitionTournamentAdvancementsByBracketID :many
SELECT id,
       tournament_id,
       bracket_id,
       match_binding_id,
       round,
       winning_team_snapshot_id,
       losing_team_snapshot_id,
       competition_match_id,
       canonical_result_id,
       advance_reason,
       advanced_at,
       created_at
FROM apollo.competition_tournament_advancements
WHERE bracket_id = $1
ORDER BY round ASC, advanced_at ASC, id ASC
`

func (q *Queries) ListCompetitionTournamentAdvancementsByBracketID(ctx context.Context, bracketID uuid.UUID) ([]ApolloCompetitionTournamentAdvancement, error) {
	rows, err := q.db.Query(ctx, listCompetitionTournamentAdvancementsByBracketID, bracketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionTournamentAdvancement
	for rows.Next() {
		var i ApolloCompetitionTournamentAdvancement
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.BracketID,
			&i.MatchBindingID,
			&i.Round,
			&i.WinningTeamSnapshotID,
			&i.LosingTeamSnapshotID,
			&i.CompetitionMatchID,
			&i.CanonicalResultID,
			&i.AdvanceReason,
			&i.AdvancedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTournamentBracketsByTournamentID = `-- name: ListCompetitionTournamentBracketsByTournamentID :many
SELECT id,
       tournament_id,
       bracket_index,
       format,
       status,
       created_at,
       updated_at
FROM apollo.competition_tournament_brackets
WHERE tournament_id = $1
ORDER BY bracket_index ASC, id ASC
`

func (q *Queries) ListCompetitionTournamentBracketsByTournamentID(ctx context.Context, tournamentID uuid.UUID) ([]ApolloCompetitionTournamentBracket, error) {
	rows, err := q.db.Query(ctx, listCompetitionTournamentBracketsByTournamentID, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionTournamentBracket
	for rows.Next() {
		var i ApolloCompetitionTournamentBracket
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.BracketIndex,
			&i.Format,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTournamentMatchBindingsByBracketID = `-- name: ListCompetitionTournamentMatchBindingsByBracketID :many
SELECT id,
       tournament_id,
       bracket_id,
       round,
       match_number,
       competition_match_id,
       side_one_team_snapshot_id,
       side_two_team_snapshot_id,
       bound_at,
       created_at
FROM apollo.competition_tournament_match_bindings
WHERE bracket_id = $1
ORDER BY round ASC, match_number ASC, id ASC
`

func (q *Queries) ListCompetitionTournamentMatchBindingsByBracketID(ctx context.Context, bracketID uuid.UUID) ([]ApolloCompetitionTournamentMatchBinding, error) {
	rows, err := q.db.Query(ctx, listCompetitionTournamentMatchBindingsByBracketID, bracketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionTournamentMatchBinding
	for rows.Next() {
		var i ApolloCompetitionTournamentMatchBinding
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.BracketID,
			&i.Round,
			&i.MatchNumber,
			&i.CompetitionMatchID,
			&i.SideOneTeamSnapshotID,
			&i.SideTwoTeamSnapshotID,
			&i.BoundAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTournamentSeedsByBracketID = `-- name: ListCompetitionTournamentSeedsByBracketID :many
SELECT id,
       tournament_id,
       bracket_id,
       seed,
       competition_session_team_id,
       seeded_at,
       created_at
FROM apollo.competition_tournament_seeds
WHERE bracket_id = $1
ORDER BY seed ASC, id ASC
`

func (q *Queries) ListCompetitionTournamentSeedsByBracketID(ctx context.Context, bracketID uuid.UUID) ([]ApolloCompetitionTournamentSeed, error) {
	rows, err := q.db.Query(ctx, listCompetitionTournamentSeedsByBracketID, bracketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionTournamentSeed
	for rows.Next() {
		var i ApolloCompetitionTournamentSeed
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.BracketID,
			&i.Seed,
			&i.CompetitionSessionTeamID,
			&i.SeededAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTournamentTeamSnapshotMembersByBracketID = `-- name: ListCompetitionTournamentTeamSnapshotMembersByBracketID :many
SELECT m.team_snapshot_id,
       m.user_id,
       m.display_name,
       m.slot_index,
       m.created_at
FROM apollo.competition_tournament_team_snapshot_members AS m
INNER JOIN apollo.competition_tournament_team_snapshots AS s
  ON s.id = m.team_snapshot_id
WHERE s.bracket_id = $1
ORDER BY s.seed ASC, m.slot_index ASC, m.user_id ASC
`

func (q *Queries) ListCompetitionTournamentTeamSnapshotMembersByBracketID(ctx context.Context, bracketID uuid.UUID) ([]ApolloCompetitionTournamentTeamSnapshotMember, error) {
	rows, err := q.db.Query(ctx, listCompetitionTournamentTeamSnapshotMembersByBracketID, bracketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionTournamentTeamSnapshotMember
	for rows.Next() {
		var i ApolloCompetitionTournamentTeamSnapshotMember
		if err := rows.Scan(
			&i.TeamSnapshotID,
			&i.UserID,
			&i.DisplayName,
			&i.SlotIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTournamentTeamSnapshotsByBracketID = `-- name: ListCompetitionTournamentTeamSnapshotsByBracketID :many
SELECT id,
       tournament_id,
       bracket_id,
       tournament_seed_id,
       seed,
       competition_session_id,
       competition_session_team_id,
       roster_hash,
       locked_at,
       created_at
FROM apollo.competition_tournament_team_snapshots
WHERE bracket_id = $1
ORDER BY seed ASC, id ASC
`

func (q *Queries) ListCompetitionTournamentTeamSnapshotsByBracketID(ctx context.Context, bracketID uuid.UUID) ([]ApolloCompetitionTournamentTeamSnapshot, error) {
	rows, err := q.db.Query(ctx, listCompetitionTournamentTeamSnapshotsByBracketID, bracketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionTournamentTeamSnapshot
	for rows.Next() {
		var i ApolloCompetitionTournamentTeamSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.BracketID,
			&i.TournamentSeedID,
			&i.Seed,
			&i.CompetitionSessionID,
			&i.CompetitionSessionTeamID,
			&i.RosterHash,
			&i.LockedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionTournaments = `-- name: ListCompetitionTournaments :many
SELECT id,
       owner_user_id,
       display_name,
       format,
       visibility,
       sport_key,
       facility_key,
       zone_key,
       participants_per_side,
       status,
       tournament_version,
       created_at,
       updated_at,
       archived_at
FROM apollo.competition_tournaments
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCompetitionTournaments(ctx context.Context) ([]ApolloCompetitionTournament, error) {
	rows, err := q.db.Query(ctx, listCompetitionTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloCompetitionTournament
	for rows.Next() {
		var i ApolloCompetitionTournament
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.DisplayName,
			&i.Format,
			&i.Visibility,
			&i.SportKey,
			&i.FacilityKey,
			&i.ZoneKey,
			&i.ParticipantsPerSide,
			&i.Status,
			&i.TournamentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetitionTournamentBracketStatus = `-- name: UpdateCompetitionTournamentBracketStatus :one
UPDATE apollo.competition_tournament_brackets
SET status = $3,
    updated_at = $4
WHERE id = $1
  AND tournament_id = $2
RETURNING id,
          tournament_id,
          bracket_index,
          format,
          status,
          created_at,
          updated_at
`

type UpdateCompetitionTournamentBracketStatusParams struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
	Status       string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionTournamentBracketStatus(ctx context.Context, arg UpdateCompetitionTournamentBracketStatusParams) (ApolloCompetitionTournamentBracket, error) {
	row := q.db.QueryRow(ctx, updateCompetitionTournamentBracketStatus,
		arg.ID,
		arg.TournamentID,
		arg.Status,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionTournamentBracket
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.BracketIndex,
		&i.Format,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompetitionTournamentStatusWithVersion = `-- name: UpdateCompetitionTournamentStatusWithVersion :one
UPDATE apollo.competition_tournaments
SET status = $3,
    tournament_version = tournament_version + 1,
    updated_at = $4
WHERE id = $1
  AND tournament_version = $2
RETURNING id,
          owner_user_id,
          display_name,
          format,
          visibility,
          sport_key,
          facility_key,
          zone_key,
          participants_per_side,
          status,
          tournament_version,
          created_at,
          updated_at,
          archived_at
`

type UpdateCompetitionTournamentStatusWithVersionParams struct {
	ID                uuid.UUID
	TournamentVersion int32
	Status            string
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpdateCompetitionTournamentStatusWithVersion(ctx context.Context, arg UpdateCompetitionTournamentStatusWithVersionParams) (ApolloCompetitionTournament, error) {
	row := q.db.QueryRow(ctx, updateCompetitionTournamentStatusWithVersion,
		arg.ID,
		arg.TournamentVersion,
		arg.Status,
		arg.UpdatedAt,
	)
	var i ApolloCompetitionTournament
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Format,
		&i.Visibility,
		&i.SportKey,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.ParticipantsPerSide,
		&i.Status,
		&i.TournamentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
