// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: visits.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVisit = `-- name: CreateVisit :one
INSERT INTO apollo.visits (
  user_id,
  facility_key,
  zone_key,
  source_event_id,
  arrived_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, facility_key, zone_key, source_event_id, arrived_at, departed_at, metadata
`

type CreateVisitParams struct {
	UserID        uuid.UUID
	FacilityKey   string
	ZoneKey       *string
	SourceEventID *string
	ArrivedAt     pgtype.Timestamptz
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (ApolloVisit, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.UserID,
		arg.FacilityKey,
		arg.ZoneKey,
		arg.SourceEventID,
		arg.ArrivedAt,
	)
	var i ApolloVisit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.SourceEventID,
		&i.ArrivedAt,
		&i.DepartedAt,
		&i.Metadata,
	)
	return i, err
}

const getActiveUserByTagHash = `-- name: GetActiveUserByTagHash :one
SELECT u.id, u.student_id, u.display_name, u.email, u.preferences, u.created_at
FROM apollo.claimed_tags AS ct
JOIN apollo.users AS u ON u.id = ct.user_id
WHERE ct.tag_hash = $1
  AND ct.is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveUserByTagHash(ctx context.Context, tagHash string) (ApolloUser, error) {
	row := q.db.QueryRow(ctx, getActiveUserByTagHash, tagHash)
	var i ApolloUser
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisplayName,
		&i.Email,
		&i.Preferences,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenVisitByUserAndFacility = `-- name: GetOpenVisitByUserAndFacility :one
SELECT v.id, v.user_id, v.facility_key, v.zone_key, v.source_event_id, v.arrived_at, v.departed_at, v.metadata
FROM apollo.visits AS v
WHERE user_id = $1
  AND facility_key = $2
  AND departed_at IS NULL
ORDER BY arrived_at DESC
LIMIT 1
`

type GetOpenVisitByUserAndFacilityParams struct {
	UserID      uuid.UUID
	FacilityKey string
}

func (q *Queries) GetOpenVisitByUserAndFacility(ctx context.Context, arg GetOpenVisitByUserAndFacilityParams) (ApolloVisit, error) {
	row := q.db.QueryRow(ctx, getOpenVisitByUserAndFacility, arg.UserID, arg.FacilityKey)
	var i ApolloVisit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.SourceEventID,
		&i.ArrivedAt,
		&i.DepartedAt,
		&i.Metadata,
	)
	return i, err
}

const getVisitBySourceEventID = `-- name: GetVisitBySourceEventID :one
SELECT v.id, v.user_id, v.facility_key, v.zone_key, v.source_event_id, v.arrived_at, v.departed_at, v.metadata
FROM apollo.visits AS v
WHERE source_event_id = $1
LIMIT 1
`

func (q *Queries) GetVisitBySourceEventID(ctx context.Context, sourceEventID *string) (ApolloVisit, error) {
	row := q.db.QueryRow(ctx, getVisitBySourceEventID, sourceEventID)
	var i ApolloVisit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityKey,
		&i.ZoneKey,
		&i.SourceEventID,
		&i.ArrivedAt,
		&i.DepartedAt,
		&i.Metadata,
	)
	return i, err
}

const listVisitsByStudentID = `-- name: ListVisitsByStudentID :many
SELECT v.id, v.user_id, v.facility_key, v.zone_key, v.source_event_id, v.arrived_at, v.departed_at, v.metadata
FROM apollo.visits AS v
JOIN apollo.users AS u ON u.id = v.user_id
WHERE u.student_id = $1
ORDER BY v.arrived_at DESC
`

func (q *Queries) ListVisitsByStudentID(ctx context.Context, studentID string) ([]ApolloVisit, error) {
	rows, err := q.db.Query(ctx, listVisitsByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloVisit
	for rows.Next() {
		var i ApolloVisit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FacilityKey,
			&i.ZoneKey,
			&i.SourceEventID,
			&i.ArrivedAt,
			&i.DepartedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
