// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExercisesByWorkoutID = `-- name: CountExercisesByWorkoutID :one
SELECT count(*)
FROM apollo.exercises
WHERE workout_id = $1
`

func (q *Queries) CountExercisesByWorkoutID(ctx context.Context, workoutID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExercisesByWorkoutID, workoutID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO apollo.exercises (
  workout_id,
  position,
  name,
  sets,
  reps,
  weight_kg,
  rpe,
  notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workout_id, position, name, sets, reps, weight_kg, rpe, notes
`

type CreateExerciseParams struct {
	WorkoutID uuid.UUID
	Position  int32
	Name      string
	Sets      int32
	Reps      int32
	WeightKg  pgtype.Numeric
	Rpe       pgtype.Numeric
	Notes     *string
}

type CreateExerciseRow struct {
	ID        uuid.UUID
	WorkoutID uuid.UUID
	Position  int32
	Name      string
	Sets      int32
	Reps      int32
	WeightKg  pgtype.Numeric
	Rpe       pgtype.Numeric
	Notes     *string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (CreateExerciseRow, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.WorkoutID,
		arg.Position,
		arg.Name,
		arg.Sets,
		arg.Reps,
		arg.WeightKg,
		arg.Rpe,
		arg.Notes,
	)
	var i CreateExerciseRow
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.Position,
		&i.Name,
		&i.Sets,
		&i.Reps,
		&i.WeightKg,
		&i.Rpe,
		&i.Notes,
	)
	return i, err
}

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO apollo.workouts (
  user_id,
  notes,
  metadata
)
VALUES ($1, $2, $3)
RETURNING id, user_id, started_at, status, finished_at, notes, metadata
`

type CreateWorkoutParams struct {
	UserID   uuid.UUID
	Notes    *string
	Metadata []byte
}

type CreateWorkoutRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	StartedAt  pgtype.Timestamptz
	Status     string
	FinishedAt pgtype.Timestamptz
	Notes      *string
	Metadata   []byte
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (CreateWorkoutRow, error) {
	row := q.db.QueryRow(ctx, createWorkout, arg.UserID, arg.Notes, arg.Metadata)
	var i CreateWorkoutRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.Status,
		&i.FinishedAt,
		&i.Notes,
		&i.Metadata,
	)
	return i, err
}

const deleteExercisesByWorkoutID = `-- name: DeleteExercisesByWorkoutID :exec
DELETE FROM apollo.exercises
WHERE workout_id = $1
`

func (q *Queries) DeleteExercisesByWorkoutID(ctx context.Context, workoutID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExercisesByWorkoutID, workoutID)
	return err
}

const finishWorkout = `-- name: FinishWorkout :one
UPDATE apollo.workouts
SET status = 'finished',
    finished_at = $3
WHERE id = $1
  AND user_id = $2
  AND status = 'in_progress'
RETURNING id, user_id, started_at, status, finished_at, notes, metadata
`

type FinishWorkoutParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FinishedAt pgtype.Timestamptz
}

type FinishWorkoutRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	StartedAt  pgtype.Timestamptz
	Status     string
	FinishedAt pgtype.Timestamptz
	Notes      *string
	Metadata   []byte
}

func (q *Queries) FinishWorkout(ctx context.Context, arg FinishWorkoutParams) (FinishWorkoutRow, error) {
	row := q.db.QueryRow(ctx, finishWorkout, arg.ID, arg.UserID, arg.FinishedAt)
	var i FinishWorkoutRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.Status,
		&i.FinishedAt,
		&i.Notes,
		&i.Metadata,
	)
	return i, err
}

const getInProgressWorkoutByUserID = `-- name: GetInProgressWorkoutByUserID :one
SELECT w.id, w.user_id, w.started_at, w.notes, w.metadata, w.status, w.finished_at
FROM apollo.workouts AS w
WHERE w.user_id = $1
  AND w.status = 'in_progress'
LIMIT 1
`

func (q *Queries) GetInProgressWorkoutByUserID(ctx context.Context, userID uuid.UUID) (ApolloWorkout, error) {
	row := q.db.QueryRow(ctx, getInProgressWorkoutByUserID, userID)
	var i ApolloWorkout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.Notes,
		&i.Metadata,
		&i.Status,
		&i.FinishedAt,
	)
	return i, err
}

const getWorkoutByIDForUser = `-- name: GetWorkoutByIDForUser :one
SELECT w.id, w.user_id, w.started_at, w.notes, w.metadata, w.status, w.finished_at
FROM apollo.workouts AS w
WHERE w.id = $1
  AND w.user_id = $2
LIMIT 1
`

type GetWorkoutByIDForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetWorkoutByIDForUser(ctx context.Context, arg GetWorkoutByIDForUserParams) (ApolloWorkout, error) {
	row := q.db.QueryRow(ctx, getWorkoutByIDForUser, arg.ID, arg.UserID)
	var i ApolloWorkout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.Notes,
		&i.Metadata,
		&i.Status,
		&i.FinishedAt,
	)
	return i, err
}

const listExercisesByWorkoutID = `-- name: ListExercisesByWorkoutID :many
SELECT e.id, e.workout_id, e.name, e.sets, e.reps, e.weight_kg, e.rpe, e.notes, e.position
FROM apollo.exercises AS e
WHERE e.workout_id = $1
ORDER BY e.position ASC, e.id ASC
`

func (q *Queries) ListExercisesByWorkoutID(ctx context.Context, workoutID uuid.UUID) ([]ApolloExercise, error) {
	rows, err := q.db.Query(ctx, listExercisesByWorkoutID, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloExercise
	for rows.Next() {
		var i ApolloExercise
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.Name,
			&i.Sets,
			&i.Reps,
			&i.WeightKg,
			&i.Rpe,
			&i.Notes,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsByUserID = `-- name: ListWorkoutsByUserID :many
SELECT w.id, w.user_id, w.started_at, w.notes, w.metadata, w.status, w.finished_at
FROM apollo.workouts AS w
WHERE w.user_id = $1
ORDER BY w.started_at DESC,
         w.id DESC
`

func (q *Queries) ListWorkoutsByUserID(ctx context.Context, userID uuid.UUID) ([]ApolloWorkout, error) {
	rows, err := q.db.Query(ctx, listWorkoutsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloWorkout
	for rows.Next() {
		var i ApolloWorkout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.Notes,
			&i.Metadata,
			&i.Status,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkoutDraft = `-- name: UpdateWorkoutDraft :one
UPDATE apollo.workouts
SET notes = $3,
    metadata = $4
WHERE id = $1
  AND user_id = $2
  AND status = 'in_progress'
RETURNING id, user_id, started_at, status, finished_at, notes, metadata
`

type UpdateWorkoutDraftParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Notes    *string
	Metadata []byte
}

type UpdateWorkoutDraftRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	StartedAt  pgtype.Timestamptz
	Status     string
	FinishedAt pgtype.Timestamptz
	Notes      *string
	Metadata   []byte
}

func (q *Queries) UpdateWorkoutDraft(ctx context.Context, arg UpdateWorkoutDraftParams) (UpdateWorkoutDraftRow, error) {
	row := q.db.QueryRow(ctx, updateWorkoutDraft,
		arg.ID,
		arg.UserID,
		arg.Notes,
		arg.Metadata,
	)
	var i UpdateWorkoutDraftRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.Status,
		&i.FinishedAt,
		&i.Notes,
		&i.Metadata,
	)
	return i, err
}
