-- name: CreateBookingRequest :one
INSERT INTO apollo.booking_requests (
    facility_key,
    zone_key,
    resource_key,
    scope,
    requested_start_at,
    requested_end_at,
    contact_name,
    contact_email,
    contact_phone,
    organization,
    purpose,
    attendee_count,
    internal_notes,
    request_source,
    intake_channel,
    status,
    version,
    created_by_user_id,
    created_by_session_id,
    created_by_role,
    created_by_capability,
    created_trusted_surface_key,
    created_trusted_surface_label,
    updated_by_user_id,
    updated_by_session_id,
    updated_by_role,
    updated_by_capability,
    updated_trusted_surface_key,
    updated_trusted_surface_label,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 'staff', 'themis', 'requested', 1, $14, $15, $16, $17, $18, $19, $14, $15, $16, $17, $18, $19, $20, $20)
RETURNING id,
          facility_key,
          zone_key,
          resource_key,
          scope,
          requested_start_at,
          requested_end_at,
          contact_name,
          contact_email,
          contact_phone,
          organization,
          purpose,
          attendee_count,
          internal_notes,
          status,
          version,
          schedule_block_id,
          created_by_user_id,
          created_by_session_id,
          created_by_role,
          created_by_capability,
          created_trusted_surface_key,
          created_trusted_surface_label,
          updated_by_user_id,
          updated_by_session_id,
          updated_by_role,
          updated_by_capability,
          updated_trusted_surface_key,
          updated_trusted_surface_label,
          created_at,
          updated_at,
          request_source,
          intake_channel;

-- name: CreatePublicBookingRequest :one
INSERT INTO apollo.booking_requests (
    id,
    facility_key,
    zone_key,
    resource_key,
    scope,
    requested_start_at,
    requested_end_at,
    contact_name,
    contact_email,
    contact_phone,
    organization,
    purpose,
    attendee_count,
    internal_notes,
    request_source,
    intake_channel,
    status,
    version,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NULL, 'public', $14, 'requested', 1, $15, $15)
RETURNING id,
          facility_key,
          zone_key,
          resource_key,
          scope,
          requested_start_at,
          requested_end_at,
          contact_name,
          contact_email,
          contact_phone,
          organization,
          purpose,
          attendee_count,
          internal_notes,
          status,
          version,
          schedule_block_id,
          created_by_user_id,
          created_by_session_id,
          created_by_role,
          created_by_capability,
          created_trusted_surface_key,
          created_trusted_surface_label,
          updated_by_user_id,
          updated_by_session_id,
          updated_by_role,
          updated_by_capability,
          updated_trusted_surface_key,
          updated_trusted_surface_label,
          created_at,
          updated_at,
          request_source,
          intake_channel;

-- name: ListBookingRequests :many
SELECT id,
       facility_key,
       zone_key,
       resource_key,
       scope,
       requested_start_at,
       requested_end_at,
       contact_name,
       contact_email,
       contact_phone,
       organization,
       purpose,
       attendee_count,
       internal_notes,
       status,
       version,
       schedule_block_id,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       updated_by_user_id,
       updated_by_session_id,
       updated_by_role,
       updated_by_capability,
       updated_trusted_surface_key,
       updated_trusted_surface_label,
       created_at,
       updated_at,
       request_source,
       intake_channel
FROM apollo.booking_requests
ORDER BY updated_at DESC, id DESC;

-- name: ListBookingRequestsByFacilityKey :many
SELECT id,
       facility_key,
       zone_key,
       resource_key,
       scope,
       requested_start_at,
       requested_end_at,
       contact_name,
       contact_email,
       contact_phone,
       organization,
       purpose,
       attendee_count,
       internal_notes,
       status,
       version,
       schedule_block_id,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       updated_by_user_id,
       updated_by_session_id,
       updated_by_role,
       updated_by_capability,
       updated_trusted_surface_key,
       updated_trusted_surface_label,
       created_at,
       updated_at,
       request_source,
       intake_channel
FROM apollo.booking_requests
WHERE facility_key = $1
ORDER BY updated_at DESC, id DESC;

-- name: GetBookingRequestByID :one
SELECT id,
       facility_key,
       zone_key,
       resource_key,
       scope,
       requested_start_at,
       requested_end_at,
       contact_name,
       contact_email,
       contact_phone,
       organization,
       purpose,
       attendee_count,
       internal_notes,
       status,
       version,
       schedule_block_id,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       updated_by_user_id,
       updated_by_session_id,
       updated_by_role,
       updated_by_capability,
       updated_trusted_surface_key,
       updated_trusted_surface_label,
       created_at,
       updated_at,
       request_source,
       intake_channel
FROM apollo.booking_requests
WHERE id = $1
LIMIT 1;

-- name: GetBookingRequestByIDForUpdate :one
SELECT id,
       facility_key,
       zone_key,
       resource_key,
       scope,
       requested_start_at,
       requested_end_at,
       contact_name,
       contact_email,
       contact_phone,
       organization,
       purpose,
       attendee_count,
       internal_notes,
       status,
       version,
       schedule_block_id,
       created_by_user_id,
       created_by_session_id,
       created_by_role,
       created_by_capability,
       created_trusted_surface_key,
       created_trusted_surface_label,
       updated_by_user_id,
       updated_by_session_id,
       updated_by_role,
       updated_by_capability,
       updated_trusted_surface_key,
       updated_trusted_surface_label,
       created_at,
       updated_at,
       request_source,
       intake_channel
FROM apollo.booking_requests
WHERE id = $1
LIMIT 1
FOR UPDATE;

-- name: UpdateBookingRequestStatus :one
UPDATE apollo.booking_requests
SET status = $2,
    version = version + 1,
    schedule_block_id = $3,
    internal_notes = COALESCE($4, internal_notes),
    updated_by_user_id = $5,
    updated_by_session_id = $6,
    updated_by_role = $7,
    updated_by_capability = $8,
    updated_trusted_surface_key = $9,
    updated_trusted_surface_label = $10,
    updated_at = $11
WHERE id = $1
  AND version = $12
RETURNING id,
          facility_key,
          zone_key,
          resource_key,
          scope,
          requested_start_at,
          requested_end_at,
          contact_name,
          contact_email,
          contact_phone,
          organization,
          purpose,
          attendee_count,
          internal_notes,
          status,
          version,
          schedule_block_id,
          created_by_user_id,
          created_by_session_id,
          created_by_role,
          created_by_capability,
          created_trusted_surface_key,
          created_trusted_surface_label,
          updated_by_user_id,
          updated_by_session_id,
          updated_by_role,
          updated_by_capability,
          updated_trusted_surface_key,
          updated_trusted_surface_label,
          created_at,
          updated_at,
          request_source,
          intake_channel;

-- name: GetBookingRequestIdempotencyByKeyHashForUpdate :one
SELECT key_hash,
       payload_hash,
       booking_request_id,
       created_at
FROM apollo.booking_request_idempotency_keys
WHERE key_hash = $1
LIMIT 1
FOR UPDATE;

-- name: LockBookingRequestIdempotencyKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0));

-- name: CreateBookingRequestIdempotencyKey :one
INSERT INTO apollo.booking_request_idempotency_keys (
    key_hash,
    payload_hash,
    booking_request_id,
    created_at
)
VALUES ($1, $2, $3, $4)
RETURNING key_hash,
          payload_hash,
          booking_request_id,
          created_at;
